### ISSUE TITLE
Collision detection and drag bounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#10]
For #8... Reported by my younger self on 2/29/2008 in https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/283:

> Two problems:
> 
> (1) When a drag collision occurs, the drag stops whereever the object was, instead of moving the object as close as possible. To see this problem... Grab the magnet and drag it quickly towards the coil. The magnet will stop at some distance away from the coil. It should stop right up again the coil.
> 
> (2) Objects are treated as rectangles. Diagonally drag the compass towards end of the bar magnet, and you'll see the problem.  The problem is especially noticable for collisions between 2 circular objects.
> 
> Relevant classes are CollisionDetector and FaradayMouseHandler.

Additional ticket comments:

> Issue (2) was addressed in [#2438](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2438), and collision bounds are now Shapes.

> In duplicate ticket [#2854](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2854), Sam M. suggested: Sometimes you can drag the compass through the loop and sometimes you can't.  I think it would be better to just turn off collision detection here.

The ticket status is "Reassigned" and it's unclear whether anything was ever done to addres this (I doubt it).

**Comment by pixelzoom** [comment]
To be discussed at 12/2/23, since I'm about to start working on collision detection.

**Comment by pixelzoom** [comment]
Some notes and decisions about collision detection from 12/20/23 meeting with @arouinfar:

* Collision detection as implemented in the Java version presents problems for alt input, making the sim less accessible. So we should simplify collision detection, and use it only where needed.

* The compass and field meter will be "magic tools" that are always on top.  They will not appear to pass through the pickup coil. They will not participate in collision detection. This is a change from the Java version for the compass.

* Because the compass can now be dragged anywhere, it needs to behave correctly inside the bar magnet. (I suspect that this will be relatively easy.)

* As in the Java version, there will be no collision detection between the electromagnet and the pickup coil in the Transformer screen.  That would make it impossible to pass the electromagnet through the pickup coil.

* Collision detection will occur only on the Pickup Coil screen, between the bar magnet and the pickup coil.

* Collision detection make it very difficult to automatically move the bar magnet and pickup coil inside the visibleBounds. So we will limit their drag bounds to the layoutBounds.  Same for electromagnet.  The compass and field meter can be dragged anywhere in the visibleBounds, and will be automatically moved when outside visibleBounds.

**Comment by pixelzoom** [comment]
I discussed drag bounds with @arouinfar in this morning's standup meeting.  Notes:

* We'll start with the simplest implementation of dragBounds -- layoutBounds minus the panels (and any space below the panels).
* We will not attempt to automatically reposition things when panel size changes. This is an edge case, difficult to do when combined with collision detection, and unlikely that locale will be changed after starting to work with the sim.  If something is "lost" behind a panel, it's recoverable by pressing resetAllButton.

**Comment by pixelzoom** [comment]
@arouinfar please take drag bounds for a test drive, let me know how it feels.

* Compass and field meter are constrained to visible bounds, and are in front of everything, including panels.  If the browser window is resized, it's possible to "lose" the compass or field meter.  Recover by pressing `resetAllButton`. Automatically moving them back inside visible bounds is complicated, because it introduces Property-reentry problems, and does not feel worth the effort/complexity.

* Bar magnet, electromagnet, and pickup coil are constrained to layoutBounds, up to the left edge of the panels. This feels generally good to me.  The bar magnet in the _Bar Magnet_ screen is the only case that feels a little overly-constrained, because there's a big chunk of space below the panels. But I think it's an acceptable compromise.

**Comment by pixelzoom** [comment]
@arouinfar and I reviewed the drag bounds, and we're both very happy with how its working.

We also discussed collision detection, and we recommend NOT implementing collision detection for the HTML5 version. We'll run this decision past the team. But the reasons are:

(1) The only place we planned to have collision detection was between bar magnet and pickup coil in the _Pickup Coil_ screen.
(2) The collision detection code in the Java version was complicated, and caused continuous problems and bug reports. It would likely be the same in the HTML5 version.
(3) In other screens, things magically move through the pickup coil, so why not the bar magnet too?
(4) Collision detection create a usability hurdle for accessibility (probably the most compelling argument for leaving it out).

**Comment by pixelzoom** [comment]
1/25/2024 design meeting: @arouinfar @kathy-phet @ariel-phet @pixelzoom 

Drag bounds are fine.  

Punting on collision detection is fine.

Having the compass in front of the magnets is problematic, because it would be measuring something different.  To try to avoid this confusion, make the following changes:
- [x] All screens: change drag bounds for the compass to visible bounds, but not further to the right of panels.left.
- [x] Bar Magnet, Pickup Coil screens: move compass behind bar magnet
- [x] Electromagnet, Transformer screens: move compass to inside electromagnet
- [x] Generator screen: move behind bar magnet
- [x] Generator screen: change initial position of compass -- to right of pickup coil, on its x axis

**Comment by pixelzoom** [comment]
@arouinfar The changes we discussed at yesterday's design meeting (listed in https://github.com/phetsims/faradays-electromagnetic-lab/issues/10#issuecomment-1911160748) are implemented.  Please test drive and let me know how this feels.  Then we can have the team review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Everything looks good on main. I was a little concerned that the compass would be difficult to grab when behind the generator, but it was surprisingly easy.

**Comment by pixelzoom** [comment]
Great. Closing.

**Comment by pixelzoom** [comment]
@kathy-phet @ariel-phet please review. Let me know if the new layering order for the compass works for you.

**Comment by ariel-phet** [comment]
@pixelzoom although as we knew the layering is a little odd when moving through the coils (the compass sort of moving magically through the wires) I personally think it works. It actually provides a reasonable cue that the compass is reading the "plane" of magnetic field that is centered on the coil. I think this implementation works nicely and definitely avoids lots of potential confusions of allowing the compass to read the interior of the bar magnet.

**Comment by kathy-phet** [comment]
@pixelzoom @arouinfar - Sorry for the delayed feedback here: 

The compass behavior seems like a good improvement over being on top, and the drag bounds sees to work nicely. The lack of collision detection seemed to work well - though a magical PhET thing. :) 

In this review, I noticed that the field meter has a similar issue in that it appears to be "in front" of the magnet and electromagnet, but measures the inside of it. I currently has exactly the behavior of the Java sim and as I thought through what would happen if it was in the "same layer" as the compass that seemed more problematic than not. So I guess for the teacher tips, just note that it is "magical" and "measuring in the center plane" or something like that?

**Comment by pixelzoom** [comment]
Thanks for the review @kathy-phet.  I added the suggestion about the field meter to the Teacher Tips issue, https://github.com/phetsims/faradays-electromagnetic-lab/issues/40#issuecomment-1961941970.

Closing.

**Comment by pixelzoom** [comment]
... and just to demonstrate how messy things get if we were to put the field meter in the same layer as the compass, see the screenshot below.  It becomes difficult to ready the meter, or to tell where the meter's probe is located.

<img width="379" alt="screenshot_3049" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/ba90c486-45ed-424c-8a6b-de2de02d4688">
