### ISSUE TITLE
Number of loops in electromagnet should affect the strength of the B-field

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-electromagnetic-lab#102]
Reducing the number of coils should reduce the strength of the magnetic field generated by the electromagnet. For example, with the DC current source set to 10V, the magnetic field at the center of the coil should be 75 G/coil (4 coils 300 G, 3 coils 225 G, etc.). This is how the Java sim behaves. However, on main, the magnetic field generated by the electromagnet is unaffected by the number of coils, which is incorrect.

Java:
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/b73eacde-55c7-4883-95b2-1a2210457f29" width=250> <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/b2b7f5d7-e613-4843-b850-68ee85542b85" width=250>
 
Main:
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/e998327d-8d36-40ab-95c6-a204de521003" width=250> <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/926ead65-f60f-4f07-992d-4f1ff28afaf3" width=250>

**Comment by pixelzoom** [comment]
Good catch - this was a porting error.  I omitted `coil.numberOfLoopsProperty` from a dependency list.

@arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Looks good on main, thanks @pixelzoom!
