### ISSUE TITLE
Incorrect loop area for pickup coil.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#104]
It looks like the Loop Area is working incorrectly for the pickup coil in the HTML5 version.  See comparison below of Loop Area = 100%.   I'm guessing that this is a radius vs diameter bug.  @arouinfar FYI.

Java version:

<img width="1024" alt="screenshot_3083" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/cfefbea3-97a0-4184-901a-d142da1d9d17">

<br>
HTML5 main:

<img width="974" alt="screenshot_3085" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/df6566d4-d61b-480a-9568-871c58853001">

**Comment by arouinfar** [comment]
@pixelzoom could it be the changes from https://github.com/phetsims/faradays-electromagnetic-lab/issues/48? I thought the Java version said "area" but was really "radius" and in HTML5 we made the change to actually map to area. I could be misremembering.

**Comment by pixelzoom** [comment]
This problem snuck in sometime between [1.0.0-dev.8](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.8/phet/faradays-electromagnetic-lab_en_phet.html) (1/17/24) and [1.0.0-dev.9](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.9/phet/faradays-electromagnetic-lab_en_phet.html) (1/23/24).

https://github.com/phetsims/faradays-electromagnetic-lab/issues/48 is a candidate, but most of the work there was completed before 1.0.0-dev.8 was published.

**Comment by pixelzoom** [comment]
This is fixed in the above commits.  Highly likely that it was introduced in the tail end of #48.    What was not clear from the Java codes is that setting `maxLoopArea: 35342` was not really setting the maximum area -- it was setting the area at the initial 50% setting of the Loop Area control.   So the fix was to double the value,  `maxLoopArea: 70685`.

@arouinfar please review, compare to Java version, close if OK.

**Comment by pixelzoom** [comment]
Reviewing this issue with @arouinfar on Zoom, we noticed that the larger pickup coil loop area resulted in overlap with the time control buttons on the Generator screen.  So we adjusted positions, and I factored out some constants to make it easier to adjust positions in all screens. 

@arouinfar and I also briefly considering reducing maxLoopArea for the coils, and/or changing the minimum value (%) for the Loop Area control. We decided that this was a can of worms that we didn't want to open, hence the repositioning.

@arouinfar When you're reviewing this issue, please set the pickup coil to 4 loops, 100% loop area, and have a look at the positions for things in all screens.

**Comment by pixelzoom** [comment]
I should note that @arouinfar and I briefly considering reducing `maxLoopArea` for the coils, and/or changing the minimum value (%) for the Loop Area control.  We decided that this was a can of worms that we didn't want to open, hence the repositioning mentioned above.

**Comment by arouinfar** [comment]
> @arouinfar When you're reviewing this issue, please set the pickup coil to 4 loops, 100% loop area, and have a look at the positions for things in all screens.

Looks good on main, thanks @pixelzoom.
