### ISSUE TITLE
Add `enabledProperty` to `waterFaucetNode`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-electromagnetic-lab#105]
In writing #16, I noticed that the `waterFaucetNode` doesn't have an instrumented `enabledProperty`. There currently isn't any way for clients to disable interaction with the FacuetNode, which seems important for maintaining a particular flow rate or setting up predictions. 

@pixelzoom can you please instrument an `enabledProperty` and designate it `phetioFeatured: true`? If it ends up in the model, please link it under `waterFaucetNode`.

**Comment by pixelzoom** [comment]
Done in the above commits.  @arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! Looks good on main, closing.
