### ISSUE TITLE
Transformer screen should have 75% for initial Loop Area.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#106]
In the Java version, Transformer screen, the pickup coil's loop area is initially 75%, which differs from the other screens that have a pickup coil.  It's currently 50% in all screens of the HTML5 version.

**Comment by pixelzoom** [comment]
Fixed in the above commit.   

@arouinfar please review, close if OK.  

Btw... I don't recall why the Transformer screen starts wth Loop Area = 75%, but it was probably so that we are initially in a state where there is more response from the light bulb and voltmeter.   If you think it should be 50%, it's easy to revert.

**Comment by arouinfar** [comment]
Looks good on main, thanks @pixelzoom. Closing.
