### ISSUE TITLE
Unused term maxVoltagePercent in multilink

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#107]
Discovered in code review #103, ACPowerSupply says:

```ts
    Multilink.multilink( [ this.maxVoltagePercentProperty, this.angleRangeProperty ],
      ( maxVoltagePercent, angleRange ) => {
        this._angleProperty.value = angleRange.min;
      } );
```

The `maxVoltagePercent` appears unused.

**Comment by pixelzoom** [comment]
Yes indeed, the value of maxVoltagePercentProperty is unused, but it is indeed a dependency.  If either maxVoltagePercentProperty or angleRangeProperty is changed, then angleProperty needs to be set to the min angle.   And I'd rather have unused callback params than a partial list of callback params.  (Recall that including unused params in callbacks is up to developer discretion.)

Back to @samreid, close if OK.

**Comment by pixelzoom** [comment]
To clarify... What I've tried to do consistently (there are probably exceptions) for Multilink and DerivedProperty callbacks is:
* Include all parameters if any dependency value is used.
* Include no parameters if no dependency values are used, or if calling some other instance method.

For example:

```ts
// FELScreenView.ts, panelsBounds is not used.
    Multilink.multilink( [ this.visibleBoundsProperty, options.panels.boundsProperty ],
      ( visibleBounds, panelsBounds ) => {
        options.panels.right = visibleBounds.right - FELConstants.SCREEN_VIEW_X_MARGIN;
        options.panels.top = this.layoutBounds.top + FELConstants.SCREEN_VIEW_Y_MARGIN;
      } );
```

```ts
// FieldNode.ts
    Multilink.multilink(
      [ magnet.positionProperty, magnet.rotationProperty, magnet.strengthProperty, magnet.fieldScaleProperty ],
      () => this.update()
    );
```

**Comment by samreid** [comment]
Great! I documented it as you described, and the policy for the multilink and derived property sounds good. Closing.
