### ISSUE TITLE
Generator implies getting "free" power

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#11]
For #8... Reported by a user on 12/13/2017 in https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3759. While Unfuddle tickets were private, I've omitted the user's name and contact info here because GitHub issues are public.

> Just tried your Generator Sim and found something I think you might want to address. When adding more loops to the generator coils the lights get brighter but the flow rate of the water and generator rpm rate has remained the same. IMO this implies getting "free" power. My understanding is that if the "load" increases the flow of water past the turbine blades would need to go up to create the torque required to meet the new power demand at the new higher voltage and current. What do you think?

**Comment by pixelzoom** [comment]
I verified the behavior that is described above.  Changing the number of loops results in no RPM change.

But I don't know if this is something that is really or problem, or (if it is a problem) how to address it.

@arouinfar @ariel-phet can you please comment?

**Comment by ariel-phet** [comment]
@pixelzoom I believe this user is correct. If you want to produce more power, you basically need to put more power in. In a realistic system there will be a "back emf" that will in essence put a drag on the generator. In fact, I believe in hydroelectric power you are basically trying to turn the turbine at a constant rate, if the load from the power grid increase you have to flow more water because there is more drag on the generator. However, this situation is a bit more subtle because you are adding more coils (capturing more flux, still I think you can demonstrate this same phenomenon by moving a magnet through a single coil versus multiple coils -- you will need more force to move the magnet at an equivalent speed through multiple coils.

If we were going to address it, my guess is we could in essence add some friction factor to the model. Basically at 1 coil we imagine no friction, and then for each coil added we linearly add a small amount of friction. Maybe we say something Hollywood like for each coil added we reduce the base rotation rate by 2%, so you would have to turn up the faucet a bit to get back to the same rpm as before.  I think it could be done in fairly simplistic way that addresses the concern and does not add major complexity to the model (and I do not think would be necessary to address on the other screens).

**Comment by pixelzoom** [comment]
@ariel-phet Doesn't the load also increase as the loop area increases?  So rather than increasing the friction factor as the number of loops increases, should the friction factor increase as the coil's flux increases?

**Comment by ariel-phet** [comment]
@pixelzoom yes, sorry, I forgot that the loop area can also be changed on that screen.

**Comment by pixelzoom** [comment]
@ariel-phet and I discussed.  

Drag will be a percentage, based on total area of the loops. With 1 loop and 20% area, drag will be 0%. With 4 loops and 100% loop area, drag will be 20%.   Something like this:

```ts
    const rpmDragFactorProperty = new DerivedProperty( [
        this.pickupCoil.coil.numberOfLoopsProperty,
        this.pickupCoil.coil.numberOfLoopsProperty.rangeProperty,
        this.pickupCoil.coil.loopAreaPercentProperty,
        this.pickupCoil.coil.loopAreaPercentProperty.rangeProperty
      ],
      ( numberOfLoops, numberOfLoopsRange, loopRadius, loopRadiusRange ) => {
        const area = numberOfLoops * Math.PI * loopRadius * loopRadius;
        const minArea = numberOfLoopsRange.min * Math.PI * loopRadiusRange.min * loopRadiusRange.min;
        const maxArea = numberOfLoopsRange.max * Math.PI * loopRadiusRange.max * loopRadiusRange.max;
        return Utils.linear( minArea, maxArea, 0, 0.2, area );
      }
    );
```

The tricky part is how to tell the Turbine model about this.  There's a bit of a chicken-&-egg problem:  The Turbine needs to know about the PickupCoil in order to implement this. But the PickupCoil needs to know about the Turnbine in order to be created.

**Comment by pixelzoom** [comment]
Implemented in the above commit, @ariel-phet @arouinfar please review.

`?turbineDragFactor` is a query parameter used to tune this feature.  It's the drag factor that's applied with 4 loops and 100% loop area, it defaults to `0.2`, and it must be > 0 and < 1.  Let me know if you'd like to change the default.

Drag increases as the total area (number of loops * area of 1 loop) increases.  In order to see any change in RPMs with smaller number of loops and loop area, I had to add 1 decimal place to the RPM display.   If you're interested, here's the implementation in Generator.ts:

```ts
    // Apply drag to the turbine based on the characteristics of the pickup coil.
    // See https://github.com/phetsims/faradays-electromagnetic-lab/issues/11
    const numberOfLoopsRange = this.pickupCoil.coil.numberOfLoopsProperty.range;
    const loopRadiusRange = this.pickupCoil.coil.loopRadiusRange;
    const dragFactorRange = this.turbine.dragFactorProperty.range;
    Multilink.multilink( [ this.pickupCoil.coil.numberOfLoopsProperty, this.pickupCoil.coil.loopRadiusProperty ],
      ( numberOfLoops, loopRadius ) => {
        const area = numberOfLoops * Math.PI * loopRadius * loopRadius;
        const minArea = numberOfLoopsRange.min * Math.PI * loopRadiusRange.min * loopRadiusRange.min;
        const maxArea = numberOfLoopsRange.max * Math.PI * loopRadiusRange.max * loopRadiusRange.max;
        this.turbine.dragFactorProperty.value = Utils.linear( minArea, maxArea, dragFactorRange.min, dragFactorRange.max, area );
      } );
```

And FYI, here's how the RPM value is derived in the Turbine model:

```ts
const MAX_RPM = 100;
...
    const rpmRange = new Range( ( flowRateRange.min / 100 ) * MAX_RPM, ( flowRateRange.max / 100 ) * MAX_RPM );
    this.rpmProperty = new DerivedProperty( [ this.waterFaucet.flowRateProperty, this.dragFactorProperty ],
      ( flowRate, dragFactor ) => ( 1 - dragFactor ) * ( flowRate / 100 ) * MAX_RPM, {
        isValidValue: rpm => rpmRange.contains( rpm ),
        units: 'rpm',
        tandem: tandem.createTandem( 'rpmProperty' ),
        phetioValueType: NumberIO,
        phetioFeatured: true
      } );
```

The important bit is:

```ts
( flowRate, dragFactor ) => ( 1 - dragFactor ) * ( flowRate / 100 ) * MAX_RPM
```

with ranges flowRate [0,100]% and dragFactor [0,0.2].

**Comment by pixelzoom** [comment]
FYI, here how the RPM value is derived in the Turbine model:

```ts
    const rpmRange = new Range( ( flowRateRange.min / 100 ) * MAX_RPM, ( flowRateRange.max / 100 ) * MAX_RPM );
    this.rpmProperty = new DerivedProperty( [ this.waterFaucet.flowRateProperty, this.dragFactorProperty ],
      ( flowRate, dragFactor ) => {
        const rpm = ( flowRate / 100 ) * MAX_RPM;
        return rpm - ( dragFactor * rpm );
      }, {
        isValidValue: rpm => rpmRange.contains( rpm ),
        units: 'rpm',
        tandem: tandem.createTandem( 'rpmProperty' ),
        phetioValueType: NumberIO,
        phetioFeatured: true
      } );
```

**Comment by ariel-phet** [comment]
@pixelzoom I think this general interaction feels good.

One thing we probably need to change (that I did not think about initially) -- I forgot that we can also change magnet strength on this screen, so we probably need to incorporate that into the change as well. So for instance, if right now the magnet strength is set to "0" you still get a change in RPM, but that should not be occurring. The magnet strength I think can just be a straight multiplicative factor into your current implementation (from 0 to 1).

**Comment by pixelzoom** [comment]
Good catch @ariel-phet.  I added the suggested multiplicative factor [0,1] to the derivation of the drag factor.  Please give it a test-drive.  Assign back to me when you're done, so I can delete `?turbineDragFactor`.

**Comment by pixelzoom** [comment]
@ariel-phet and I met on Zoom.  There's a problem with just applying a multiplicative factor for magnet strength.  The code is currently:

```ts
const area = numberOfLoops * Math.PI * loopRadius * loopRadius;
const minArea = numberOfLoopsRange.min * Math.PI * loopRadiusRange.min * loopRadiusRange.min;
const maxArea = numberOfLoopsRange.max * Math.PI * loopRadiusRange.max * loopRadiusRange.max;
const dragFactor = ( magnetStrengthPercent / 100 ) * Utils.linear( minArea, maxArea, dragFactorRange.min, dragFactorRange.max, area );
```

The problem is that when area === minArea, the linear interpolation evaluates to 0, and the magnet strength has no effect.

**Comment by pixelzoom** [comment]
> ... The problem is that when area === minArea, the linear interpolation evaluates to 0, and the magnet strength has no effect.

I addressed this problem in https://github.com/phetsims/faradays-electromagnetic-lab/commit/20fb1a8189962290190e5cf91c21cdd2be34468a, by ensuring that the minimum drag factor due to loop area is non-zero:

```const minDragFactor = ( minArea / maxArea ) * maxDragFactor;```

And the computation for dragFactor is still:

```( magnetStrengthPercent / 100 ) * Utils.linear( minArea, maxArea, minDragFactor, maxDragFactor, area );```

... so there will be no drag when the magnet is 0G.

A potential problem (?) is that with Loops=1 and Loop Area=20%, dragging the Strength slider does not always change the value of in the RPM display.  RPM would need 2 decimal places to show that change.  Perhaps we can live with this?  1 decimal place is sort of ugly; 2 decimal places is very ugly.

@ariel-phet @arouinfar thoughts and review please.

**Comment by ariel-phet** [comment]
@pixelzoom I don't think it is necessary at that small flux to always show a change at every increment of the slider. Currently moving smoothly between low and high magnet strength shows a clear change, and moving the slider in this way is the most likely use case. I don't think there is any need to show more decimal places.

I think the current behavior is working nicely and a good improvement to the sim.

**Comment by pixelzoom** [comment]
Thanks @ariel-phet.

@arouinfar if this looks OK after your review, feel free to close.  Note that the `turbineDragFactor` query parameter described above no longer exists, and the drag factor range is [0,0.2].

**Comment by arouinfar** [comment]
Thanks @ariel-phet @pixelzoom for collaborating on this issue! I'm really pleased with this solution, and the behavior on main looks great.
