### ISSUE TITLE
Pointer areas for CoilNode have unexpected geometry

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#111]
When reviewing pointer areas as part of https://github.com/phetsims/faradays-electromagnetic-lab/issues/103, @samreid and I noticed some unexpected behavior for the pointer geometry of CoilNode. When the mouse is in the gap between two wires in a coil, sometimes the cursor shows a pointer hand (when hovering off-center vertically on the back part of the coil), and sometimes it does not show a pointer hand (when hovering over the vertical center of the back of the coil, or anywhere in the gap of the front of the coil. See screenshots below.

<img width="1728" alt="Screen Shot 2024-03-20 at 10 21 11 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/b5bf3644-f060-4c36-8b1c-053ec27d2180">
<img width="1728" alt="Screen Shot 2024-03-20 at 10 21 03 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/5b054d65-40ea-4196-a7a5-e30b08f4b5b5">
<img width="1728" alt="Screen Shot 2024-03-20 at 10 21 00 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/48fc18e5-2533-4408-a2b1-c58b546cf063">
<img width="1728" alt="Screen Shot 2024-03-20 at 10 20 49 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/491e637e-5b58-482d-abaf-234230b2a593">

We would like to discuss this with @pixelzoom to see if this is intended, and if so could we find a way to leverage showPointerAreas to make it more clear what is clickable when trying to grab the CoilNode.

Note: When investigating this, @samreid and I had some success with the following line of code at the end of the `CoilSegmentNode` constructor:

```
this.touchArea = coilSegment.toShape().getStrokedShape( new LineStyles( { lineWidth: wireWidth } ) );
```

This allowed us to visualize the touch area, but we were surprised to see that it did not match the hover state of the pointer in the regions described above. See screenshot:

![Screen Shot 2024-03-20 at 10 29 22 AM](https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/1be97f56-36c7-4b5d-a970-097d71205144)

**Comment by samreid** [comment]
We tried adjusting the pointer overlay to see if it revealed anything.  Here is the patch:

<details>

```diff

Subject: [PATCH] Rename angleStabilizerProperty => angleStabilityProperty and related names, see https://github.com/phetsims/projectile-data-lab/issues/252
---
Index: js/overlays/PointerAreaOverlay.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/overlays/PointerAreaOverlay.ts b/js/overlays/PointerAreaOverlay.ts
--- a/js/overlays/PointerAreaOverlay.ts	(revision 131daef9d8f0aa1fb70370ee1fedbd5cc8d873b6)
+++ b/js/overlays/PointerAreaOverlay.ts	(date 1710945694032)
@@ -8,7 +8,7 @@
 
 import Bounds2 from '../../../dot/js/Bounds2.js';
 import { Shape } from '../../../kite/js/imports.js';
-import { Display, TOverlay, Node, scenery, ShapeBasedOverlay, Trail } from '../imports.js';
+import { Display, TOverlay, Node, scenery, ShapeBasedOverlay, Trail, Path } from '../imports.js';
 
 export default class PointerAreaOverlay extends ShapeBasedOverlay implements TOverlay {
   public constructor( display: Display, rootNode: Node ) {
@@ -22,14 +22,21 @@
         // skip this subtree if the node is invisible
         return true;
       }
-      if ( ( node.mouseArea || node.touchArea ) && trail.isVisible() ) {
+      if ( trail.isVisible() ) {
         const transform = trail.getTransform();
 
+        let showedAnything = false;
         if ( node.mouseArea ) {
           this.addShape( transform.transformShape( node.mouseArea instanceof Bounds2 ? Shape.bounds( node.mouseArea ) : node.mouseArea ), 'rgba(0,0,255,0.8)', true );
+          showedAnything = true;
         }
         if ( node.touchArea ) {
           this.addShape( transform.transformShape( node.touchArea instanceof Bounds2 ? Shape.bounds( node.touchArea ) : node.touchArea ), 'rgba(255,0,0,0.8)', false );
+          showedAnything = true;
+        }
+
+        if ( node instanceof Path && !showedAnything && trail.isPickable() ) {
+          this.addShape( transform.transformShape( node.getStrokedShape() ), 'rgba(0,255,0,0.8)', false );
         }
       }
       return false;


```

</details>

Here is the screenshot:

<img width="1481" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/679486/63b96a4b-d9a9-457b-92bf-c3fab00fb56b">

**Comment by pixelzoom** [comment]
You should only be able to grab the coil by the wire (not in the gaps) because you need to be able to grab things that are inside the coil (and between the gaps).   This is the vetted/approved behavior.   @arouinfar do you want to revisit that?

I don't know why `CoilBackgroundNode` can be grabbed in the gaps near the very top and bottom.  I'll investigate, but I don't know if it's worth spending much time on -- it does not prevent grabbing things that are inside the coil.  It's certainly not worth going down the path that you're pursuing in phetsims/kite#105.

**Comment by pixelzoom** [comment]
@matthew-blackman said:

> Note: When investigating this, @samreid and I had some success with the following line of code at the end of the CoilSegmentNode constructor:
> 
> `this.touchArea = coilSegment.toShape().getStrokedShape( new LineStyles( { lineWidth: wireWidth } ) );`

I added the above line to CoilSegmentNode.

To determine whether this is a problem with the coil's foreground or background, I removed them one at a time in PickupCoilScreenView (around line 75). 

The foreground tests fine:

<img width="220" alt="screenshot_3103" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/358abc63-fd9c-4dc1-9326-c17aaa4aec85">

The background (as expected) exhibits the problem where the cursor change does not match the mouse area. In this screenshot, I've drawn in yellow to indicate the area where the cursor incorrectly changes to 'pointer'.  The computed mouse area look suspicious to me in the vicinity of the green arrow.



<img width="206" alt="screenshot_3107" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/e510af86-c1d8-4845-b876-8e1a797d6143">

**Comment by pixelzoom** [comment]
Pointer areas for individual CoilSegmentNodes look OK.  Here they are in order, for index 0 through 4:

<img width="187" alt="screenshot_3108" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/78c5cd88-24da-49c7-8e6f-00f48fa02639">
<img width="202" alt="screenshot_3109" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/2633a13f-5fe6-4961-9801-d3402b76a4e1">
<img width="213" alt="screenshot_3110" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/1c21eaa6-3f4e-4b69-bba7-470eed4581b2">
<img width="199" alt="screenshot_3111" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/43aba25c-52fb-4a13-9a90-074fc1da7607">
<img width="191" alt="screenshot_3112" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/75c62771-8e95-4c6b-ba91-e21533f4f77e">

**Comment by pixelzoom** [comment]
I no longer think that the pointer area looks suspecision in the vicinity of this green arrow.  Here's I'm showing CoilSegmentNodes 0, 1, and 3.

<img width="167" alt="screenshot_3115" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/99c9f276-b4e8-4810-9e5e-32e8cbb43a39">

**Comment by pixelzoom** [comment]
I've isolated the problem further.  With CoilSegmentNode 3 by itself, the cursor incorrectly changes to 'pointer' in the area that I've shaded in yellow. CoilSegmentNode 4 by itself exhibits a similar problem.

Note that I've also tried this without the electrons in the screnegraph, with no change.

<img width="181" alt="screenshot_3117" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/506383c2-a766-485b-958c-37fab12fc598">

Here's a patch to reproduce the above:

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] simplify doc, https://github.com/phetsims/faradays-electromagnetic-lab/issues/108
---
Index: js/common/view/CoilSegmentNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CoilSegmentNode.ts b/js/common/view/CoilSegmentNode.ts
--- a/js/common/view/CoilSegmentNode.ts	(revision f4d8964f9fbe8f5ead4ed967b9d500dc36d4136d)
+++ b/js/common/view/CoilSegmentNode.ts	(date 1711029950781)
@@ -9,6 +9,7 @@
 import { Path } from '../../../../scenery/js/imports.js';
 import faradaysElectromagneticLab from '../../faradaysElectromagneticLab.js';
 import CoilSegment from '../model/CoilSegment.js';
+import { LineStyles } from '../../../../kite/js/imports.js';
 
 export default class CoilSegmentNode extends Path {
 
@@ -20,6 +21,8 @@
       lineJoin: 'bevel',
       strokePickable: true
     } );
+
+    this.touchArea = coilSegment.toShape().getStrokedShape( new LineStyles( { lineWidth: wireWidth } ) );
   }
 }
 
Index: js/pickup-coil/view/PickupCoilScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/pickup-coil/view/PickupCoilScreenView.ts b/js/pickup-coil/view/PickupCoilScreenView.ts
--- a/js/pickup-coil/view/PickupCoilScreenView.ts	(revision f4d8964f9fbe8f5ead4ed967b9d500dc36d4136d)
+++ b/js/pickup-coil/view/PickupCoilScreenView.ts	(date 1711030566444)
@@ -79,7 +79,7 @@
         pickupCoilAxisNode,
         this.compassNode, // behind barMagnetNode, see https://github.com/phetsims/faradays-electromagnetic-lab/issues/10#issuecomment-1911160748
         barMagnetNode,
-        pickupCoilNode,
+        // pickupCoilNode,
         panels,
         this.fieldMeterNode,
         this.resetAllButton,
Index: js/common/view/CoilNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CoilNode.ts b/js/common/view/CoilNode.ts
--- a/js/common/view/CoilNode.ts	(revision f4d8964f9fbe8f5ead4ed967b9d500dc36d4136d)
+++ b/js/common/view/CoilNode.ts	(date 1711032166236)
@@ -105,10 +105,10 @@
     // Render the electrons that move through the coil.
     if ( options.renderElectrons ) {
       const foregroundElectronsNode = new ElectronsNode( 'foreground', coil );
-      this.foregroundNode.addChild( foregroundElectronsNode );
+      // this.foregroundNode.addChild( foregroundElectronsNode );
 
       const backgroundElectronsNode = new ElectronsNode( 'background', coil );
-      this.backgroundNode.addChild( backgroundElectronsNode );
+      // this.backgroundNode.addChild( backgroundElectronsNode );
     }
 
     // Render the segments that make up the coil's wire.
@@ -133,6 +133,12 @@
       const parentNode = ( coilSegment.layer === 'foreground' ) ? this.foregroundCoilSegmentsParent : this.backgroundCoilSegmentsParent;
       parentNode.addChild( coilSegmentNode );
     } );
+
+    this.backgroundCoilSegmentsParent.children.forEach( child => {
+      child.visible = false;
+    } );
+    this.backgroundCoilSegmentsParent.getChildAt( 3 ).visible = true;
   }
 }
 
```
</details>

@jonathanolson any thoughts this problem? Could you please have a look?

**Comment by jonathanolson** [comment]
The behavior in https://github.com/phetsims/kite/issues/105 looks like it is due to these paths having the default fillPickable:true (a bit... unfortunate, there is probably a better API design here - we use transparent rectangles for picking a lot, so we can't just turn off fill picking if it is transparent).

Turned fillPickable off in the above commit. Not sure how to test yet, since I'm working with the other kite/shape issues.

**Comment by jonathanolson** [comment]
Fixing canvasBounds for ElectronsNode also messed up the hit areas. With the above patches, I believe this should work as expected. @pixelzoom can you verify/review?

**Comment by pixelzoom** [comment]
Thanks @jonathanolson, looks good to me.  @matthew-blackman or @samreid please review, close if OK.

**Comment by matthew-blackman** [comment]
Looks good to me as well. Closing.
