### ISSUE TITLE
FieldNode compass needles are pixelated

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#113]
As part of https://github.com/phetsims/faradays-electromagnetic-lab/issues/103, @samreid and I noticed that the compass needle images comprising the FieldNode were being rendered at a lower resolution than the other compass needles throughout the sim (see screenshot below). Let's discuss if there is a way to increase their resolution so that all compass needles render at the same quality.

![Screen Shot 2024-03-20 at 11 03 21 AM](https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/366dc840-4a2b-474a-8c9a-d9274dfa9da4)

**Comment by pixelzoom** [comment]
The field needles are necessarily rendered differently than the compass needle, so there's always the likelihood that the rendering quality may vary, depending on what scenery `renderer` options are supporteed by the browser. That said...

The field (FieldNode) uses scenery Sprites.  In https://github.com/phetsims/faradays-electromagnetic-lab/issues/109, we're having problems getting the webgl renderer working, and it's currently falling back to canvas.  Until that issue is resolved, I'm not going to work on this issue.

**Comment by pixelzoom** [comment]
@matthew-blackman Please provide platform issues when creating issues like this one.  I need details on the OS and browser, with version number for both.   Also nice to know whether it's specific to one platform, or at least whether that was checked.

**Comment by pixelzoom** [comment]
On macOS + Chrome (both latest) I can only see this pixelation if I zoom in using the pan-and-zoom feature.  So I'm wondering (a) Is this how you created the screenshot above? (b) If so, how important is this?

**Comment by pixelzoom** [comment]
WebGL looks similar when zooming in with pan-and-zoom, see below.  So resolving #109 is unlikely to change this.   @jonathanolson please advise on how to make the B-field render more crisply.

<img width="291" alt="screenshot_3097" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/80281bb3-8a2c-4328-b3f9-176ed1c50e82">

**Comment by jonathanolson** [comment]
Added scaling and mipmapping to get a decent visual appearance throughout the possible zoom range. @pixelzoom can you check/review?

**Comment by pixelzoom** [comment]
Changes look great @jonathanolson -- screenshot below, zoomed in using pan-and-zoom feature.

Back to @matthew-blackman or @samreid for review, close if OK.


<img width="436" alt="screenshot_3134" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/7e3a709b-8e71-45ec-8e08-ffe757569151">

**Comment by samreid** [comment]
Everything looks great here, nice work @jonathanolson and @pixelzoom. Thanks for pointing this out @matthew-blackman. Closing.
