### ISSUE TITLE
Preference headings should have first letter of each word capitalized

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#114]
<img width="998" alt="Screen Shot 2024-03-20 at 3 44 12 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/fce1f6d7-2895-4a18-8e93-fc5b2abeba2c">

For consistency with other headings and other sims' preferences, it makes sense to also capitalize the first letter of 'Checkbox' and 'Hemisphere' in the preference headings. Discovered as part of https://github.com/phetsims/faradays-electromagnetic-lab/issues/103

**Comment by matthew-blackman** [comment]
This has been updated in the commit. @pixelzoom please review and close if this looks good to you.

**Comment by pixelzoom** [comment]
Here's what Preferences > Simulation looks like after https://github.com/phetsims/faradays-electromagnetic-lab/commit/b9e6a8385c442a4e8eed33a17533d537a0f88d04. If @arouinfar is OK with this, then please close.

<img width="791" alt="screenshot_3095" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/4c0289d6-21a4-4261-8c5a-26c85b6737f9">

But this is the first I've heard that this is a convention. And I can't say that I agree with it.  It's certianly not the convention in other sims, for example geometric-optics:
<img width="803" alt="screenshot_3096" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/9e33f970-a264-4bf1-9fb5-5bb292e7f96c">

**Comment by pixelzoom** [comment]
Reviewed with @arouinfar, and she said it looks fine.
