### ISSUE TITLE
DC power supply does not respect Ohm's law

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#117]
In #103, I noticed a troubling behavior when reviewing the DC power supply - it is not actually behaving like a voltage source. When loops are added to the wire, its resistance will change in direct proportion to the total length of the wire. If the battery is providing a constant voltage when this happens, the current in the wire should change. This is not what happens in the sim (see recording below).

https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/9f925ca0-6f5e-447d-b719-1c30658ad211

We definitely don't want to give students the idea that the same voltage can create an equal current in a wire that has 4x the resistance. This is a major departure from Ohm's law, and I feel that it presents a significant pedagogical problem to the sim. I recommend changing the slider on the DC power supply to a current slider, and making it clear that the sim is using a 'constant current' model.

**Comment by pixelzoom** [comment]
model.md explicitly says that we are not modeling resistance:

> ### Electromagnet
> ... Note that there is no model of resistance for the coil or voltage source.

@arouinfar How do you want to proceed?

**Comment by pixelzoom** [comment]
I added bold style to the overlooked resistance statement:

<img width="806" alt="screenshot_3133" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/2f9b7811-9294-41e7-8dc2-722aeb7d6ce5">

**Comment by pixelzoom** [comment]
Discussed with @arouinfar. Adding resistance and current to the model is not something we want to do. More at https://github.com/phetsims/faradays-electromagnetic-lab/issues/119#issuecomment-2021675396.

@matthew-blackman @samreid What do you think we should do next for this issue?

**Comment by pixelzoom** [comment]
Discussed with @matthew-blackman and @samreid.  The resolution for this issue is to improve the documentation in model.md.  @matthew-blackman will take a stab at that in https://github.com/phetsims/faradays-electromagnetic-lab/issues/70, and @arouinfar and I will review.

@matthew-blackman Anything else here? If not, feel free to close.

**Comment by matthew-blackman** [comment]
Being addressed in #70. Closing.
