### ISSUE TITLE
Electrons are pixelated

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#121]
Test device
MacBook Pro M1

Operating System
macOS Monterey - 12.0.1

Browser
Chrome 123.0.6312.59

As part of #103, I noticed that the electron images appear pixelated (see screenshot below). Could this be a similar issue to #113? Seeing the visual improvements to the sim from that issue being resolved, I think this is worth a similar effort.

<img width="365" alt="Screen Shot 2024-03-26 at 12 27 11 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/e5421450-c5b0-4c2f-af99-3e6c65c2512c">

**Comment by pixelzoom** [comment]
Yes, similar to #113 -- electrons are also rendered using scenery Sprites, see ElectronsNode.ts.  

Assigning to @jonathanolson, since he's also investigating #113.

**Comment by pixelzoom** [comment]
I added mipmap support using the same approach that @jonathanolson used in #113, with the same scale factors and mipmapBias. See screenshot below. 

@jonathanolson @matthew-blackman please review. Last one to review close, if everything is OK.

<img width="491" alt="screenshot_3135" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/18beaa1d-705d-4673-bc7b-a05354e83a0f">

**Comment by jonathanolson** [comment]
Looks good to me. Minor stylistic recommendation for matrix.rowMajor arguments to be split in rows of 3, so that it visually looks like the matrix representation, e.g.:

```js
this.matrix.rowMajor(
  ELECTRON_INVERSE_SCALE, 0, position.x + ELECTRON_RADIUS,
  0, ELECTRON_INVERSE_SCALE, position.y + ELECTRON_RADIUS,
  0, 0, 1
);
```
instead of
```js
this.matrix.rowMajor( ELECTRON_INVERSE_SCALE, 0, position.x + ELECTRON_RADIUS, 0,
        ELECTRON_INVERSE_SCALE, position.y + ELECTRON_RADIUS, 0, 0, 1 );
```

**Comment by matthew-blackman** [comment]
This looks great! Nice work all. Closing.

**Comment by pixelzoom** [comment]
> Minor stylistic recommendation for matrix.rowMajor arguments to be split in rows of 3

Good idea. I'll do that.
