### ISSUE TITLE
// REVIEW comments

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#122]
This issue is a catch-all for discussing/addressing all REVIEW comments from #103 that did not get their own issue.

**Comment by samreid** [comment]
Self-assigning, as I will be adding a few more // REVIEW comments. I also committed an adjustment to an existing // REVIEW comment.

**Comment by pixelzoom** [comment]
As I'm addressing REVIEW comments, I'm commiting to this issue.  I don't intended to go over these commits with the reviewers.  If you're interested in how REVIEW comments have been addressed (or not been addressed in some cases) have a look at the commits. Let me know if you have questions.

**Comment by pixelzoom** [comment]
All REVIEW comments have been addressed, or broken out into separate GitHub issues.   

Thanks! Closing.
