### ISSUE TITLE
Consider improving the workaround for zeroing out the EMF induced by switching power supplies

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#124]
Related to https://github.com/phetsims/faradays-electromagnetic-lab/issues/92 and discovered in #103, we observed this code:

```ts
    // Workaround for https://github.com/phetsims/faradays-electromagnetic-lab/issues/92, to ignore the EMF induced
    // by switching power supplies. Step the pickup coil twice, so that there is effectively no induced EMF.
    this.electromagnet.currentSourceProperty.lazyLink( () => {
      this.pickupCoil.step( ConstantDtClock.DT ); // EMF may be induced by changing from oldCurrentSource to newCurrentSource.
      this.pickupCoil.step( ConstantDtClock.DT ); // No EMF is induced because there is no flux change in newCurrentSource.
      assert && assert( this.pickupCoil.emfProperty.value === 0, `unexpected emf: ${this.pickupCoil.emfProperty.value}` );
    } );
```

This workaround works by stepping the pickupCoil twice. Here is the code that runs when pickupCoil.step is called:

```ts
  public step( dt: number ): void {
    this.updateEMF( dt );
    this.coil.step( dt );
    if ( this.currentIndicatorProperty.value === this.voltmeter ) {
      this.voltmeter.step( dt );
    }
  }

  /**
   * Updates the induced EMF (and other related Properties) using Faraday's Law.
   */
  private updateEMF( dt: number ): void {
    assert && assert( dt === ConstantDtClock.DT, `invalid dt=${dt}` );

    // Flux in the coil.
    const flux = this.getFlux();

    // Change in flux.
    this._deltaFluxProperty.value = flux - this._fluxProperty.value;
    this._fluxProperty.value = flux;

    // Induced EMF.
    this._emfProperty.value = -( this._deltaFluxProperty.value / dt );
  }
```

Furthermore `coil.step` is implemented like so:

```ts
  public step( dt: number ): void {
    if ( this.electronsVisibleProperty.value ) {
      this.electronsProperty.value.forEach( electron => electron.step( dt ) );

      // REVIEW - Shouldn't this only be fired when the electrons have moved? Or renamed to electronsSteppedEmitter
      // REVIEW - For example, when the Pickup Coil starts up, its electrons are not moving
      this.electronsMovedEmitter.emit();
    }
  }
```

We are concerned there could be unintentional side effects from this workaround, such as causing the electrons to move, or causing the needle to move, or spurious values for some of the PhET-iO instrumented Property instances. Or what if PhET-iO state is set, and the change of power supply triggers a change that overwrites the stateful values related to flux?

**Comment by pixelzoom** [comment]
> We are concerned there could be unintentional side effects from this workaround, such as causing the electrons to move, or causing the needle to move, or spurious values for some of the PhET-iO instrumented Property instances.

It may cause the electrons to move, so that may be worth investigating.  

If it causes the voltmeter to move, it won't be seen, because only the final state (needle at zero) will be rendered.

Spurious values for some of the PhET-iO instrumented Property instances?  See any DerivedProperty with more than 1 dependency and you have the potential for spurious/intermediate values.   This is no different -- there will be some stuff that changes until the system reaches a valid state.

**Comment by pixelzoom** [comment]
In the above commits, I added `clearEMF` to PickupCoil:

```ts
  /**
   * Clears any EMF that may be present in the pickup coil. By calling updateEMF twice without changing anything else,
   * there will be no change in flux, and therefore no induced EMF. This was added as a workaround to ignore the EMF
   * induced by switching power supplies. See https://github.com/phetsims/faradays-electromagnetic-lab/issues/92.
   */
  public clearEMF(): void {
    if ( this.emfProperty.value !== 0 ) {
      this.updateEMF( ConstantDtClock.DT );
      this.updateEMF( ConstantDtClock.DT );
    }
    assert && assert( this.emfProperty.value === 0, `unexpected emfProperty.value: ${this.emfProperty.value}` );
  }
```

`clearEMF` is called when the Transformer's power supply is changed:

```ts
    // Ignore the EMF induced by switching power supplies.
    this.electromagnet.currentSourceProperty.lazyLink( () => this.pickupCoil.clearEMF() );
```

Unlike the previous workaround that called `pickupCoil.step` twice, `pickupCoil.clearEMF` only calls `updateEMF` twice.  So there were be no side-effects, such as moving electrons. 

I followed these steps to verify that this is still working properly: https://github.com/phetsims/faradays-electromagnetic-lab/issues/92#issuecomment-1973763491.

Over to @samreid or @matthew-blackman to review. Close if OK.

**Comment by samreid** [comment]
The commit looks clear and helpful. Closing.
