### ISSUE TITLE
Using Math.trunc instead of Math.floor suggests that the argument could be negative.

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#126]
During code review #103, we observed 4 occurrences of `Math.trunc`, which MDN describes like so:

> The Math.trunc() static method returns the integer part of a number by removing any fractional digits.
> [...]
> Unlike the other three Math methods: [Math.floor()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/floor), [Math.ceil()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil) and [Math.round()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round), the way Math.trunc() works is very simple. It truncates (cuts off) the dot and the digits to the right of it, no matter whether the argument is a positive or negative number.

In the cases we reviewed, it seems like the argument should be non-negative, and we recommend using `Math.floor` so readers don't misconstrue the argument as possibly negative.

**Comment by pixelzoom** [comment]
Converted to `Math.floor` after fuzz testing with `assert && assert( Math.trunc( value ) === Math.floor( value ) )` at usage sites.
