### ISSUE TITLE
Consider using constructor parameter properties

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#127]
During code review #103, we observed several opportunities to use class constructor parameter properties, which are described in https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties

For example:

```ts
  private readonly numberOfSamplePoints: number;

  public constructor( numberOfSamplePoints: number ) {
    assert && assert( Number.isInteger( numberOfSamplePoints ) && numberOfSamplePoints > 0 && numberOfSamplePoints % 2 === 1,
      `invalid numberOfSamplePoints=${numberOfSamplePoints}, must be an odd integer` );
    super();
    this.numberOfSamplePoints = numberOfSamplePoints;
  }
```

could be written as:

```ts
  public constructor( private readonly numberOfSamplePoints: number ) {
    assert && assert( Number.isInteger( numberOfSamplePoints ) && numberOfSamplePoints > 0 && numberOfSamplePoints % 2 === 1,
      `invalid numberOfSamplePoints=${numberOfSamplePoints}, must be an odd integer` );
    super();
  }
```

If it is important to avoid these for any reason, including stylistic reasons, consider documenting that in the implementation notes.

**Comment by pixelzoom** [comment]
Sorry, I'm not a fan. Too often I see a confusing/inconsistent mix of parameter properties and other properties.  Or  properties with no documentation because they are parameter properties.
