### ISSUE TITLE
Mismatched parameters in DerivedProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#128]
During code review #103, we observed In FieldMeasurementTool:

```ts
    // This needs to be a new Vector2 instance, so do not pass an output vector to magnet.getFieldVector.
    this.fieldVectorProperty = new DerivedProperty(
      [ this.positionProperty, magnet.positionProperty, magnet.rotationProperty, magnet.strengthProperty ],
      ( position, rotation, strength ) => magnet.getFieldVector( position ), {
```

Note that the 2nd dependency in the array is position, but the 2nd parameter in the callback is rotation.

**Comment by pixelzoom** [comment]
Fixed in https://github.com/phetsims/faradays-electromagnetic-lab/commit/839fdd57021b47f91881fcbbaa7ab8d3dc4fc5f6. Closing.
