### ISSUE TITLE
Consider unit tests

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#131]
During the code review #103, we observed code that would benefit from unit testing. For example:

- [ ] https://github.com/phetsims/faradays-electromagnetic-lab/blob/fdc18a84596c056eef1c3d52b14ee9192b47ed90/js/common/model/CoilMagnet.ts#L81-L137
- [ ] https://github.com/phetsims/faradays-electromagnetic-lab/blob/9d427ac928f35ecb6283a3102a9fdba22a65f403/js/common/model/BarMagnetFieldGrid.ts#L132-L183

Unit tests would be helpful because they would (a) allow us to check the behavior against the ground truth for known situations and (b) prevent accidental breakage in the future.

This is not a comprehensive list of all places where unit testing may prove valuable in Faraday's Electromagnetic Lab, just some occurrences that we observed.

**Comment by samreid** [comment]
In #122 the code review recommended using common code for the quadratic bezier implementation. If common code is not used there, then QuadraticBezierSpline.ts could be another good opportunity for unit tests.

**Comment by pixelzoom** [comment]
I'm skeptical about the bits that you identified in https://github.com/phetsims/faradays-electromagnetic-lab/issues/131#issue-2209450215. I will note that those 2 methods are `@private`, have survived 19 years without unit tests, and would require a considerable test harness.

More generally, PhET has close to zero unit tests for sims, and I don't relish being the guniea pig. 

So I don't really feel like there's enough here to make a "unit tests" effort worth the hassle and expense.
