### ISSUE TITLE
Use AXON/EnabledProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#134]
From the code review #130, one item in the code review checklist says:

> When defining a boolean Property to indicate whether something is enabled with a tandem name enabledProperty, use AXON/EnabledProperty. This should be done in both the model and the view. If you're using a DerivedProperty, skip this item.

It looks like this code matches the description and should be changed: https://github.com/phetsims/faradays-electromagnetic-lab/blob/e218bbdddd2a43cface34555c6c5efcac2d6f5a8/js/generator/view/WaterFaucetNode.ts#L65-L69

**Comment by pixelzoom** [comment]
I believe that CRC item is bogus.  EnabledProperty doc says:

> In general this should never be called by clients, but instead is factored out for consistency in PhET libraries.

But let's ask @zepumph, because I seem to recall that he had some 411 on this topic in the past.

**Comment by zepumph** [comment]
I don't have a lot of preference either way. `EnabledPropety` was basically created just to factor out the tandem name `enabledProperty`. I think it would be an easy step to apply this to this sim, but also this isn't a hill I'm going to die on. It does seem like either the CRC item or the EnabledProperty doc needs to change though. 

EnabledProperty the file was created 10/2020. The CRC item was [added](https://github.com/phetsims/phet-info/commit/9cddf1f3f6d0a5d395fe45d62f1d70ab69ee0546) in 11/2020. So I'd say part of the initial implementation was the recognition that EnabledProperty could (should?) be used elsewhere. I'll update the EnabledProperty doc. Up to you two about how to proceed on the CRC item and for FEL.

**Comment by zepumph** [comment]
I really can still see it both ways, but I don't love recommending EnabledProperty given that you still have to hard code 'enabledProperty' as a string, and all the class does is assert that you spelled it right. That makes me sad.

**Comment by samreid** [comment]
It also brings these defaults:

```
      phetioDocumentation: 'Determines whether the element is enabled (true) or disabled (false).',
      phetioFeatured: true,
```

**Comment by pixelzoom** [comment]
Seems like a lot of effort just to verify that the tandem name is "enabledProperty", and the wrong place to be verifying the tandem name.  And why EnabledProperty, when we don't have VisibleProperty, InputEnabledProperty,  etc.?  

That said... I switched to EnabledProperty and gave it more specific `phetioDocumentation`:

```ts
    // For PhET-iO. See https://github.com/phetsims/faradays-electromagnetic-lab/issues/105
    const enabledProperty = new EnabledProperty( true, {
      tandem: options.tandem.createTandem( 'enabledProperty' ),
      phetioDocumentation: 'Determines whether the water faucet is enabled (true) or disabled (false).',
      phetioFeatured: true
    } );
```
