### ISSUE TITLE
Incomplete sentence in Electron.ts documentation

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#137]
From #103, we observed this code https://github.com/phetsims/faradays-electromagnetic-lab/blob/c95a7b72f185d5cf982b7833cce6f7c7bbcbecf5/js/common/model/Electron.ts#L152-L156 which has an incomplete sentence in the documentation.

**Comment by samreid** [comment]
Note we subsequently identified a better approach in https://github.com/phetsims/faradays-electromagnetic-lab/issues/141. After implementing #141, nothing more should be needed here.

**Comment by pixelzoom** [comment]
I fixed the comment anyway.  I'll have a look at https://github.com/phetsims/faradays-electromagnetic-lab/issues/141.
