### ISSUE TITLE
Use recursionDepth+1 instead of ++recursionDepth

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#139]
During code review #103, we observed this code:

https://github.com/phetsims/faradays-electromagnetic-lab/blob/c503836bdee00df9d97d63af1465b279b340d208/js/common/model/Electron.ts#L199-L201

This code incorrectly increments the recursionDepth variable. Someone debugging the code and looking at that value after the recursive call completed would see an incorrect value for recursionDepth.

This can be remedied by changing it to `recursionDepth+1` in both cases.

**Comment by pixelzoom** [comment]
Good point. I replaced `++recursionDepth` with `recursionDepth + 1` in the above commit. 

FYI, `recursionDepth` was not present in the Java implementation.  It was added as a safeguard, and its only purpose is to prevent infinite recursion via this assertion:

```ts
assert && assert( recursionDepth < this.coilSegments.length, `infinite loop? recursionDepth=${recursionDepth}` );
```

 Closing.
