### ISSUE TITLE
Alternative Input

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#14]
Alternative input is currently enabled, via this line in package.json:

```json
      "supportsInteractiveDescription": true,
```

Alternative input for this sim looks pretty straightforward. 
 
The Generator screen has a faucet. So if we want this sim to support alt input, https://github.com/phetsims/scenery-phet/issues/773 needs to be addressed. It would be a shame to do work on alt input for this sim, then turn it off like we did for pH Scale.

**Comment by pixelzoom** [comment]
12/4/2023 design meeeting: @arouinfar @ariel-phet @kathy-phet @brent-phet @pixelzoom

Work on FaucetNode (https://github.com/phetsims/scenery-phet/issues/773) is anticipated to start in Feb 2024.  That should be soon enough to make the milestone of "1.0 release in Summer 2024".

**Comment by pixelzoom** [comment]
If I want to experiment with FaucetNode, I could do so in my subclass like this:

```ts
export default class WaterFaucetNode extends AccessibleSlider( FaucetNode, 3 ) {
```

**Comment by arouinfar** [comment]
@pixelzoom I reviewed the current state of alt input on main. Overall things look good including focus order and slider step sizes.

There are a few things that still need to be worked out, perhaps these should be moved to other issues?
- [ ] https://github.com/phetsims/scenery-phet/issues/773 (kickoff meeting tomorrow)
- [ ]  Electromagnet moves when using arrow keys to adjust sliders
- [ ] Focus highlights for electromagnet and pickup coil include padding for hidden features (AC Power Supply, voltage readout)
   <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/cc261b9c-48d4-4af1-98ce-98b05254a805" width=250> <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/84d053fb-0905-4bb9-9473-5290dfa5e0cf" width=250>
- [ ] Faraday's Law-like shortcuts to slide magnet through the coil
  <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/45e71bb8-f3dd-4725-bc74-b7a268ac03a2" width=300>
- [ ] Interactive highlights for draggable objects in the Play Area aren't hooked up yet.

**Comment by pixelzoom** [comment]
> - [ ] https://github.com/phetsims/scenery-phet/issues/773 (kickoff meeting tomorrow)

Tracking for this sim in https://github.com/phetsims/faradays-electromagnetic-lab/issues/55

> -[ ] Electromagnet moves when using arrow keys to adjust sliders

Reported in #45, a common-code bug assigned to @jessegreenberg.

>  - [ ] Focus highlights for electromagnet and pickup coil include padding for hidden features (AC Power Supply, voltage readout)

Reported in #44, a common-code bug assigned to @jessegreenberg.

> - [ ] Faraday's Law-like shortcuts to slide magnet through the coil

I had planned to handle this in #25, see https://github.com/phetsims/faradays-electromagnetic-lab/issues/25#issuecomment-1866707381.  But since it's really independent of #25, I've moved it to https://github.com/phetsims/faradays-electromagnetic-lab/issues/54.

> - [ ] Interactive highlights for draggable objects in the Play Area aren't hooked up yet.

Tracking in https://github.com/phetsims/faradays-electromagnetic-lab/issues/53.

**Comment by pixelzoom** [comment]
All of the issues that @arouinfar enumerated above have been addressed and closed.   All remaining work for alt input is related to the Generator faucet, tracked in https://github.com/phetsims/faradays-electromagnetic-lab/issues/55.  So closing this issue.
