### ISSUE TITLE
Confusing comment about vectors

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#144]
During code review #103, we observed this code in FieldMeterNode.ts

```ts
    // Dynamic labels. The Java version showed a line over 'B' for these labels, presumably indicating magnitude.
    // That notation was incorrect, since 'B' is (by definition) the *magnitude* of the magnetic field. See for
    // example https://en.wikipedia.org/wiki/Magnetic_flux.
    const stringBLabelProperty = new DerivedStringProperty( [ BStringProperty ], B => `${B}` );
    const stringBxLabelProperty = new DerivedStringProperty( [ BStringProperty, xStringProperty ], ( B, x ) => `${B}<sub>${x}</sub>` );
    const stringByLabelProperty = new DerivedStringProperty( [ BStringProperty, yStringProperty ], ( B, y ) => `${B}<sub>${y}</sub>` );
```

Here is a picture of the line over the B in the Java:

<img width="309" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/679486/a13a6d5f-f936-467e-8a2e-a13f089c05e6">

It appears the line over the B is meant to indicate it is a vector, like so:

<img width="136" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/679486/5a232d39-de71-47cc-91b9-70b2adabbfaa">

In the wikipedia link, the authors use an alternate strategy for showing that it is a vector, which is to use a boldface font, like so:

<img width="248" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/679486/df97439a-3e67-4184-8365-0a663dcc2395">

Note in this image, **B** is a vector and *B* is a scalar.

**Comment by pixelzoom** [comment]
B, Bx, and By are all scalars, so the vector notation was incorrect in the Java version. @samreid Does this updated doc clarify?

```ts
    // Dynamic labels. The Java version showed a line over 'B' for these labels, presumably indicating 'vector'.
    // Using that vector notation was incorrect, because the values we are showing here are all scalars.
    // See for example https://en.wikipedia.org/wiki/Magnetic_flux.
    const stringBLabelProperty = new DerivedStringProperty( [ BStringProperty ], B => `${B}` );
    const stringBxLabelProperty = new DerivedStringProperty( [ BStringProperty, xStringProperty ], ( B, x ) => `${B}<sub>${x}</sub>` );
    const stringByLabelProperty = new DerivedStringProperty( [ BStringProperty, yStringProperty ], ( B, y ) => `${B}<sub>${y}</sub>` );
```

**Comment by samreid** [comment]
Looks good, thanks. Closing.
