### ISSUE TITLE
StringUtils.fillIn vs PatternStringProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#145]
During code review #103 we saw that FieldMeterNode.ts, ACNumberControl and PercentControl are using `StringUtils.fillIn` whereas PatternStringProperty is used in PercentControl and DCPowerSupplyNode. Would it be better to use PatternStringProperty everywhere?

**Comment by pixelzoom** [comment]
PatternStringProperty requires a `TReadOnlyProperty<string>` as its first argument.

`FieldMeterNode`:  The pattern is not a Property, and I did not want to artificially create one for a static string.  9 PatternStringProperty instances per FieldMeter x 5 screens = 45 unnecessary PatternStringProperty instances.  DerivedStringProperty is the better choices here.

`ACNumberControl`: PatternStringProperty is irrelevant here. The use of `StringUtils.fillIn` is in the `numberFormatter` option to a NumberDisplay. 

`PercentControl`: PatternStringProperty is used were appropriate. The 1 use of `StringUtils.fillIn` is in the `numberFormatter` option to a NumberDisplay. 

Reopen if I missed anything.
