### ISSUE TITLE
Consistency for emf casing

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#147]
During #103 we observed this code in PickupCoil.ts:

```ts
    this._biggestAbsEmf = 0.0;

    // Check that maxEMFProperty is calibrated properly.
    if ( FELQueryParameters.calibrateEMF ) {
      this._emfProperty.lazyLink( () => this.calibrateMaxEMF() );
    }

    this.maxEMFProperty = new NumberProperty( options.maxEMF, {
```

We saw that some variables have `Emf` and some have `EMF`. We recommend consistency here.

**Comment by pixelzoom** [comment]
The only variable I found was `_biggestAbsEmf`. I renamed it to `largestAbsoluteEMF`.

I like how you used "emf" in the issue title :)
