### ISSUE TITLE
UI Sound

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#15]
UI Sound is currently enabled, via this line in package.json:

```json
      "supportsSound": true,
```

We’ll need to decide if we want any custom sound design, mainly for draggable objects. We’ve been punting on custom sound in other similar sims (e.g. Geometric Optics) so it might be OK to also punt here.

**Comment by pixelzoom** [comment]
12/4/2023 design meeeting: @arouinfar @ariel-phet @kathy-phet @brent-phet @pixelzoom

CM: It would be nice to have a default common-code sound for draggable things.
KP: Sonification? What to sonify? 
AP: A full sound design would be complicated. There are lots of representations occurring simultaneously.
KP: Change in flux would be the one thing I'd sonify.
AP: Theremin-like sound for change in flux.
AR: Can we reuse what we did in faradays-law? I'd like to explore a pared-down sonfication.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/graphing-lines/issues/137#issuecomment-1861693224, @amanda-phet and I discovered draggable objects apparently have an (unofficial?) default sound design -- tambo's "grab" and "release" sounds.  In the above commit, I've added those grab and release sounds to all objects that are draggable using the mouse or keyboard (DragListener or KeyboardDragListener).

**Comment by pixelzoom** [comment]
1/4/24 design meeting:

Since the sim is nearing feature complete, it would be good to schedule a meeting about this issue "soon".

**Comment by pixelzoom** [comment]
We had a sound design kickoff meeting on 1/17/2024. Meeting notes, etc. live in https://docs.google.com/document/d/1IoQX0ybxgxso57yedPZB8NvkWuMLMBD71kO04k7hZHo/edit?pli=1#heading=h.qxxnnmfrpx3k.

**Comment by pixelzoom** [comment]
@arouinfar noted that we will need sound for FaucetNode.  Since it's a common code component, we'll need default sounds, and the ability to override the defaults with sim-specific sounds.

Brainstorming aspects that might need sound:
* Moving the shooter. Default might be the same as Slider default, since FaucetNode extends AccessibleSlider.
* Tap-to-dispense featured. Default might be the same as PushButton.
* flowRateProperty. Default might sound like water. 

It will be useful for whoever is doing the sound design to consult the scenery-phet demo for FaucetNode, runnable from phetmarks, to see the important behaviors/options.

_EDIT: Tracking FaucetNode sound in https://github.com/phetsims/scenery-phet/issues/840._

**Comment by arouinfar** [comment]
This issue is tracking UI Sound, which is complete apart from https://github.com/phetsims/scenery-phet/issues/840. We're currently working on full support for sound and sonification, so I don't think we need this issue anymore. Closing.
