### ISSUE TITLE
PhET-iO design completion tasks

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#151]
This issue is for tracking the 'After PhET-iO design has been completed...' steps in https://github.com/phetsims/phet-io/blob/main/doc/phet-io-instrumentation-technical-guide.md#post-publication-steps-after-phet-io-design-has-been-completed.

The remaining parts that we are aware of are:
- In main, mark package.json's add "compareDesignedAPIChanges": true, to the "phet-io" section. This will add it to perennial/data/phet-io-api-stable/ (after the automatic nightly grunt generate-data). This will start CT tests and incorporate the sim for other tasks that update or check the APIs.
- Generate the reference API by running grunt generate-phet-io-api and make sure that it is checked in to phet-io/api/.

We are confident that @pixelzoom is aware of these steps as part of https://github.com/phetsims/faradays-electromagnetic-lab/issues/103, and are using this issue to keep a paper trail.

**Comment by pixelzoom** [comment]
Thanks for this issue.  On 3/13/24, I marked all 4 sims as `phetioDesigned: true`, added them to phet-io-api-stable, generated API files, etc.   But I had neglected to add `"compareDesignedAPIChanges": true` to package.json.   That's been done in the above commits, so I'll close this issue.
