### ISSUE TITLE
State wrapper: WARNING: Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#153]
This sim sets `webgl: true` in FELSim.ts, and uses `renderer: 'webgl'` for scenery Sprites.

When running a State wrapper fuzz test with URL http://localhost:8080/phet-io-wrappers/state/?sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&audio=disabled, I see a lot of "WebGL contexts" warnings in the console, see screenshot below.   The number of warnings continues to grow as the fuzz test runs.

@jonathanolson Is this anything to be concerned about? @zepumph @samreid FYI.

<img width="556" alt="screenshot_3148" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/50bfb835-8db6-4a2f-bfa0-1e2b5bd427c1">

**Comment by jonathanolson** [comment]
Yes, it is a concern. Browsers limit the number of WebGL contexts. If you go over the limit, it essentially destroys the "oldest" context. I'm seeing some sources saying mobile browsers limit WebGL contexts to 8. (Luckily WebGPU has no limit, and this is shared, but we can't use that yet).

Scenery does try to pool these (WebGLBlock), however if you're showing 5+ WebGL layers, a Display update could theoretically need to allocate a new 5 before disposing those previous 5.

I'll look into it.

**Comment by jonathanolson** [comment]
Looks like it helps a lot to remove the inactive ScreenViews so they aren't children. Looking into this as a solution.

**Comment by jonathanolson** [comment]
Added above, we don't go past 6 contexts in this case (4 from the Transformer screen => 2 from another screen).

This might also have performance impact slowing down screen-switching (but also might speed up the sim a bit when in a single screen).

@pixelzoom can you review, and see if this looks like an OK approach?

**Comment by pixelzoom** [comment]
The new `detachInactiveScreenViews` options looks good to me. And I no longer see the "Too many active WebGL contexts" warnings when fuzzing the State wrapper.

I don't see any obvious performance impact when switching screens on my MacBook Pro.  But it might be an issue on performance-challenged platforms, so assigning to QA for a quick confirmation.

@KatieWoe or @Nancy-Salpepi, please:

* Compare the performance of [1.0.0-dev.23](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.23/phet/faradays-electromagnetic-lab_all_phet.html) to [1.0.0-dev.22](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.22/phet/faradays-electromagnetic-lab_all_phet.html) when switching screens.  Is there any noticeable difference? Is it still acceptable?
* Test on a Chromebook and older iPad if possible, and identify the test machines here.

**Comment by Nancy-Salpepi** [comment]
Testing on a Chromebook 100e there is about a 1 second delay sometimes--most noticeable when switching from the Generator Screen. I think this is still perfectly acceptable....especially since this Chromebook is on the older side (100e came out in 2017).

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi.

I think it's safe to consider this issue resolved.
