### ISSUE TITLE
Field meter is not displaying small non-zero gauss values correctly. 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#154]
Specifically it's not doing the correct thing for _negative_ small non-zero gauss values.  Here's the offending code in FieldMeterNode, where this gets skipped if `gauss` is negative:

```ts
  if ( gauss > 0 && gauss < GAUSS_MIN_DISPLAY_VALUE ) {

    // Display '< 0.01' instead of '0.00' for small non-zero values, see https://github.com/phetsims/faradays-electromagnetic-lab/issues/84
    return StringUtils.fillIn( lessThanValueUnits, {
      value: `${GAUSS_MIN_DISPLAY_VALUE}`,
      units: G
    } );
  }
```

Fixing this is straightforward, by using `Math.abs( gauss )`.  

But then there's a new problem -- what should be displayed if (for example) `gauss` is `-0.001`?   Displaying "< 0.01" does not seem correct, because it implies a positive value. 

Note that this is a problem for B<sub>x</sub> and B<sub>y</sub>, which are signed. B (magnitude) is unsigned.

**Comment by pixelzoom** [comment]
@arouinfar Thoughts on what to display for small negative values?

**Comment by arouinfar** [comment]
@pixelzoom instead of displaying "< 0.01" we could display "~ 0.00" for any value with an absolute value < 0.01. We do this in Collision Lab for small, non-zero values. When using the about "~" notation, the sign becomes irrelevant.
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/9afb9235-99e2-42cb-abad-ce65edb164d3)

**Comment by pixelzoom** [comment]
I asked a today's dev meeting, and developer's felt that the "~" notation was appropriate here.

For my first attempt, "~0.00" looks too much like a negative sign:

<img width="183" alt="screenshot_3154" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/32bc0751-2031-4c3c-a5ae-ad6a132e54d7">

Adding a space looks like it would be less likely to be confused with a negative sign, but I don't know how "~" is typically used:

<img width="192" alt="screenshot_3153" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/9e674434-30a5-4862-86a0-45a423c18637">

@arouinfar Let's discuss.

**Comment by pixelzoom** [comment]
Discussed with @arouinfar.  

We'll go with "~ 0 G" for B, Bx, By  -- see screenshot below.

We decided NOT to do the same for theta.

<img width="201" alt="screenshot_3159" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/47d6709d-4136-4917-a076-245f40a61e07">

**Comment by pixelzoom** [comment]
Test drive in main or [1.0.0-dev.20](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.20/phet/faradays-electromagnetic-lab_all_phet.html).

Over to @arouinfar for review, close if OK.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom! Closing.
