### ISSUE TITLE
LoL Deliverables

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-electromagnetic-lab#159]
For #1 

- [x] Select subset of sims/screens to share (LoL uses `screens` to split sims into single screens, and FEL suite has lots of duplication.)
- [x]  Metadata for each screen (description, vocab words, questions for before/after sim use)
- [x]  Icons
- [x] Deliver to LoL

**Comment by pixelzoom** [comment]
1.0.0 has been published for all 4 sims in the suite, so this issue can resume.

**Comment by arouinfar** [comment]
Done, closing.
