### ISSUE TITLE
examples.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#16]
This issue will track the creation of example.md for PhET-iO. As we identify things that should be in examples.md, we'll note them here.

**Comment by pixelzoom** [comment]
Explain the non-standard model coordinate system, inherited from the legacy Java version.

* +x to the right
* +y down
* +angle clockwise
* origin (0,0) at upper-left corner of layoutBounds (red rectangle visible when running with ?dev)
* any y values or angles shown in the UI have their sign flipped, to correspond to a typical mathematical coordinate system

**Comment by pixelzoom** [comment]
Electron positions are not stateful.  Electrons are a qualitative representation of the current -- number of electrons, their speed, and their direction is what's important.

**Comment by pixelzoom** [comment]
`generator.turbine.dragFactorProperty` is used to simulate drag ("back EMF") on the turbine caused by the pickup coil.  Discussed more in https://github.com/phetsims/faradays-electromagnetic-lab/issues/11.

**Comment by arouinfar** [comment]
`electromagnetNode.dragEnabledProperty: false` renders electromagnet undraggable, but leaves the sliders interactive while `electromagnetNode.inputEnabledProperty: false` disables all input.

**Comment by arouinfar** [comment]
I created examples.md in the above commit. I still need to modify it for the other FEL flavors.

**Comment by arouinfar** [comment]
Examples for all flavors of FEL have been created, closing.
