### ISSUE TITLE
Turbine rotates too fast

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#162]
In the Generator screen, I think the Turbine is rotating faster than necessary.  It's going so fast that the water wheel starts to look like its spinning in the opposite direction as the magnet.  The maximum also seems much faster than 100 RPMs. 

@arouinfar What do you think? Should we slow down the rotation?

The relevant code is in Turbine.ts, see below.  Increasing `60` slows it down.

```ts
// Maximum change in angle per clock tick.
const MAX_DELTA_ANGLE = ( 2 * Math.PI ) * ( RPM_RANGE.max / ( ConstantDtClock.FRAMES_PER_SECOND * 60 ) );
```

**Comment by arouinfar** [comment]
Good suggestion @pixelzoom. I agree, the animation looks overly fast so let's try slowing it down. How would you like to proceed, iterating after standup sometime?

**Comment by pixelzoom** [comment]
I reduced the max speed to 60 rpm.  60 seemed like a good number, because it does 1 full revolution per second.   The water wheel still looks a bit like it's running backwards, but I think it's OK.   @arouinfar Let me know what you think.  If you don't like 60 rpm, let me know what you'd like to try.

**Comment by arouinfar** [comment]
I reviewed on main and 60 rpm looks like a reasonable maximum to me. Thanks @pixelzoom! Closing.
