### ISSUE TITLE
Revisit the electromagnet user interface

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#163]
While working on #156 and #66, I was reminded how unusable the electromagnet is in the Transformer screen.  If we were just moving the electromagnet through the coil, we could probably live with the weird overlapping.  But we want to put the electromagnet in the center of the coil, and then change its voltage/frequency.  And the current user interface is really unusable for that, as shown in the screenshots below.  This is an example of a situtation where putting controls on the thing that you're controlling is not always the best user interface.

@arouinfar @ariel-phet and I discussed in an impromptu design meeting today, and we'd like to try decoupling the controls from the draggable electromagnet.  We discussed some possible ways to do this, and @arouinfar will make some Franken-mockups.  To be discussed at 5/2/24 design meeting.

<img width="311" alt="screenshot_3261" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/08ae5071-0b11-4bdb-916a-819f0975e5f4">

<img width="323" alt="screenshot_3262" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/85d11b7c-6dc3-4983-8741-36cd9d058fc3">

**Comment by arouinfar** [comment]
We discussed these mockups at the design meeting, and the team approved. The Battery Voltage should be a NumberControl instead so there is a readout. The readout will be negative when the positive terminal of the battery points to the left (opposite of default orientation).
![Screenshot 2024-05-02 at 2 04 25 PM](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/14d7de0d-ee4e-436e-a066-de422662eafe)
![Screenshot 2024-05-02 at 2 04 37 PM](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/cd52c705-626a-414a-9ac9-a0ac802484ed)

**Comment by pixelzoom** [comment]
Dev version 1.0.0-dev.26 was published before making any changes related to this issue:

* https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.26/phet/faradays-electromagnetic-lab_all_phet.html
* https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.26/phet-io/

**Comment by pixelzoom** [comment]
Major (!) changes in the above commits, especially https://github.com/phetsims/faradays-electromagnetic-lab/commit/c4150109b8f56238761005db33ece07d391c9b46.   Remaining work (panel placement, Studio tree structure,...) is indicated by TODO comments in the code that reference this issue.

@arouinfar @kathy-phet @ariel-phet This is ready for feedback.  You can test drive in main or in [1.0.0-dev.27](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.27/phet/faradays-electromagnetic-lab_all_phet.html).

Screenshots below show the new electromagnet UI in the _Transformer_ screen, for both power supplies.  _Electromagnet_ screen is identical.  

The panels labeled "DC Power Supply" and "AC Power Supply" (PhET-iO elements `dcPowerSupplyPanel` and `acPowerSupplyPanel`) are temporarily draggable, so you can experiment with their positions.  Upper-left feels best to me, despite (or maybe because of) the occlusion concerns on touch devices. 

When dragging the electromagnet (especially in the _Transformer_ screen) this new UI feels like a big improvement to me, worth the tradeoff of relocating the DC/AC controls.

<img width="1179" alt="screenshot_3266" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/7d3c5f8d-90ff-4441-bfdc-c38ae33df880">


<img width="1177" alt="screenshot_3265" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/07745d6a-ced8-4cd2-aef1-87425a6632ee">

**Comment by pixelzoom** [comment]
5/6 on Slack#faradays-electromagnetic-lab:

> FEL team: Your feedback is requested on major changes to the electromagnet UI.  Please see https://github.com/phetsims/faradays-electromagnetic-lab/issues/163#issuecomment-2097245636 and comment in the issue.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I really like these changes, and think it's a big UX improvement.

> Upper-left feels best to me, despite (or maybe because of) the occlusion concerns on touch devices.

Me too. I wasn't expecting to prefer upper-left, but I think it makes the UI look more balanced it also feels more out of the way when dragging the electromagnet/pickup coil around the play area.  I realize it's probably still a TODO, but I think the Power Supply panel should float to the left to maximize the play area.

**Comment by ariel-phet** [comment]
@pixelzoom I think this is definitely UI improvement. I think the power supply could use some pixel polishing, but definitely like the benefits of this direction.

**Comment by pixelzoom** [comment]
Here's what remains for this issue:

- [ ] Feedback from @kathy-phet.
- [ ] Power supply polishing, suggested by @ariel-phet. (Ask for specifics.)
- [ ] Decision on where to locate the DC and AC Power Supply panels.

**Comment by pixelzoom** [comment]
I have been unsuccessful in getting feedback.  I guess we'll need a design meeting for this.

**Comment by pixelzoom** [comment]
Design meeting 5/20/24 @arouinfar @kathy-phet @pixelzoom 

* Upper-left is good location for panels.  Layout should behave like right panels.
* @pixelzoom will meet with @ariel-phet to discuss pixel polishing.

**Comment by pixelzoom** [comment]
In the above commits:
* Panels are fixed to upper-left position.
* Studio tree structure was revised, after discussing with @arouinfar.

Remaining issues:

Schedule a time to discuss pixel polishing with @ariel-phet.

Decide what to do about drag bounds. It's possible to lose the compass behind the power supply panels. We can't do the same thing that we did with the panels on the right side, because we'd lose a lot of drag space.  And we don't want to attempt non-rectangular drag bounds (ala Kepler's Laws), because that's a mess.  We also can't address the problem by changing layering.  So I'm inclined to not worry about it -- the user can always press the Reset All button. @arouinfar your opinion?

**Comment by arouinfar** [comment]
The changes to the panel positioning and Studio tree all look good @pixelzoom.

> Decide what to do about drag bounds... We also can't address the problem by changing layering.

To elaborate, the compass is layered between the front/back coil segments so it appears to measure inside of the coil. We can't simply just pop it to the top layer like the Field Meter unless we are okay with breaking the 3D illusion of where the compass is measuring.

> So I'm inclined to not worry about it -- the user can always press the Reset All button. @arouinfar your opinion?

I'm also inclined to leave the z-ordering alone, but I wonder if we could reset the position of the compass when the checkbox is turned off. Right now, the compass remembers its most recent position and will reappear there when turned off/on. We could instead reset the position back to the default. This way, a "lost" compass could be retrieved by toggling the checkbox instead of resorting to the ResetAllButton.

Resetting the compass position might prevent some predictive scenarios. For example, with Magnetic Field off, you could toggle the appearance of the compass to predict what happens to the direction of the field in a particular location when the field strength is changed. This sort of interaction is a bit clunky, and I don't think it's a particularly strong pedagogical move. It could be achieved by toggling the magnetic field representation instead.

**Comment by pixelzoom** [comment]
> Right now, the compass remembers its most recent position and will reappear there when turned off/on. We could instead reset the position back to the default. 

Me no like.  It's a hack that I will be reminded of each and every time I toggle the compass visibility.

> Resetting the compass position might prevent some predictive scenarios.

We could get fancy and reset the compass position only if it's occluded.  That feels like a "clever" solution to the problem -- an adjective that raises alarms whenever I hear it applied to software.

Resetting the compass position also creates PhET-iO problems.  `compass.positionProperty` can be changed by the client. The compass may or may not end up in the position that the client set, depending on the order that state is restored. So for that reason alone, I don't think we should reset the compass position in any scenario other than pressing the resetAllButton.

**Comment by pixelzoom** [comment]
Resetting the compass position also creates PhET-iO problems.  `compass.positionProperty` can be changed by the client. The compass may or may not end up in the position that the client set, depending on the order that state is restored.  So for that reason alone, I don't think we should reset the compass position in any scenario other than pressing the `resetAllButton`.

**Comment by arouinfar** [comment]
@pixelzoom you raise some excellent points. Let's not muck about with the compass position.

**Comment by pixelzoom** [comment]
In addition to the AC/DC Power Supply panels, it's also possible to "lose" the compass behind the water faucet in the Generator screen, and behind the voltmeter in the Pickup Coil, Transformer, and Generator screens.  I'll note in the code that we're not going to do anything about these cases.

Final task is to meet with @ariel-phet about pixel polishing.

**Comment by kathy-phet** [comment]
@pixelzoom @arouinfar - When I was playing with the model today, I found I wanted to move the AC power meter closer to the coil to inspect some relationships ... eg. when is the change in flux/brightness large and small. 

So while I really like the starting position of the control panel for the electromagnet, when you have a wide screen its hard to inspect. 
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/5096804/5486ad2c-b622-4845-a7d7-a42cf91b3381)

And I would value being able to get to here: 
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/5096804/107c1100-d79c-4621-ba5c-f9183086b808)

How many downsides are there to keeping it moveable as it is in this version: 
https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.27/phet/faradays-electromagnetic-lab_all_phet.html?dev

**Comment by kathy-phet** [comment]
And maybe that helps with being able to get the compass back?

**Comment by pixelzoom** [comment]
> How many downsides are there to keeping it moveable

No major downsides that I can think of. 

Proposal:
* Draggable panels that use the same the (dynamic) drag bounds as the compass and field meter. That is, if the browser window is large, they can be dragged out of the way.  If the browser window is made smaller, the sim moves them to keep them visible.
* Independent positions for the 2 panels, PhET-iO instrumented, defaults as they are now (top left).
* (Optional?) Revert the look and color of the panels to the pseudo-3D look of the Java version (and earlier HTML5 versions). This is to distinguish them from the other non-draggable panels on the right side of the screen.

All of this is relatively straightforward, no anticipated challenges, ~1 hour.

@kathy-phet How does that proposal sound?

**Comment by pixelzoom** [comment]
> All of this is relatively straightforward, no anticipated challenges, ~1 hour.

Looks like alt input is going to be more work than anticipated. Make that ~2 hours.

**Comment by pixelzoom** [comment]
Pixel polishing meeting with @ariel-phet and @arouinfar.   Changes appear in https://github.com/phetsims/faradays-electromagnetic-lab/commit/b18f961f7a04df3ab1e7c821d5c8adcc797b5e1f.

Summary:
* Swap text and icon in panel titles.
* Smaller slider thumbs.
* Shorter track for max voltage slider.
* Longer track for frequency slider.

**Comment by pixelzoom** [comment]
Work on making the AC/DC panels draggable is done. It was a lot more work than anticipated -- drag bounds were complicated, PhET-iO was complicated, and there was a common-code bug in KeyboardDragListener (see https://github.com/phetsims/scenery/commit/31c96b4c159a1f0553b5bcd4dccd134b72e92dcd).
 
@arouinfar and I reviewed the behavior and Studio tree via Zoom. Assigning to her for a test drive.

**Comment by arouinfar** [comment]
Took this for a test drive on main and overall looks good. However, the keyboard drag speeds for the power supply panels is way too slow (probably matches the compass/field meter). There isn't any need to move them precisely, so let's match the speeds of the electromagnet/pickup coil, which are a fair bit faster.

**Comment by pixelzoom** [comment]
It was using the defaults for KeyboardDragListener.  It's now using the same as the electromagnet/pickup coil:

```ts
      dragSpeed: 600,
      shiftDragSpeed: 150,
```

Back to @arouinfar for review. Close if OK.

**Comment by arouinfar** [comment]
Looks good, thanks!
