### ISSUE TITLE
Flux Calculation Model for Generator Screen

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/faradays-electromagnetic-lab#170]
We added a new rule for the Pickup Coil screen to address challenges with getting qualitatively good behavior for the change in flux model when you increase/decrease the coil area under different scenarios. 

However, this leads to funny behavior on the generator screen as seen in these snapshots: 
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/5096804/2023f8eb-c71f-4720-be21-cc9235fecac4)
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/5096804/d115a796-6f29-443e-8056-2e54d4674800)
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/5096804/ba6dc1e1-367f-45c6-bcd6-ed26914470c5)

The "area" multiplier rectangles are updating as you change the coil area, and so the width of the area depends on the magnet position at the moment they are set. Vertical magnet --> everything narrow; Horizontal magnet --> as in Pickup Coil. 

We will need to consider for this specific case, what we want to show exactly. 

**My first instinct:** 
Since on this screen you CANNOT actually move the magnet through the coil, I suggest we just use what we had originally with the coil areas. We don't have the issue with the discontinuity we were seeing close to the bar magnet since that was just when passing it through. In this dev version: 
https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.28/phet/faradays-electromagnetic-lab_all_phet.html?dev
Behavior looks good here to me, when I inspect the flux behavior stepping through.

**Comment by pixelzoom** [comment]
> Since on this screen you CANNOT actually move the magnet through the coil, I suggest we just use what we had originally with the coil areas. 

That's what I was going to suggest.  Relatively easy, should take ~15 minutes.  I'm out, but I'll try to get to it sometime today.

**Comment by pixelzoom** [comment]
@kathy-phet @arouinfar ready for review in main or https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.30/phet/faradays-electromagnetic-lab_all_phet.html?dev

**Comment by pixelzoom** [comment]
@kathy-phet @arouinfar say this be closed.
