### ISSUE TITLE
Some sliders have grab/release sounds with keyboard nav

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#173]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1091
On the Electromagnet and Transformer screens, adjusting the sliders for the AC Power/Battery Voltage result in continuous grab and release sounds. This only happens with sliders on moveable objects and only with keyboard nav. 

**Steps to reproduce**
1. On the Electromagnet screen, tab to the slider on the DC Power Supply Panel
2. Continually press the left arrow to move the slider

**Visuals**

https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/29b728c9-e2c2-423e-beb8-5d8e090a674e

**Comment by jessegreenberg** [comment]
This was brought to my attention in https://github.com/phetsims/scenery/issues/1636 and it should be fixed. @Nancy-Salpepi can you please confirm?

**Comment by Nancy-Salpepi** [comment]
Sounds fixed in main. Should I go ahead and close this issue then @jessegreenberg?

**Comment by jessegreenberg** [comment]
Great, thanks for verifying (and finding) @Nancy-Salpepi. I will close since this was a scenery issue.
