### ISSUE TITLE
Bulb brightness is different when performing the same actions on different screens

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#174]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1091, when rapidly changing the loop area of the Pickup Coil, the brightness of the bulb is much larger on the Generator Screen than on the Pickup Coil Screen. 

**Steps to reproduce**
1. On the Generator Screen, use the mouse to rapidly increase/decrease the loop area back and forth between min and max.
2. Switch to the Pickup Coil Screen, move the magnet so it approximately the same distance between from the Pickup Coil as in the Generator Screen.
3. Use the mouse to rapidly increase/decrease the loop area back and forth between min and max. 

**Visuals**
Note: In the video I started on the Pickup Coil Screen and moved to the Generator Screen.

https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/63f48d8b-2eba-4eb8-9d6b-d29f221f307f

**Comment by Nancy-Salpepi** [comment]
I also see a difference with the voltmeters. On the Pickup Coil Screen, the arrow barely moves as the loop area changes, while on the Generator Screen, there is much more fluctuation.

**Comment by pixelzoom** [comment]
This is related to #66 (Calibration) which is currently assigned to @arouinfar for review.  So I'll unassign myself until that issue progresses.

I will note that, even after calibration, there will definitely be differences between screens.  For example, the Generator screen's calibration is optimized for the fixed positions of the magnet and pickup coil.

**Comment by arouinfar** [comment]
>  On the Pickup Coil Screen, the arrow barely moves as the loop area changes, while on the Generator Screen, there is much more fluctuation.

This is still true after #66, but I will document it in the Teacher Tips. Closing.
