### ISSUE TITLE
Power Supply Panels are missing interactive highlights

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#175]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1091, the dcPowerSupplyPanel and acPowerSupplyPanel are missing the outer interactive highlight. Highlights only appear when attempting to move a slider. When using keyboard nav, those panels have the outer highlight. 

**Steps to reproduce**
1. In the Preferences Menu, turn on interactive highlights
2. On the Electromagnet or Transformer Screen, move the pointer in the area above the slider on the dcPowerSupplyPanel
3. Grab and move the panel

**Visuals**

https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/f6bc3d86-2acf-4e57-a7d8-5403a96e513e

Here is what they look like with keyboard nav:
<img width="236" alt="Screenshot 2024-06-01 at 5 03 55 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/57d94d6a-730d-4ca8-99ac-ed78de605853">   <img width="206" alt="Screenshot 2024-06-07 at 3 58 53 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/e3d1a4c1-23dd-4e51-993e-c038ca1e8b3d">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Fixed in main. Closing!
