### ISSUE TITLE
Coils have 2 different interactive highlights

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#176]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1091, all of the moveable coils (pickup coils and power supplies) seem to have two interactive highlights (not seen with keyboard nav).

**Steps to Reproduce**

1. Turn on interactive highlights in the Preferences Menu
2. Hover pointer over the back portion of the coil
3. Hover pointer over the front portion of the coil or the object on top

**Visuals**
![IMG_4379](https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/f95d3ec5-8b5c-4c81-96af-40d91188a492)
![IMG_4380](https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/a4ff5ae9-cf99-401d-922b-0f5580ea0f60)

**Comment by jessegreenberg** [comment]
I noticed this while commenting in another issue and took a look. You could do something like this:

```patch
Subject: [PATCH] Rename vectorDelta to modelDelta and other KeyboardDragListener improvements, see https://github.com/phetsims/scenery/issues/1635
---
Index: js/common/view/PickupCoilNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/PickupCoilNode.ts b/js/common/view/PickupCoilNode.ts
--- a/js/common/view/PickupCoilNode.ts	(revision 170a3ab6c3a213f4e98c66ae5f42e405bcc01ffd)
+++ b/js/common/view/PickupCoilNode.ts	(date 1717543023139)
@@ -22,6 +22,7 @@
 import PickOptional from '../../../../phet-core/js/types/PickOptional.js';
 import PickupCoilAreaNode from './PickupCoilAreaNode.js';
 import TReadOnlyProperty from '../../../../axon/js/TReadOnlyProperty.js';
+import { Shape } from '../../../../kite/js/imports.js';
 
 type SelfOptions = {
   maxRayLength?: number; // passed to LightBulbNode
@@ -109,6 +110,12 @@
       this.cursor = cursor;
       this.backgroundNode.cursor = cursor;
     } );
+
+    // A constants highlight so that the highlight is the same for the coil and the background node, and so that
+    // it doesn't grow when the light bulb is on.
+    const interactiveHighlight = Shape.bounds( this.localBounds );
+    this.interactiveHighlight = interactiveHighlight;
+    coilNode.backgroundNode.interactiveHighlight = interactiveHighlight;
   }
 }
 

```

And apply to other things that extend FELMovableNode. Let me know if you would like me to look further.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg!

We originally agreed to live with 2 different interactive highlights over in https://github.com/phetsims/faradays-electromagnetic-lab/issues/53#issuecomment-1901282360, but if we can prevent it, that sounds nice. @pixelzoom can you investigate/try @jessegreenberg's patch?

**Comment by Nancy-Salpepi** [comment]
I think I see this mentioned in Jesse's patch, but to be sure I'll just mention that the larger interactive highlight changes size as the light beams increase in size.  (@pixelzoom note: tracking in #189)

https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/7a32ff18-cc6d-43a0-ae7b-4d2b2530b0c8

**Comment by pixelzoom** [comment]
@arouinfar and I worked on this.  We addressed it in https://github.com/phetsims/faradays-electromagnetic-lab/commit/ee7f6787c97e36c6dce80cfc9a7f1ac2bc450663 by explicitly setting focusHighlight (and therefore interactiveHighlight) to the same rectangle for both the foreground and background.  This works nicely for the pickup coil and the electromagnet.

Closing.

**Comment by pixelzoom** [comment]
Reopening. @Nancy-Salpepi would you like to review? Close if OK.

**Comment by Nancy-Salpepi** [comment]
Working nicely!
Closing.
