### ISSUE TITLE
Should the battery voltage slider stay centered when the panel size changes?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#177]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1091, with ?stringTest=dynamic, the slider stays on the left side as the panel becomes larger. Should it be centered?

**Visuals**
<img width="305" alt="Screenshot 2024-06-01 at 5 44 57 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/fb648fa0-22e2-4d2d-85b7-080a125d8941">

**Comment by arouinfar** [comment]
> Should it be centered?

I think centered would look nicer.

**Comment by pixelzoom** [comment]
This should be a simple change in DCPowerSupplyPanel.ts:

```diff
  return new VBox( {
-    align: 'left',
+    align: 'center',
```

But something has changed in common code (logic for boundsProperty?) that is causing the sim to crash when testing with `stringTest=dynamic`.   I've asked about this on Slack, and will need to circle back to this issue when that's fixed.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please verify, close if OK.  Note that you'll need to run with `?strictAxonDependencies=false` due to a regression in common code that has broken `stringTest=dynamic`.

**Comment by Nancy-Salpepi** [comment]
Looks fixed in main. Closing.
