### ISSUE TITLE
examples.md updates needed

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#178]
For https://github.com/phetsims/qa/issues/1091:
@arouinfar it looks like there were some changes in studio since you made the examples.md. The stationary panels are now under `right panels`  not `panels` in the studio tree and the `PreferenceControls` are under `simulationPreferencesPanel` not `simulationPreferencesPanel.simPreferences` . There were also a few other things that didn't seem to be instrumented (see "this doesn't exist" in the list below).

The following changes need to be made to the examples.md:

 Under **Hide Controls** 

- [x] Change: `faradaysElectromagneticLab.barMagnetScreen.view.panels.toolsPanel.fieldMeterCheckbox.visibleProperty`
To: `faradaysElectromagneticLab.barMagnetScreen.view.rightPanels.toolsPanel.fieldMeterCheckbox.visibleProperty`

- [x] Change: `faradaysElectromagneticLab.pickupCoilScreen.view.panels.barMagnetPanel.visibleProperty` 
To:
`faradaysElectromagneticLab.pickupCoilScreen.view.rightPanels.barMagnetPanel.visibleProperty`

- [x] Change: 
`faradaysElectromagneticLab.pickupCoilScreen.view.panels.pickupCoilPanel.currentIndicatorControl.visibleProperty`
To:
`faradaysElectromagneticLab.pickupCoilScreen.view.rightPanels.pickupCoilPanel.currentIndicatorControl.visibleProperty`

- [x] Change: `faradaysElectromagneticLab.pickupCoilScreen.view.panels.pickupCoilPanel.numberOfLoopsControl.visibleProperty`
To:
`faradaysElectromagneticLab.pickupCoilScreen.view.rightPanels.pickupCoilPanel.numberOfLoopsControl.visibleProperty`

- [x] Change: `faradaysElectromagneticLab.pickupCoilScreen.view.panels.pickupCoilPanel.loopAreaControl.visibleProperty`
To: 
`faradaysElectromagneticLab.pickupCoilScreen.view.rightPanels.pickupCoilPanel.loopAreaControl.visibleProperty`

- [x] Change: `faradaysElectromagneticLab.electromagnetScreen.view.panels.electromagnetPanel.currentSourceControl.visibleProperty`
To:
`faradaysElectromagneticLab.electromagnetScreen.view.rightPanels.electromagnetPanel.currentSourceControl.visibleProperty`

- [x] This doesn't exist: `faradaysElectromagneticLab.electromagnetScreen.view.electromagnetNode.dcPowerSupplyNode.voltageSlider.visibleProperty`
 It seems like there is only an enabled property for this: 
`faradaysElectromagneticLab.electromagnetScreen.view.dcPowerSupplyPanel.batteryVoltageControl.enabledProperty`

- [x] This doesn't exist: `faradaysElectromagneticLab.electromagnetScreen.view.electromagnetNode.dcPowerSupplyNode.voltsText.visibleProperty`

Under **Prevent movement of a draggable object**
- [x] This doesn't exist: `faradaysElectromagneticLab.electromagnetScreen.view.electromagnetNode.dragEnabledProperty`

Under **Preferences**
- [x] Change: `faradaysElectromagneticLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.simPreferences.magneticUnitsPreferencesControl.visibleProperty`

To: 
`faradaysElectromagneticLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.magneticUnitsPreferencesControl.visibleProperty`

- [x] Change:
`faradaysElectromagneticLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.simPreferences.addEarthCheckboxPreferencesControl.visibleProperty`
To: 
`faradaysElectromagneticLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.addEarthCheckboxPreferencesControl.visibleProperty`

- [x] Change: `faradaysElectromagneticLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.simPreferences.earthImagePreferencesControl.visibleProperty`
To: `faradaysElectromagneticLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.earthImagePreferencesControl.visibleProperty`

- [x] One last thing: I would also change the wording of the second sentence under **Hide Controls** either by eliminating the word 'to' in front of 'facilitate prediction making' or by changing the sentence (e.g. _Hide controls to scaffold student exploration or facilitate prediction-making_.)

  Current Wording: Hiding controls can scaffold student exploration or to facilitate prediction-making.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi, I should have reviewed this before we published a dev version!

This is yet again another demonstration of why https://github.com/phetsims/phet-io-sim-specific/issues/21 is a worthwhile feature.

**Comment by arouinfar** [comment]
Thanks again @Nancy-Salpepi for the detailed list of changes. It was very helpful.

I updated the examples in the above commits for all 4 sims. Further edits are needed, but will be tracked in #179.
