### ISSUE TITLE
Should we reexamine behavior of Add "Earth" Checkbox?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#179]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1091, in Studio and State wrappers, if the sim is launched with the Add "Earth" Checkbox preference on and checked, unchecking the checkbox and turning off the preference, will not prevent the Earth from showing up again in the play area on Reset All.  The Earth Checkbox, even though now hidden, will become checked again upon Reset All to restore state. Perhaps this is a case where we don't want to restore the state exactly as it was launched (I remember something different was done with the default temperature units in Greenhouse). 

**Steps to reproduce**
1. In State, Set State Rate equal to zero
2. In the Preferences menu of the Upstream Sim, turn on Add "Earth" Checkbox
3. Check the Earth Checkbox on the Bar Magnet Screen
4. Press Set State Now
5. In the Downstream Sim, uncheck the Earth checkbox 
6. Remove the checkbox using the preferences menu
7. Press Reset All

**Visuals**

https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/189c437a-95ac-477a-808b-390734741e34

**Comment by pixelzoom** [comment]
Discussed with @arouinfar.  This is a documentation issue, for examples.md.   The "Add Earth Checkbox" is a little unusual because it adds a control that allows the user to change a screen-specific Property.  The preference is not affected by "Reset All"; the sim-specific Property is.

Over to @arouinfar to address in examples.md.

**Comment by arouinfar** [comment]
I updated examples.md for the 3 sims in the suite with the Add "Earth" Checkbox preference in the above commits. Closing.
