### ISSUE TITLE
Should compass be above earth in layering?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#181]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1091
I think it would be a good idea for the compass to be layered above the Earth magnet. If you put it over the Earth to see where the compass would point at that spot, then try to pick it up again you end up dragging the Earth instead.

**Visuals**
![compassontop](https://github.com/phetsims/faradays-electromagnetic-lab/assets/41024075/a02e3285-e954-4e6b-95ec-9a7419a89eb8)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Electromagnetic Lab‬
URL: https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.32/phet/faradays-electromagnetic-lab_all_phet.html
Version: 1.0.0-dev.32 2024-05-30 15:49:49 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. While the behavior you've reported isn't great, it's unfortunately necessary. 

In https://github.com/phetsims/faradays-electromagnetic-lab/issues/10#issuecomment-1911160748, the design team decided to layer the compass behind the magnet, despite the difficulty when Earth is checked. The model is 2D and the compass measures the B-field **inside** the magnet. However, when the compass is on top of the magnet it implies that it is measuring the B-field just **outside** of the magnet which would point in the opposite direction. To avoid confusion, we chose to layer the compass behind the magnet.

Closing as wont-fix.
