### ISSUE TITLE
Initial compass position is incorrect on Pickup Coil screen.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#183]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1091
The compass on the second screen appears on the left side of the screen on the first load, but on the right with subsequent reset alls.

**Visuals**
![newcompas](https://github.com/phetsims/faradays-electromagnetic-lab/assets/41024075/6cd8f8c9-83e8-4dbd-83ba-4b22a978aa89)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Electromagnetic Lab‬
URL: https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.32/phet/faradays-electromagnetic-lab_all_phet.html
Version: 1.0.0-dev.32 2024-05-30 15:49:49 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1280x631
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
How strange! The compass used to have the same initial position on all screens, see https://github.com/phetsims/faradays-electromagnetic-lab/issues/64#issuecomment-1979757780. That was awhile ago, though, and it looks like @pixelzoom may have shifted things slightly. The initial position on the Pickup Coil screen looks completely wrong, though. Its position after reset all looks appropriate.

**Comment by pixelzoom** [comment]
@arouinfar is correct - the compass should have the same position on all screens. So it's the initial position that's incorrect on the Pickup Coil screen.

This broke sometime between https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.30/phet/ (5/24) and https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.31/phet/ (5/28).

Adding debug output to FELScreenView.ts:

```diff
+   console.log( `BEFORE: ${options.compass.positionProperty.value}` );
    Multilink.multilink( [ this.visibleBoundsProperty, options.rightPanels.boundsProperty ],
      ( visibleBounds, rightPanelsBounds ) => {
        options.rightPanels.right = visibleBounds.right - FELConstants.SCREEN_VIEW_X_MARGIN;
        options.rightPanels.top = this.layoutBounds.top + FELConstants.SCREEN_VIEW_Y_MARGIN;
      } );
+   console.log( `AFTER: ${options.compass.positionProperty.value}` );
```

... I see this console output for the Pickup Coil screen:

> BEFORE: Vector2(635, 375)
> AFTER: Vector2(0, 375)

So something about that Multilink is setting the compass' x-coordinate to 0.   Very weird...

**Comment by pixelzoom** [comment]
This broke sometime between https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.30/phet/ (5/24) and https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.31/phet/ (5/28).

**Comment by pixelzoom** [comment]
I looked at this with @zepumph.  `this.visibleBoundsProperty` and `rightPanels.boundsProperty` are also used to derive the dragBoundsProperty for the compass.  So it's likely that dragBoundsProperty is going through some intermediate state that results in the compass position being changed.

**Comment by pixelzoom** [comment]
The above commit initializes the position of `rightPanels` before creating compassNode, so that dragBoundsProperty will be correct.   This resolves the problem.

@KatieWoe please review in main, close if OK.

**Comment by KatieWoe** [comment]
Looks good!
