### ISSUE TITLE
Change cursor appearance when bar magnet is locked to axis

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#184]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1091, on the Pickup Coil Screen when 'Lock to Axis' is checked, the cursor is a hand when hovering over the bar magnet. Hovering the cursor over the Pickup Coil and Electromagnet on the Pickup Coil and Transformer Screens shows a double-sided arrow, while freely moving objects, such as the compass, have the hand cursor. Shouldn't the cursor for the bar magnet also show a double-sided arrow since its movement is now limited to the axis? 

**Steps to reproduce**
1. On the Pickup Coil Screen, check 'Lock to axis'
2. Hover pointer over the magnet.

**Visuals**

https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/09f8e3d6-5b2f-412c-8509-f2aa68075b96

**Comment by arouinfar** [comment]
> Shouldn't the cursor for the bar magnet also show a double-sided arrow since its movement is now limited to the axis?

Good catch! Looks like an oversight. @pixelzoom let's use the double-headed arrow when Lock to Axis is on.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  @Nancy-Salpepi please review in main, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good. Closing.
