### ISSUE TITLE
Update color of light rays

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-electromagnetic-lab#185]
@KatieWoe reported in https://github.com/phetsims/qa/issues/1091

> Not sure if it's worth an issue, but in projector mode, the yellow lightbeams from the bulb can be hard to see against the white background. @arouinfar

Here's what the rays currently look like in Projector Model:
<img width="304" alt="Screenshot 2024-06-07 at 2 03 02 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/09dc520e-d003-4fe5-af68-7dd188c14ac2">

The color profile includes `faradaysElectromagneticLab.lightRaysColor`, but I don't see the halo around the bulb, so I don't know if we can change it.

In Fourier: Making Waves we ran into a similar issue with the A3 harmonic (also yellow) https://github.com/phetsims/fourier-making-waves/issues/193. We improved the contrast by using `rgb(255, 210, 0)`.

Here's what that color looks like in FEL:
<img width="325" alt="Screenshot 2024-06-07 at 2 08 11 PM 1" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/7633d822-37e0-4f51-82fb-dc390bafb28e"> <img width="350" alt="Screenshot 2024-06-07 at 2 08 28 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/96d0a48e-06b2-4453-a505-d60b568f4814">

The rays and halo are noticeably different colors, but I'm not overly bothered by it. I think the improvement to usability is worth it.

@pixelzoom let's use `rgb(255, 210, 0)` for `lightRaysColor` for both profiles.

**Comment by pixelzoom** [comment]
Discussed with @arouinfar. We decided to change the color only for projector profile.
