### ISSUE TITLE
assertion errors when fuzzing debug version

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#187]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Chrome 125.0.6422.142

**Problem description**
For https://github.com/phetsims/qa/issues/1091, when fuzzing the debug version of the sim, errors appeared in the console after a few minutes. 
<img width="536" alt="Screenshot 2024-06-10 at 10 58 21 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/8718b7ee-eaad-4179-a8f5-927413f3433a">
<img width="536" alt="Screenshot 2024-06-10 at 10 57 01 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/2a078bce-6973-40e8-a5b8-f2a64edc85b9">
<img width="536" alt="Screenshot 2024-06-10 at 10 57 14 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/bcdff33c-a0f8-46de-a443-25ee6205ba85">

Troubleshooting Info
<details>

> !!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Electromagnetic Lab‬
URL: https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.32/phet/faradays-electromagnetic-lab_all_phet_debug.html
Version: 1.0.0-dev.32 2024-05-30 15:49:49 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1399x722
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@Nancy-Salpepi I have not been able to reproduce this (MacBook Pro Intel, macOS 14.5, Chrome 125.0.6422.144).  I'm using the URL shown below.  When "fuzzing the debug version", were you using any other query parameters?

https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.32/phet/faradays-electromagnetic-lab_all_phet_debug.html?ea&fuzz

**Comment by Nancy-Salpepi** [comment]
No I wasn't using any query parameters and that is the link I used. 
I tried to have it happen again right after I made this issue. I let it fuzz for 20 minutes and nothing. 

Sorry I am of no help here.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi can no longer reproduce. I've tried to reproduce this a few more times, and I've been unsuccessful.    And I would expect this to show up in CT with the general fuzz test.    So I don't know what to do other than to 🤞🏻 and close this issue.  If it comes up again, we'll revisit.
