### ISSUE TITLE
Resizing the browser window causes the magnet position to reset.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#190]
This is a weird one...  Steps to reproduce:

1. Start the sim
2. Go to Pickup Coil screen
3. Select "Lock to Axis"
4. Move the bar magnet into the center of the pickup coil
5. Resize the browser window until the magnet moves to it's inital position.

There is similar behavior with the electromagnet on the Transformer screen.

This only happens when "Lock to Axis" is on.

**Comment by pixelzoom** [comment]
Probably need to add `valueComparisonStrategy: 'equalsFunction'` to the `dragBoundProperty` instantiation.

**Comment by pixelzoom** [comment]
In addition to adding `valueComparisonStrategy: 'equalsFunction'` for  `dragBoundProperty`, this involved factoring out `FELScreenView.lockToAxisListener` so that resizing the browser window does not move the magnet and pickup coil.  

I tested quite a bit, but I'd like to have another set of eyes to verify that there was no regression introduced. @Nancy-Salpepi would you mind taking this for a quick spin?  Playing with the "Lock to Axis" feature and resizing the browser window would be sufficient.

**Comment by Nancy-Salpepi** [comment]
Great find! Looks fixed in main and I didn't see any other issues. 
Closing.
