### ISSUE TITLE
It should be possible to hide the voltage readout on the battery

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-electromagnetic-lab#191]
It used to be possible to hide the the voltage readout on the battery with `view.electromagnetNode.dcPowerSupplyNode.voltsText.visibleProperty`. 

In #178 @Nancy-Salpepi noted:

> This doesn't exist: `faradaysElectromagneticLab.electromagnetScreen.view.electromagnetNode.dcPowerSupplyNode.voltsText.visibleProperty`

We changed the design of the electromagnets over in #163, which resulted in some refactoring. Here's the current tree structure.
<img width="247" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/7d416605-3bd5-49f9-94c2-8a256b1dc00a">

@pixelzoom is there a way to restore this functionality?

**Comment by pixelzoom** [comment]
@arouinfar please review. Studio tree structure is shown below. `voltsText.visibleProperty` is featured.

<img width="226" alt="screenshot_3403" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/12f83dbc-c469-491a-ba9b-ca107f890741">

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The tree structure and behavior look good, but the `*dCPowerSupply` LinkedProperty isn't showing up in the Featured tree because `dcPowerSupplyNode` isn't featured. Can you please feature it?

**Comment by pixelzoom** [comment]
`dcPowerSupplyNode` is now featured. Back to @arouinfar, close if OK.

**Comment by arouinfar** [comment]
Looks good on main, thanks @pixelzoom. Closing.
