### ISSUE TITLE
Changes for examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#194]
For https://github.com/phetsims/qa/issues/1110:

Under Hide Controls add a tick mark thingy to the left side of
faradaysElectromagneticLab.barMagnetScreen.view.rightPanels.toolsPanel.fieldMeterCheckbox.visibleProperty`

**Comment by Nancy-Salpepi** [comment]
No other changes that I can see 🎉

EDIT: actually...one tiny change: Under Hide Controls > Electromagnet screen I would change the wording of the statement below so that it is clear that it is through the simulation itself....
 "To keep the DC current source at a fixed voltage, set the desired voltage within PhET-iO Studio or by using the voltageProperty" 

Maybe:
  "To keep the DC current source at a fixed voltage, set the desired voltage through direct interaction in the simulation or by using the voltageProperty...."

**Comment by pixelzoom** [comment]
@arouinfar there are additional potential changes noted in https://github.com/phetsims/faradays-electromagnetic-lab/issues/195.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi!

Updates made in the above commits. The changes only applied to 2 of the sims in the suite.

**Comment by KatieWoe** [comment]
The problem described in the first part of the issue is still in https://github.com/phetsims/qa/issues/1116
![Screenshot 2024-07-24 114555](https://github.com/user-attachments/assets/d927584d-e73b-4b6f-bd9e-b448de14e286)

**Comment by KatieWoe** [comment]
https://github.com/phetsims/faradays-electromagnetic-lab/issues/194#issuecomment-2231734037 is unchanged as well

**Comment by arouinfar** [comment]
@pixelzoom looks like these commits didn't make it into the RC. Comparing timestamps, the commits happened ~35  minutes before the RC build.

**Comment by pixelzoom** [comment]
I confirmed that @arouinfar made the changes before I created the 1.0 branch.  I inspected the 1.0 branch, and confirmed that those changes are indeed missing.  I'll need to cherry-pick them, and verify in 1.0.0-rc.2.

Here's what I suspect went wrong: When `grunt rc` creates a release branch, it looks like it uses the shas that are in my working copy, not the shas that are in HEAD of main.  I didn't realize that, and I probably did not do a pull-all.sh before running `grunt rc`. Therefore the changes that @arouinfar made were not included in the 1.0 branch. Sorry about that...

**Comment by pixelzoom** [comment]
Patched into relevant sims (faradays-electromagnetic-lab 1.0 and magnets-and-electromagnets 1.0) in the above commits.  Tested in local builds of 1.0.

Ready for verification in 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
To verify for https://github.com/phetsims/qa/issues/1128...  Click on Examples in the Wrapper Index, and verify that the changes shown in https://github.com/phetsims/phet-io-sim-specific/commit/7925ba2a7f0e3789c58ce29b96ce7577360fcdcd appear.

To verify for https://github.com/phetsims/qa/issues/1130... Click on Examples in the Wrapper Index, and verify that the changes shown inhttps://github.com/phetsims/phet-io-sim-specific/commit/f1c7975d7cf1e17dfb92f2e60814d1269a304792 appear.

It is sufficent to test on 1 platform. If everything looks OK, close this issue.

**Comment by Nancy-Salpepi** [comment]
This is fixed in rc.2 for FEL & Magnets and Electromagnets. 
Closing.
