### ISSUE TITLE
Setting state position of electrons and compass needles

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#196]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/1110
When setting state in the state wrapper or launching a sim from studio, the position of the electrons may not match. This is rather minor. The position of the field compass markers may also shift if the screen size/shape in studio is different from the size/shape of the launched sim. This seems to be purely visual and  does not impact the actual data from what I can tell. This is, from what I see, a minor issue.
**Visuals**
![electronposition](https://github.com/user-attachments/assets/70208efa-a378-42a8-99d4-f356a3a508e5)

**Comment by pixelzoom** [comment]
@KatieWoe reported:
> When setting state in the state wrapper or launching a sim from studio, the position of the electrons may not match. This is rather minor.

The positions of the charged particles (electrons or positive charges) is intentionally not stateful.  This is documented in ChargedParticle.ts, see below.  @arouinfar I'll let you decide whether this is significant enough to note in examples.md.

```ts
 * Note that ChargedParticle is NOT instrumented for PhET-iO. The exact positions of charges are not significant.
 * We do not care (for example) if charge positions are different in the Upstream and Downstream frames of
 * the State wrapper. What does matter is the number of charges and their speed, both of which are derived
 * from other state.
```

> The position of the field compass markers may also shift if the screen size/shape in studio is different from the size/shape of the launched sim. This seems to be purely visual and does not impact the actual data from what I can tell. This is, from what I see, a minor issue.

The field vector indicators (aka compass markers) are positioned relative to the model's origin, and their spacing is constant. So I would not expect them to "shift" or change their position relative to the other elements (magnet, compass, etc).  I would expect to see more/fewer of them as the size of the browser window is changed.  

@KatieWoe can you provide an example showing that they "shift", or steps to reproduce?

**Comment by arouinfar** [comment]
> @arouinfar I'll let you decide whether this is significant enough to note in examples.md.

It's not significant enough for examples.md. The data stream doesn't include anything about the position of the charge carriers, so I don't think we need to bring attention to it in the client-facing documentation.

**Comment by KatieWoe** [comment]
Steps:
1. Go to a particular screen in Studio (Electromagnet in example)
2. Move the sim boundaries so it is taller/less wide in Studio
3. Put the Field Meter between some obvious compass needles (between the two just to the right of the coils in the example. Note position and orientation)
4. Launch/Test
5. Observe those needles being in a slightly different position and orientation. Field Meter give the same reading as before.

![setup](https://github.com/user-attachments/assets/c2bbde9f-5f95-4d98-a29a-55da7dba1479)

**Comment by pixelzoom** [comment]
Thanks @KatieWoe, that's helpful, and thanks for reporting.

Looking at FieldNode.ts, I see that I misspoke in https://github.com/phetsims/faradays-electromagnetic-lab/issues/196#issuecomment-2231909879.  The field vector indicators do not have a consistent origin. The grid is created from top-down, left-to-right to fill the browser window.  So the position of the grid relative to the other things (magnet, compass, field meter, coil,...) will indeed shift when the size of the browser window changes.

This seems insignificant, and would be a big deal to change at this point. So I propose that we close as "won't fix".  @arouinfar if you agree, please close.

**Comment by arouinfar** [comment]
> This seems insignificant, and would be a big deal to change at this point. So I propose that we close as "won't fix". @arouinfar if you agree, please close.

I agree @pixelzoom. Closing as wont-fix.
