### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#2]
Here are the legacy (Java) credits:

<img width="616" alt="screenshot_2874" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/3df0c92a-27a4-42b5-b73d-006e10f733de">

**Comment by pixelzoom** [comment]
Here are the current credits, as of 1.0.0-dev.7.  There was no "Lead Designer" in the Java credits, so no one to credit as such here.

<img width="639" alt="screenshot_2978" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/0ba771a5-afba-4fcf-8081-d1c3ea2189dd">

**Comment by pixelzoom** [comment]
AP was added to the credits back on 1/23/24:

<img width="694" alt="screenshot_3053" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/7d075d3e-ee65-4f60-96db-4fd040e8e4d5">

**Comment by samreid** [comment]
I pushed a spelling correction.

**Comment by pixelzoom** [comment]
Credits as of 5/28/24:

<img width="680" alt="screenshot_3330" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/6921e408-fe9c-4832-857e-309bf8f4debe">

**Comment by Nancy-Salpepi** [comment]
Jaron Droder and Clifford Hardin can also be added to QA credits.

**Comment by pixelzoom** [comment]
Please identify any change to QA credits for https://github.com/phetsims/qa/issues/1110.

**Comment by Nancy-Salpepi** [comment]
Please add Matthew Moore to QA credits.

**Comment by pixelzoom** [comment]
Please identify any changes to the QA credits for RC testing of the suite: https://github.com/phetsims/qa/issues/1116, https://github.com/phetsims/qa/issues/1117, https://github.com/phetsims/qa/issues/1118, and https://github.com/phetsims/qa/issues/1119.

**Comment by KatieWoe** [comment]
Luisa Vargas should be added to QA

**Comment by pixelzoom** [comment]
The above commits added Luisa Vargas to the QA credits, and patches the 1.0 branches for all sims in the suite.

**Comment by pixelzoom** [comment]
For https://github.com/phetsims/qa/issues/1128, https://github.com/phetsims/qa/issues/1129, https://github.com/phetsims/qa/issues/1130, and https://github.com/phetsims/qa/issues/1131, please verify that the credits are as shown below.   Also specify any changes to the QA credits for these test.

It is sufficient to verify this on 1 platform.

<img width="646" alt="screenshot_3435" src="https://github.com/user-attachments/assets/ed876333-4800-4199-b5a7-93b27d5d1d95">

**Comment by Nancy-Salpepi** [comment]
Credits match those in https://github.com/phetsims/faradays-electromagnetic-lab/issues/2#issuecomment-2253643317 for all sims.
No new additions to QA credits.
