### ISSUE TITLE
iPad Graphical Artifacts

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#203]
**Device**
iPad 6th Gen
**OS**
iPadOS 17.5.1
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/1116
In the iframe for some of the PhET-iO wrappers (text-area and state for example) there are graphical artifacts left from dragging the bar magnet or other objects around the screen. I didn't notice this in the main sim, or even the standard iframe link.
**Visuals**
![IMG_0114](https://github.com/user-attachments/assets/3a5bedba-a117-4515-bdb8-e7ca2e433702)
![IMG_0115](https://github.com/user-attachments/assets/5e223fa8-9e96-48fc-b68d-aa6ae8ef0d15)
![IMG_0116](https://github.com/user-attachments/assets/741487a6-1f98-4b92-9f2d-746cd24cae76)

**Comment by pixelzoom** [comment]
This was reported previously in https://github.com/phetsims/faradays-electromagnetic-lab/issues/197 during dev testing. The consensus was that this does not need to be addressed. See comments starting at https://github.com/phetsims/faradays-electromagnetic-lab/issues/197#issuecomment-2233886102.

So closing as "duplicate" and "won't fix".
