### ISSUE TITLE
Preference to show/hide "Show Earth" checkbox on "Bar Magnet" screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#23]
Suggested in https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2423 ...

This would apply to all variants of the sim that include the Bar Magnet screen.

- [x] Use a toggle switch in the Preferences dialog
- [x] Include a instrumented BooleanProperty
- [x] Include a query parameter to set the initial value of the BooleanProperty
- [x] default to `false` for FEL & Generator sims, default `true` for Magnet & Compass sim

**Comment by pixelzoom** [comment]
The Preferences control is implemented and wired up, see screenshot below.   

* The Property is `addEarthCheckboxProperty`.
* The query parameter is `addEarthCheckbox`, values `true` and `false`. It defaults to `false` for _FEL_, and will default to `true` for _Magnet and Compass_ and _Magnets and Electromagnets_ sims.
* This query parameter and preference will be available for the _FEL_, _Magnet and Compass_, and _Magnets and Electromagnets sims_. It is irrelevant for the Generator sim, and will not be included in Preferences.

<img width="765" alt="screenshot_2920" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/3df28eff-fe5b-469c-b5f0-c613b762192d">

**Comment by pixelzoom** [comment]
Ready for review by @arouinfar.  Note that the default is `?addEarthCheckbox=false` for FEL.  The default will be `? addEarthCheckbox=true` for _Magnet and Compass_ and _Magnets and Electromagnets_ sims.   The query parameter will be irrelevant for the Generator sim.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I reviewed on main, including in Studio, and everything looks good in FEL.

Not sure if we should leave this open to review once <i>Magnet and Compass</i> and <i>Magnets and Electromagnets</i> are created or if we can close, so back to @pixelzoom to decide.

**Comment by pixelzoom** [comment]
We can leave it open.

**Comment by pixelzoom** [comment]
@arouinfar Ready for review in magnet-and-compass and magnets-and-electromagnets.  Close if OK.

**Comment by arouinfar** [comment]
I reviewed magnet-and-compass and magnets-and-electromagnets on main and the behavior looks good, closing.
