### ISSUE TITLE
Preference to change magnetic units (G vs T)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#24]
Suggested in https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3484 ...

- [x] In Preferences dialog, add radio buttons to switch between G (gauss) and T (tesla)
- [x] Add an associated instrumented Property
- [x] Add an associated query parameter to set the initial value of the Property (default=G)
- [x] Display T in scientific notation

**Comment by pixelzoom** [comment]
See screenshot below for Preference control.

* The query parameter is `magneticUnits`, value 'G' and 'T', defaults to 'G'.
* The Property is `magneticUnitsProperty`, initialized using the `magneticUnits` query parameter value.  

<img width="765" alt="screenshot_2920" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/a1e91365-d7c6-48d6-92e8-15ca09bed41b">

**Comment by pixelzoom** [comment]
Work here is done, ready for review by @arouinfar. Close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom this is all working nicely on main.

I reviewed in Studio and it looks like the associated property is `faradaysElectromagneticLab.global.model.preferences.functionVariableProperty` instead of the described `magneticUnitsProperty` so back to @pixelzoom to address.

**Comment by pixelzoom** [comment]
Fixed in the above commit. This was a copy-paste error that was not caught by the`tandem-name-should-match` lint rule.  I've requested support for catching cases like this in https://github.com/phetsims/chipper/issues/1416.
