### ISSUE TITLE
PhET-iO Design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#26]
This issue is for identifying sim-specific PhET-iO requirements.

@arouinfar will create a PhET-iO Design document.

Sim-specific requirements to identify include:

* Preferences
* Query parameters
* PhET-iO only features
* Customer suggestions
* ...

**Comment by pixelzoom** [comment]
@arouinfar How do you want to proceed with this issue?  The sim is ready for review in https://github.com/phetsims/faradays-electromagnetic-lab/issues/62.

**Comment by arouinfar** [comment]
The design team did not have any specific requests for PhET-iO features. Preferences were separately discussed in #23 #24 and #27. 

The remaining design work for PhET-iO is being tracked in #62, closing.
