### ISSUE TITLE
Select view of the Earth

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#27]
12/4/2023 design meeeting: @arouinfar @ariel-phet @kathy-phet @brent-phet @pixelzoom

Some screens in the Java version had a "Show Earth" checkbox. Checking it results in the Americas-centric view shown in the screenshot below (source http://www.clker.com/clipart-2123.html).  If we only have one Earth image, then we'll always be excluding half of the Earth.  So this seems like a good place to employ the "Region and Culture" feature.   

Things to do:

(1) Verify that the PhET Global team agrees that this feature is needed.

(2) Create artwork. @arouinfar discovered that NOAA has a visualization of Earth without clouds that you can rotate to the desired angle: https://sos.noaa.gov/catalog/datasets/blue-marble-without-clouds/.   This might be useful for generating images with the proper lighting.  And/or check with Mariah about creating more cartoonish images. Since we need to flip the Earth and maintain proper lighting cues, we will need 2 images for every Region. 

(3) Render SVG directly. Images of the Earth will be relatively large.  So the ability to display SVG (instead of PNG) image files seems crucial to this feature, see https://github.com/phetsims/scenery/issues/1578.

<img width="1024" alt="screenshot_2921" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/03b59760-667d-478b-8c1f-e2ee81b364af">

**Comment by pixelzoom** [comment]
@arouinfar and I discussed this today.  We're feeling like this is not a good use of the Region and Culture feature, is a bit "heavy handed" and complicated, and hides the feature.   The purpose of showing the Earth is not to represent specific regions or inspire nationalism -- it's to draw an analogy between the Earth and a bar magnet.  So the image just needs to convey "planet Earth".   As mentioned above, the entire Earth can be represented by 2 images. So another (better?) alternative is to simply have 2 images of the Earth, and choose 1 of them at startup.

We also discussed using a single "blue marble" type picture of the Earth, where clouds obscure the continents.  But the continents are important, to see that the view is equitorial, and the magnet is aligned with the Earth's poles.

**Comment by pixelzoom** [comment]
1/4/24 design meeting with @arouinfar @ariel-phet @kathy-phet @pixelzoom:

* Support 3 Earth images: Asia, Africa/Europe, Americas
* Add a query parameter to select between the 3 images, with ‘random’ as the default.

**Comment by pixelzoom** [comment]
Another thought... We could add 3 radio buttons, one for each image of the Earth, below the "Add Earth checkbox" preference in the Simulation tab below.

<img width="666" alt="screenshot_2971" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/fd872fd4-220f-40fd-a4e7-91dbb6558dc7">

**Comment by pixelzoom** [comment]
This is ready for review by @arouinfar.  I started with 2 images, and it's easy to add more.

* The query parameter is `?earthImage`, values "Americas" and "Africa", default to "Americas".  These are easy to change or extend.
* The PhET-iO Property is `earthImageProperty`, values the same as `?earthImage`, initialized to the value of `?earthImage`.
* The Preferences control is shown in the screenshot below. (For the record, I have no control over the layout, and it's not good.)
* This query parameter and preference will be available for the _FEL_, _Magnet and Compass_, and _Magnets and Electromagnets sims_. It is irrelevant for the Generator sim, and will not be included in Preferences.

If this is satisfactory, then the next step is creating final PNG files, which needs to consider lighting when the bar magnet and Earth are flipped.

FYI, the current PNG files are from http://www.clker.com/clipart-2123.html ("Americas") and http://www.clker.com/clipart-the-globe.html ("Africa").

<img width="769" alt="screenshot_2972" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/b1dfa079-6f5b-46fb-8e5f-f9acbffb5368">

**Comment by arouinfar** [comment]
Thanks @pixelzoom, I really like the approach you've taken, and things are working well on main. I think it makes sense to continue with two images, but frame it as the Eastern/Western hemispheres to simplify the query parameter/Property values.

I took screenshots from the [NOAA visualization](https://sos.noaa.gov/catalog/datasets/blue-marble-without-clouds/) and traced it in Illustrator to create a flat, cartoony version of the Earth. Here are the results:
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/93f05a05-a591-47ff-a92d-1036df306f8c" width=300> <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/5f850e83-99d9-440c-8173-ead9bb58a342" width=300>

Let me know what you think @pixelzoom. I picked colors from the original Americas asset, but decided against adding a gradient. I can easily adjust the colors or add a gradient to create a more spherical-looking effect, though. 

Here are the assets if we want to move forward with these images: 
[earth-assets.zip](https://github.com/phetsims/faradays-electromagnetic-lab/files/13922610/earth-assets.zip)

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  I like this "hemispheres" approach a lot, and made these changes:

* Query parameters is `?earthHemisphere`, value `eastern` and `western`, default `western`.
* Preferences Property is `earthHemisphereProperty`.

I checked in earth.ai.  I used the .svg files. The .png files can be omitted in future updates.

I do not think that we need to add a gradient or light source to the images. But I do think we should play with the colors, to make it "pop" a bit more on the black background.  Let's discuss.

**Comment by pixelzoom** [comment]
@arouinfar and I reviewed and discussed in 1/16/24 standup.  She's going to play with colors.  Opacity of EarthNode is 0.75, and can easily be adjusted.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I've adjusted the colors to make them a bit brighter. Here's what it looks like in context (please ignore magnet orientation). 

| Original | Updated (Opacity = 65%) | 
| --- | --- | 
|  <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/c2a4018e-516e-458a-aab7-c2983ba0dafa" width=300> |  <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/5525cd77-fed8-470e-a694-02bf1e7fdd7a" width=300> |
| <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/45cd0c9f-c332-46d1-a3b1-5c1fb234adbb" width=300> |  <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/38a01fa5-bac6-49a9-a4fb-cd09ad19525a" width=300> |

The challenge is finding colors that work well for both black and white backgrounds. We could take the opacity down to 50% to improve the look of the field indicators. Whatever you think is best @pixelzoom.
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/c27f6e53-4ef2-475c-abce-5e45476a6cfb)

Here are the updated assets: [earth-assets.zip](https://github.com/phetsims/faradays-electromagnetic-lab/files/14411670/earth-assets.zip)

**Comment by pixelzoom** [comment]
Back to @arouinfar for review.  These images look great.  I dialed the opacity back to 6.0 -- between your 6.5 and 5.0.  If you'd like to experiment further, I could add a query parameter.  Or if this is OK, feel free to close.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, the updated images look great! Good call on the opacity, I think 0.6 is a nice balance. Closing.
