### ISSUE TITLE
Screen icon design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#28]
We'll need icons for the 5 screens, ideally (but not necessarily) something that works for both the Home screen and navigation bar.

Since there are 4 sims in this family, it would also be nice if the same screen icons are usable across all sims in which the screens appear. 

Also preferred that the icons can be drawn in code, to make it possible to match color profile.

**Comment by pixelzoom** [comment]
We're getting close to feature complete, when it would be nice to have screen icons.  So assigning to @arouinfar.

Before we put effort into artwork or implementation... It would be preferrable to create icons in code, so that color profiles can be supported. And it might be good to propose icons, and have the sim team approve. Or maybe brainstorm as part of a design meeting.

**Comment by pixelzoom** [comment]
Before we put effort into artwork or implementation...  It would be preferrable to create icons in code, so that color profiles can be supported.  And it might be good to propose icons, and have the sim team approve.  Or maybe brainstorm as part of a design meeting.

**Comment by arouinfar** [comment]
> Before we put effort into artwork or implementation... It would be preferrable to create icons in code

I agree @pixelzoom. It's also fewer assets to create and maintain.

> And it might be good to propose icons, and have the sim team approve.

Sounds good, here's what I'm thinking:

1. Bar Magnet
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/a225ac30-0411-41f5-b740-c912a85c2658" width=250>

2. Pickup Coil
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/25c3f17a-12a6-4236-bc76-3717a7264152" width=250>


3. Electromagnet -- Hide the electrons and the slider
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/3dfb1307-939f-4430-9e76-07cfdf98780a" width=250>

4. Transformer -- Hide the electrons and the slider
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/ee8d11ba-8454-4bd5-b40c-ac43268da023" width=250>

5. Generator -- I think the full generator has too much detail to put into the screen icon. Maybe just a closeup of the generator wheel without the rpm readout? We could consider adding a bit of the faucet like we do in the EFAC Systems screen icon
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/707787c5-a860-448a-93e2-fe3624c03685" width=250> 
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/2277f6f3-eedc-4cd4-9dde-b9422a270c6a" width=250>

@pixelzoom feel free to tweak these ideas or propose any alternatives.

**Comment by pixelzoom** [comment]
A few of these are not going to hold up very well in the navigation bar.   We can certainly have different icons for the navigation bar, but it would be preferrable if we didn't.   So I think we should consider more simplified, caricatured version of these things.  @arouinfar let's discuss.

**Comment by pixelzoom** [comment]
Here's a simplified set of icons, to add to the discussion.  These are implemented in the sim, if you'd like to see them in context. 

<img width="1067" alt="screenshot_2975" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/0683df6a-43b1-4e17-b128-c9945ed74f17">

<img width="1075" alt="screenshot_2976" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/5371d5e0-3633-41a2-9aca-4fbe3d084e67">

**Comment by pixelzoom** [comment]
This probably needs to be discussed in a design meeting with the team.

**Comment by pixelzoom** [comment]
1/25/2024 design meeting: @arouinfar @kathy-phet @ariel-phet @pixelzoom 

Consensus was that the icons for the Bar Magnet and Generator screens are OK.

We did not reach any conclusions about the other screens. @ariel-phet commented that physicists will probably want to see coils in the icons.

**Comment by pixelzoom** [comment]
> ... physicists will probably want to see coils in the icons.

Here's the code for creating a "coil" icon for the Pickup Screen (not committed):

<details>
<summary>function createScreenIcon</summary>

```ts
/**
 * Creates the icon for this screen.
 */
function createScreenIcon(): ScreenIcon {

  // Coil model
  const currentAmplitudeProperty = new NumberProperty( 0 );
  const currentAmplitudeRange = FELConstants.CURRENT_AMPLITUDE_RANGE;
  const coil = new Coil( currentAmplitudeProperty, currentAmplitudeRange, {
    numberOfLoopsRange: new RangeWithValue( 3, 3, 3 ),
    maxLoopArea: 7000,
    loopAreaPercentRange: new RangeWithValue( 100, 100, 100 ),
    tandem: Tandem.OPT_OUT
  } );
  coil.electronsVisibleProperty.value = false;

  // A hack because we have to have a subclass of FELMovable associated with the coil's background layer.
  const movable = new BarMagnet( {
    tandem: Tandem.OPT_OUT
  } );

  // Coil view
  const coilNode = new CoilNode( coil, movable, {
    tandem: Tandem.OPT_OUT
  } );
  
  // Disable interaction
  coilNode.pickable = false;

  // coilNode.backgroundNode needs to be added separately from coilNode.
  const icon = new Node( {
    children: [ coilNode.backgroundNode, coilNode ]
  } );

  return new ScreenIcon( icon, {
    fill: FELColors.screenBackgroundColorProperty,
    maxIconWidthProportion: 1,
    maxIconHeightProportion: 0.85
  } );
}
```

</details>

It looks passable (barely) on the Home screen.  And it looks lousy in the navigation bar.  See below.

<img width="1101" alt="screenshot_3017" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/99ede43d-b5b6-4ea4-b88c-597e6e8cd0ef">


<img width="1098" alt="screenshot_3015" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/6b3bcea0-8f7e-40f0-b045-e1c73d423060">

<img width="1104" alt="screenshot_3016" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/095245fb-800e-45de-924d-15868ad47c11">

**Comment by pixelzoom** [comment]
@arouinfar and I met about this, and did some brainstorming.  Here are some changes that we're going to try...

Pickup Coil screen:

<img width="223" alt="screenshot_3063" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/6da75850-1308-4c7c-8fa8-7e4ba3287e21">


Transformer screen:

<img width="285" alt="screenshot_3062" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/12e72286-03cb-4a28-99cc-ebca3b8c2612">

**Comment by pixelzoom** [comment]
The first screenshot below shows the lastest screen icons in context. For the Pickup Coil and Transformer screens, clipping off the tops of the wire ends on the coils looks decent.

The second screenshot below shows what happens when you leave the home screen, then come back to the home screen.  The `clipArea` for the screen icons is no longer being applied.  I've seen weirdness with clipArea + ScreenIcon before, but nothing like this.  I'll need @jonathanolson's assistance -- see `createScreenIcon` in PickupCoilScreen and TransformerScreen.  On macOS 14.3.1, it does not occur in Safari, but occurs in both Chrome 122 and Firefox 123.

<img width="840" alt="screenshot_3066" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/58ca7dc6-b755-44cf-91a3-cc421decd7e5">

<img width="840" alt="screenshot_3067" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/8ef61fee-3df4-4689-8385-2a095c5923b8">

**Comment by pixelzoom** [comment]
2/29/24 design meeting with @arouinfar @kathy-phet @ariel-phet @Nancy-Salpepi @pixelzoom 

* Icons look good.
* @ariel-phet suggested margins for the Pickup Coil and Transformer icons, and centering the icons. I did a quick demo, everyone liked it, I will make it so.
* clipArea problem still needs to be addressed, but @jonathanolson is on it.

**Comment by pixelzoom** [comment]
Change requests have been completed.  ScreenIcons were consolidated in FELScreenIconFactory.ts, so that I could factor out shared code (see `createBarMagnetNode` and `createCoilNode`). 

I'll leave this issue open until the `clipArea` problem is resolved.  The backup plan is to convert those icons to images using `rasterize()`.

**Comment by pixelzoom** [comment]
I've moved the clipArea bug to https://github.com/phetsims/faradays-electromagnetic-lab/issues/89.

@arouinfar please review the screen icons. If everything looks OK, please close.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good on main! Closing.
