### ISSUE TITLE
Set resistor colors for desired value and tolerance.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#29]
In the Java version, the voltmeter was connected to the pickup coil across a resistor, like this:

<img width="227" alt="screenshot_2955" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/cdf0133a-ff38-4b91-8104-6c2b6f2fa897">

We're not sure where this resistor came from.  There is no such thing as a 3-band resistor (2 value bands + 1 tolerance band).  And if there were such a thing, the value of this resistor (black-black-gold) would be 0 Ω +/-5%.

In the HTML5 version, I implemented a 4-band resistor, which currently looks like this:

<img width="244" alt="screenshot_2956" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/211866f7-9f32-4d03-9fc0-424b679e4423">

The value of this resistor is again 0 Ω +/-5%.  It should be set to some desired value by changing these colors in the Color Editor, where the bands are numbered from left to right:

* resistorBand1Color
* resistorBand2Color
* resistorBand3Color
* resistorBand4Color

For resistor color code, see https://www.utmel.com/tools/band-resistor-color-code-calculator?id=20.

If you need to change the color of the resistor's body, see `resistorFill` in the Color Editor.

**Comment by arouinfar** [comment]
Thanks @pixelzoom!

The resistance value is a fairly arbitrary choice, but I wanted to make sure that we chose something with a reasonable order of magnitude. I referred to an example problem for Lenz's Law (Example 23.1  from the OpenStax College Physics [textbook](https://openstax.org/books/college-physics-2e/pages/23-2-faradays-law-of-induction-lenzs-law)) and did a rough calculation for the magnet in FEL. The induced emf is on the order of 10<sup>-2</sup> V, so I chose a resistance on the order of 10 <sup>-1</sup> ohms to make sure the induced current wouldn't be too crazy. (I'll admit this might have been overkill).

I came up with a resistance of 0.1 ohms, so I updated the band colors accordingly. I sampled the colors we use in CCK, and here's what they look like in the sim:

![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/5f1dd0f8-32c9-4ee5-8a1d-24c0e9d6d9b5)

@pixelzoom please update these colors:
 faradaysElectromagneticLab.resistorFill: (195, 136, 89)
 faradaysElectromagneticLab.resistorBand2Color: (150, 75, 1)
 faradaysElectromagneticLab.resistorBand3Color: (230, 182, 1)
 faradaysElectromagneticLab.resistorBand4Color: (230, 182, 1)

**Comment by pixelzoom** [comment]
Colors were updated in the above commits, see screenshot below.  Back to @arouinfar for a review, close if OK.

<img width="277" alt="screenshot_2974" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/d50d3b25-2e69-4af5-9b09-4667d4fda5f0">

**Comment by arouinfar** [comment]
Looks good on main, thanks @pixelzoom. Closing.
