### ISSUE TITLE
Color profile design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#32]
This sim supports "default" and "projector" color profiles, editable via the Color Editor.

Colors for "default" are identical to the Java version, but can be easily changed if desired.

Colors for "projector" need work, and definitely have some problems.  I'll circle back to set some plausible colors before passing on to @arouinfar.

**Comment by pixelzoom** [comment]
I tweaked a few things in the projector profile, and this feels like it's in a good starting place to hand off to @arouinfar.

A few notes/observations:

* For the default profile, the colors are the same as the Java version, with one exception: the south pole of the bar magnet is blue instead of off-white.  This matches PhET's faradays-law sim, and (in a Google search) seems consist with the typical color of real-world bar magnets.

* Real-world compasses typically have a needle that is white at the south end, or sometimes black.  So it does not match the south pole color typically used for bar magnets.  This seems fine to me, but I wanted to point it out.

* The colors used for the coils (coilFrontColor, coilMiddleColor, coilBackColor) are currently the same for default and projector profiles. And I think it would be a good idea to keep them the same, if possible.  But they currently feel a bit dark in projector profile.  Perhaps they can be lightened up, to provide a compromise that works for both profiles. (I did not attempt this because I wanted the look of the default profile to match the Java version for now.)

**Comment by pixelzoom** [comment]
Noted in today's design meeting...  Coils have 3 associated colors: coilFrontColorProperty, coilMiddleColorProperty, coilBackColorProperty.  The coil currently looks a little dark in projector mode.  And lightening up coilBackColorProperty would probably improve the look of the screen icons.

**Comment by arouinfar** [comment]
@pixelzoom please update these colors. They are the same for both color profiles.

faradaysElectromagneticLab.radioButtonSelectedStroke: (0, 0, 0)
faradaysElectromagneticLab.coilFrontColor: (191, 128, 64)
faradaysElectromagneticLab.coilMiddleColor: (134, 88, 45)
faradaysElectromagneticLab.coilBackColor: (57, 38, 19)
faradaysElectromagneticLab.voltMeterNegativeProbeFill: (110, 110, 110)
faradaysElectromagneticLab.voltmeterProbeStroke: (110, 110, 110)
faradaysElectromagneticLab.acPowerSupplyBodyColor: (200, 200, 200)

**Comment by pixelzoom** [comment]
Nice improvements, especially the coil colors. Back to @arouinfar for review. Close if OK.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom!
