### ISSUE TITLE
Add a DC motor.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#35]
Suggested for the Java version via phethelp on 3/25/2010 in  [Unfuddle#2243](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2243):

> An additional lab in the Electromagnetic Lab simulating a DC motor.

**Comment by pixelzoom** [comment]
1/4/24 design meeting with @arouinfar @ariel-phet @kathy-phet @pixelzoom:

This is not a good fit for this sim.  It should probably be a feature in CCK, where there are similar requests.

**Comment by arouinfar** [comment]
> This is not a good fit for this sim. It should probably be a feature in CCK, where there are similar requests.

See https://github.com/phetsims/circuit-construction-kit-common/issues/510
