### ISSUE TITLE
Support quantitative goals: measure distances & current

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#38]
Requested for the Java version on 4/28/2014 in [Unfuddle#3623](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3623), user's contact info redacted:

> I am wondering, however, if there is any possible way to add a feature to the 'Magnets and Electromagnets' simulation that enables the student to
> 
>   Determine the actual physical distance from the electromagnet when they measure the magnetic field strength, and
>   Measure/calculate the current flowing through the electromagnet when they change the voltage of the battery.

**Comment by pixelzoom** [comment]
> Determine the actual physical distance from the electromagnet when they measure the magnetic field strength

The model uses no meaningful units for position and distance. The model coordinate system is identical to the view coordinate frame.  Adding a meaningful model coordinate frame, then doing the transforms between model and view coordiantes, would be a huge change.

>  Measure/calculate the current flowing through the electromagnet when they change the voltage of the battery.

The model has no meaningful values for current.  Everything is based on "current amplitude", described in Coil.ts like this:

```ts
  // This is a quantity that we made up. It is a percentage that describes the amount of current relative to some
  // maximum current in the model, and direction of that current. View components can use this value to determine
  // how they should behave (eg, how far to move a voltmeter needle, how bright to make a lightbulb, etc.)
  public readonly currentAmplitudeProperty: TReadOnlyProperty<number>;
```

Changing this is really not practical.

So I recommend that we do not attempt to implement these features.

**Comment by arouinfar** [comment]
Thanks for evaluating this request @pixelzoom. 

> So I recommend that we do not attempt to implement these features.

I agree, and the design team has also previously decided against changes or user requests unsupported by the sim's model. 

While this is a nice suggestion, it's not something we can feasibly support. Closing
