### ISSUE TITLE
Make electrons flow through the top segment that connects the 2 ends of the coil.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#42]
From https://github.com/phetsims/faradays-electromagnetic-lab/issues/33#issuecomment-1877848309, and to support #41:

> Make electrons flow through the top segment that connects the 2 ends of the coil. See CoilNode.ts `if ( this.endsConnected )`.

**Comment by pixelzoom** [comment]
First quick look... This is going to be more difficult than anticipated. Electrons move through instances of CoilSegment, each of which has an associated QuadraticBezierSpline.   The top piece of wire is different -- it is a Path, not a QuadraticBezierSpline -- so can not be immediately assigned to a CoilSegment.

**Comment by pixelzoom** [comment]
This attempt in CoilNode gets close (not committed). It converts the "Connect the ends" case to a CoilSegment, whose QuadraticBezierSpline describes a straight line.

```ts
    // Connect the ends
    if ( this.endsConnected ) {
      assert && assert( leftEndPoint && rightEndPoint );

      // To create a straight line, set the control point to be on the midpoint of the line connecting the points.
      const controlPoint = leftEndPoint!.average( rightEndPoint! );
      const curve = new QuadraticBezierSpline( rightEndPoint!, controlPoint, leftEndPoint! );

      const coilSegment = new CoilSegment( curve, this );
      this.coilSegments.push( coilSegment );

      const shape = new Shape()
        .moveToPoint( curve.startPoint )
        .quadraticCurveToPoint( curve.controlPoint, curve.endPoint );
      const path = new Path( shape, combineOptions<PathOptions>( {
        stroke: FELColors.coilMiddleColorProperty
      }, pathOptions ) );
      coilSegment.parentNode.addChild( path );
    }
```

The odd (?) order of args to `new QuadraticBezierSpline` is needed to make the electrons flow in the proper direction.

And as shown in the screenshot below, the electrons are bunched up in the segment identifed as "Right wire end in foreground".

<img width="518" alt="screenshot_2973" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/ba1a3bf0-1f94-4e1e-9ecf-f36494736b60">

**Comment by pixelzoom** [comment]
@arouinfar This is ready for review, close if OK.   You'll need to inspect with the voltmeter selected, and loops >= 3 so that the top section of wire is visible.

<img width="529" alt="screenshot_2994" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/fd79b5f4-fc51-4494-bc00-eabc7273d1e8">

**Comment by pixelzoom** [comment]
@arouinfar hold off on review.  This seems to have introduced some new undesirable behavior in the Electromagnet.  The electrons in each loop used to remain vertically aligned, like this:

<img width="266" alt="screenshot_3000" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/301e2065-5139-4f9b-9f7f-92a9ed9f2f88">

Now they eventually lose that vertical alignment, like this:

<img width="289" alt="screenshot_2999" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/15f6f527-5795-450b-ac9c-89c47af8ff9e">

**Comment by pixelzoom** [comment]
> The electrons in each loop used to remain vertically aligned ... Now they eventually lose that vertical alignment

Hypothesis about this, unconfirmed...  Each loop consists of 4 segments: top front, bottom front, top back, bottom back. Plus there are 2 "end" that connect to the current source.   So prior to adding the top segment, there the coil was very symmetrical, and had an even number of similar segments.  The top segment is very different, there only 1 instance, and it results in an odd number of segments.  So after awhile the symmetry of electron positions is lost. 

Then again, the electromagnet coil does not have a top segment -- or it's not supposed to anyway.  But there could be some computation that changed.

I'm also noticing that the electron motion has gotten less smooth, a little jerky, and almost like there's some GC happening. That might be related to this change, or some other change.

Consider reverting these changes, and addressing the issue some other way. Like making the resistor grow to cover the top segment.

**Comment by pixelzoom** [comment]
In the above commit, I did a selective revert of the changes that I made in https://github.com/phetsims/faradays-electromagnetic-lab/commit/51b67cbdb79dad3efe25048b684bfba7a17293dc.  This removes the electrons from the top segment, while keeping other improvements that were made to the code.  I then confirmed that the electrons once again remain vertically aligned in the loops.

**Comment by pixelzoom** [comment]
In the above commit, I took a different design approach.  The coil no longer has a top wire segment. It is now the responsibility of the measuring device to decide how to connect the ends of the coil. In the case of the light bulb, that was already handled by covering by the light bulb's base.  The voltmeter now has it's own solution - the resistor has wire ends (just like a real resistor) that are connected to the ends of the coil.  The wire ends resize as the coil size changes.  No electrons are shown in the resistor's wire ends, and I don't think that's a problem -- it looks different than the coil, and I think it's sufficient to show electrons in the coil.

@arouinfar please review.  Is this an acceptable solution to the problem?

<img width="248" alt="screenshot_3003" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/971a41f5-7be5-4aac-ba46-6d0f520ee0ec">

**Comment by arouinfar** [comment]
> In the above commit, I took a different design approach. The coil no longer has a top wire segment. It is now the responsibility of the measuring device to decide how to connect the ends of the coil. 

I like this solution @pixelzoom! What's important for students to see is the direction the current flows across the resistor, but they don't need to see electrons in the horizontal wire segment to do this.

Anything else to do here @pixelzoom? Should we have a PSA at design meeting, or is this safe to close?

**Comment by pixelzoom** [comment]
Thanks @arouinfar. I think this is safe to close.
