### ISSUE TITLE
When “Earth” is checked, change button label to “Flip Earth”

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#43]
For https://github.com/phetsims/faradays-electromagnetic-lab/issues/36:

* As a compromise: when “Earth” is checked, change button label to “Flip Earth”.

**Comment by pixelzoom** [comment]
Work here is done, ready for review by @arouinfar. Close if OK.

**Comment by arouinfar** [comment]
Looks good on main, thanks @pixelzoom! Closing.
