### ISSUE TITLE
Incorrect focus rectangle and interactive highlight for electromagnet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#44]
The electromagnetic has 2 choices of current source: battery or AC power supply.   When the battery is selected, the focus rectangle is incorrect:

<img width="857" alt="screenshot_2965" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/965914ac-0a77-465d-9b8e-d2f4493ca20b">

When the AC power supply is selected, the focus rectangle is correct: 

<img width="856" alt="screenshot_2966" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/caab2739-4cf4-4acf-aa4f-4d5cae2b566e">

Perhaps the focus rectangle is being computed based on `boundsProperty` instead of `visibleBoundsProperty`?  @jessegreenberg thoughts?

**Comment by pixelzoom** [comment]
The electromagnet is `ElectromagnetNode`.

**Comment by jessegreenberg** [comment]
Yes, it seems the default highlights should surround the `visibleBounds` instead of just the `bounds`. I made https://github.com/phetsims/scenery/issues/1593 for that change.

**Comment by pixelzoom** [comment]
Interactive highlights have the same problem, so updating the title of this issue.

**Comment by pixelzoom** [comment]
@jessegreenberg It looks like this is working correctly now -- the focus rectangle and interactive hightlight are the correct size. Was it fixed in some other general issue?

**Comment by jessegreenberg** [comment]
Yes, this was fixed in https://github.com/phetsims/scenery/issues/1593 so I would expect it to be fixed for this issue now.

**Comment by pixelzoom** [comment]
Great, thanks. Closing.
