### ISSUE TITLE
When slider thumb has focus, arrow keys change slider AND move electromagnet.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#45]
To reproduce:

1. Start the sim, go to the Electromagnet screen.
2. Press Tab to move the focus highlight to the electromagnet (first screenshot below). Verify that you can move the electromagnet with the arrow keys.
3. Press Tab again to move the focus highlight to the battery's slider thumb (second screenshot below.)  The behavior of the arrow keys is now unexpected -- they tchange the slider thumb _AND_ move the electromagnet.

The same problem occurs with the sliders on the AC power supply (the other choice for Current Source radio buttons).

@jessegreenberg Can you advise me on how to proceed?

<img width="857" alt="screenshot_2965" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/0c1af9f3-f144-45a3-ad5d-12f97b6ed9df">

<img width="857" alt="screenshot_2968" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/5af6097d-5cfb-419a-b86c-9f91ba8a70b0">

**Comment by pixelzoom** [comment]
The electromagnet is `ElectromagnetNode`.  It has child `BatteryNode`, which has an `HSlider`.

**Comment by jessegreenberg** [comment]
Thanks for reporting, it is a bug. Either the listener added in the AccessibleValueHandler needs to attach itself to the pointer to prevent the KeyboardDragListener from starting, or it needs to stop event propagation. I think the former, but I will take a look.

**Comment by pixelzoom** [comment]
Looks like @jessegreenberg fixed this in https://github.com/phetsims/scenery/issues/1596, which is now closed. It's working as expected in this sim.  So closing.
