### ISSUE TITLE
Delete faraday GitHub repo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#5]
https://github.com/phetsims/faraday contains experimental work from way back in 2013, when PhET was first starting to investigate using HTML5 and JavaScript.  Surprisingly, it still runs — probably because it has no dependencies on other repos. It was kept around on the odd chance that it might be useful, but it ultimately contributed nothing to the faradays-electromagnetic-lab port.  It should be deleted.

This is not to be confused with the Java version in Unfuddle at trunk/simulations-java/simulations/faraday/.  That legacy code should be left untouched.

**Comment by zepumph** [comment]
Are there any dev versions published? I don't have any issues with you deleting it.

**Comment by pixelzoom** [comment]
I apparently do not have permission to delete this repo:

<img width="673" alt="screenshot_3189" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/1685cfd7-fb48-4b1f-bbd1-6f7112fed164">

**Comment by zepumph** [comment]
I believe I have permission, but I'm out the rest of the morning.

**Comment by zepumph** [comment]
I have the permission to delete it, but I got in my head and I'm a bit nervous. I just archived `phetsims/faraday`. https://github.com/phetsims/faraday/settings. Please let me know that this is the right repo, and I can go ahead and delete it.

**Comment by pixelzoom** [comment]
Yes, https://github.com/phetsims/faraday is the subject of this issue. Please delete it.

**Comment by zepumph** [comment]
Deleted.
