### ISSUE TITLE
Review and port faraday/doc/ from Unfuddle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#6]
The Java version has lots of useful documents in Unfuddle SVN at:
https://phet.unfuddle.com/a#/projects/9404/repositories/23262/browse?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Ffaraday%2Fdoc

In addition to porting code, some of this doc should be ported to GitHub in faradays-electromagnetic-lab/doc/.

FYI @arouinfar - you may want to take a look at some of this legacy doc, especially:
  
* Requirements.txt - summary of sim requirements as of 12/21/2004 (PhET didn't have design docs back then)
* Physics_Implementation.rtf - similar to model.md for HTML5 sims
* 4 "Tips for Teachers" files (PDF and docx format)

**Comment by pixelzoom** [comment]
Below is the list of documents in Unfuddle at [trunk/simulations-java/simulations/faraday/doc](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/browse?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Ffaraday%2Fdoc).  I copied all of these docs _except the ones with "Tips" prefix_ to GitHub at  [faradays-electromagnetic-lab/doc/java-version/](https://github.com/phetsims/faradays-electromagnetic-lab/tree/main/doc/java-version).

@arouinfar Let me know if you'd like any of the "Tips" documents copied over.  I suspect not, since Teacher Tips probably need to be updated/modernized.   If there's nothing else that you'd like copied over, please close this issue.

<img width="401" alt="screenshot_2993" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/d98301d6-05b6-47e1-af52-3f4010c9bbae">

**Comment by arouinfar** [comment]
Thanks @pixelzoom. No need to move over the legacy Teacher Tips docs. 

The pdf versions are all published on the website, which I will consult when creating the new Tips. Modern Teacher Tips have a very different format, so I don't see any benefit in retaining the editable doc versions.
