### ISSUE TITLE
Review PhET-iO instrumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#62]
Base level instrumentation is done, and the sim is ready to review,  including:

- [x] Studio tree organization
- [x] tandem names
- [x] phetioReadOnly
- [x] phetioFeatured (see #83) 
- [x] phetioDocumentation
- [x] phetioHighFrequency (see #60)
- [x] linked elements
- [x] units & ranges

Let me know what you'd like to change.  You can either create new GitHub issues, or comment in this issue.

**Comment by pixelzoom** [comment]
1/25/2024 design meeting: @arouinfar @kathy-phet @pixelzoom 

We discussed these 4 Properties in particular, because they are central to Faraday's Law:

* pickupCoil.coil.loopAreaProperty
* pickupCoil.coil.fluxProperty
* pickupCoil.coil.deltaFluxProperty
* pickupCoil.coil.emfProperty

Their values are not really meaningful outside of the sim internals, because we have a "Hollywood" model.  In https://github.com/phetsims/faradays-electromagnetic-lab/commit/3ddba982e8e47f157312cc3258af56de1edf48a9 above, we removed units and adjusted phetioDocumentation as a start. But these Properties require further review.  And we may want to discuss them in examples.md.

**Comment by pixelzoom** [comment]
@arouinfar and I discussed, here's the initial list of change requests:

- [x] Instrument:

~~electromagnetNode.dragListener.enabledProperty~~
~~electromagnetNode.keyboardDragListener.enabledProperty~~
electromagnetNode.dragEnabledProperty

- [x] fieldMeter.fieldVectorProperty is easy enough to get Bx and By components.  But getting magnitude and angle requires doing some vector math.   So for the convenience of PhET-iO, add:

fieldMeter.magnitudeProperty // in G only, DerivedProperty
fieldMeter.angleProperty // in G only, DerivedProperty

- [x] Add units: ‘G’ to electromagnet.strengthProperty

- [x] Instrument the voltage readout on the battery: 

voltsText.visibleProperty

- [x] Uninstrument

acPowerSupplyNode.frequencyControl.slider
acPowerSupplyNode.maxVoltageControl.slider

- [x] Rename 

seeIndexCheckbox > seeInsideCheckbox

- [x] Uninstrument `acPowerSupplyNode.chartNode` (no children and doesn't appear to be stateful)

**Comment by pixelzoom** [comment]
All of the change requests in https://github.com/phetsims/faradays-electromagnetic-lab/issues/62#issuecomment-1952874051 are completed.  Back to @arouinfar for review, close if OK.

Note that instead of instrumenting `electromagnetNode.dragListener.enabledProperty` and 
`electromagnetNode.keyboardDragListener.enabledProperty`, a new Property `electromagnetNode.dragEnabledProperty` was added.  This was the cleanest way to support independent control being able to disable dragging while still being able to use sliders, while also addressing draggability of the background layer of the coil.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! These changes all look good in main, closing.
