### ISSUE TITLE
Adjust initial positions of all objects

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#64]
From https://github.com/phetsims/faradays-electromagnetic-lab/issues/25#issuecomment-1911166998:

> .... We may want to move the positions of the magnet and pickup coil up a bit, to feel more centered in the screen. We'll probably defer that until we calibrate the light bulb to display longer rays.

On hold until calibration is addressed in https://github.com/phetsims/faradays-electromagnetic-lab/issues/66.

**Comment by pixelzoom** [comment]
This work can proceed.   

If you run with `?log`, the position of draggable objects will be printed to the browser console. 

To see the max length of the light rays:

1. Go to the Pickup Coil screen.
2. Set loops = 4, loop area = 100%.
3. Put the magent in the center of the pickup coil.
4. Press the "Flip polarity" button.

**Comment by pixelzoom** [comment]
@arouinfar FYI...  In the above commit, I put the compass and field meter in the same initial position for all screens.  This seemed like a decent starting point, and suitable for dev-lite testing.

**Comment by pixelzoom** [comment]
@arouinfar Here's a table that you can use to specify the positions.  I've filled it in with the current positions.  Each column is a screen.   Let me know if for some reason you want to adjust positions of the generator; it's components (magnet, coil, faucet) are in a fixed position.

| component | Bar Magnet | Pickup Coil | Electromagnet | Transformer | Generator |
| :---: | :---: | :---: | :---: | :---: | :---: |
| Compass  | ( 625, 400 ) | ( 625, 400 ) | ( 625, 400 ) | ( 625, 400 ) | ( 625, 400 ) |
| Field Meter | ( 125, 400 ) | ( 125, 400 ) | ( 125, 400 ) | ( 125, 400 ) | ( 125, 400 ) |
| Bar Magnet | ( 450, 300 ) | ( 200, 400 ) | NA | NA |  NA |
| Electromagnet | NA | NA | ( 400, 400 ) | ( 200, 400 ) | NA |
| Pickup Coil | NA | ( 500, 400 ) | NA | ( 500, 400 ) | NA |

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Overall, these defaults seem appropriate. I like the consistency of keeping the same defaults for the compass and field meter. 

The field meter is a bit tricky to place. I considered moving it closer to the control panels to have better proximity to the checkbox, but that looks too crowded. The field meter is quite large, so I'm not worried about people not noticing it when the checkbox is checked, so I decided to leave it as-is.

The only element I'd like to move is the Bar Magnet on the first screen. Let's shift it to (430, 285) to better align it with the magnetic field indicators.

**Comment by pixelzoom** [comment]
Bar Magnet on the first screen is now at (430, 285).  Back to @arouinfar for review, close if OK.

**Comment by arouinfar** [comment]
Looks good, closing!

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
