### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#66]
This issue concerns the calibration sim model, including the pickup coil, speed of electrons, light bulb, and voltmeter.

PickupCoil has this method, ported from the Java version, and enabled via `?calibrateEMF`:

```ts
  /**
   * Provides assistance for calibrating this coil. The easiest way to calibrate is to run the sim with the
   * &log query parameter, then follow these steps for each screen that has a PickupCoil model element.
   *
   * 1. Set the "Max EMF" developer control to its smallest value.
   * 2. Set the model parameters to their maximums, so that maximum EMF will be generated.
   * 3. Do whatever is required to generate EMF (move magnet through coil, run generator, etc.)
   * 4. Watch the console for a message that tells you what value to use.
   * 5. Change the value of maxEMF that is used to instantiate the PickupCoil.
   */
  private calibrateMaxEMF(): void {
```

A few issues related to calibration:

- [ ] ~~LightBulb and Voltmeter likely need to be calibrated separately, and this does not support that.~~
- [x] LightBulb and Voltmeter do not observe `emfProperty`, they observe `currentAmplitudeProperty` (as they should).
- [x] Running with `?calibrateMaxEMF`, I rarely see `currentAmplitudeProperty` approaching the maximums of its range [-1,1].
- [x] Instead of setting `currentAmplitudeProperty` in PickupCoil updateEMF (the only place it's set), we might want to make it `new DerivedProperty( [ emfProperty ], ... )`.

**Comment by pixelzoom** [comment]
Design meeting 2/29/24 with @arouinfar @kathy-phet @ariel-phet @Nancy-Salpepi @pixelzoom

Consensus was that the separate calibration of light bulb, etc. would be nice to have, so I should investigate.

**Comment by pixelzoom** [comment]
Existing calibration parameters to consider adjusting:

* currentSpeedScale
* transitionSmoothingScale
* maxEMF

**Comment by pixelzoom** [comment]
@arouinfar and I discovered that it's useful for the light bulb to have a different `maxRayLength` for each screen.  For the Generator screen, `maxRayLength: 500` feels really great.  Not sure about the other screens...

**Comment by pixelzoom** [comment]
Related to #156 ...  Notes from 5/1/24 meeting with @arouinfar and @ariel-phet.

@ariel-phet said that he had a hard time convincing himself that #156 was correct by just playing with the sim.  He had a promising idea for a better method of calibrating, which I'll try to summarize here:

* Create a field where all vectors point to the right and have the same strength, with a control to change the strength.  Move the pickup coil through this field to verify that flux is behaving as expected.

* Create a field where all vectors point the right, but the stength increase from [0,max] -- a left-to-right gradient.  Move the pickup coil through this field to verify that flux is behaving as expected.

* Query parameters for selecting one of these 2 calibration fields.

I'll need to give some thought to the best way to do this.  But it sounds better than the current adhoc calibration methods that we came up with in 2005.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/faradays-electromagnetic-lab/commit/9c1861fe137e90a7b533df01d76197033f28e613, I added a query parameter for setting up the constant Bx or gradient Bx field that @ariel-phet suggested in https://github.com/phetsims/faradays-electromagnetic-lab/issues/66#issuecomment-2089265340.  

The query parameter is `gradientField`, documented as:

```ts
  // Ignores the magnet model and sets up a static gradient B-field, where all field vectors are (Bx,0), and Bx varies
  // linearly over a range. The value for this query parameter is the range of Bx from positions x=100 to x=650.
  // These positions will be noted by yellow vertical lines. By is always 0.
  //
  // This is useful for calibrating the sim, and verifying behavior of the pickup coil. This query parameter affects
  // all screens, even though it is only useful in the Pickup Coil and Transformer screens.
  //
  // Examples:
  // gradientField=300,300 creates a constant B-field with (Bx,By) = (300,0) everywhere.
  // gradientField=0,300 create a gradient B-field, where Bx changes linearly from 0 to 300, and By is 0 everywhere.
  //
```

Below is a screenshot showing `gradientField=0,300`.   The vertical yellow lines show the x-range over which the gradient occurs. 

I'll need to meet with @ariel-phet to talk more about how he envisions using this.

<img width="1045" alt="screenshot_3291" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/6c3d41c6-7f27-496a-a6cc-a3726d3e876d">

**Comment by pixelzoom** [comment]
On hold until  #156 and related issues are closed.

**Comment by pixelzoom** [comment]
The fudge factor added in https://github.com/phetsims/faradays-electromagnetic-lab/issues/166#issuecomment-2125799912 changes the flux of the pickup coil for screens that have an electromagnet.  They require recalibration of maxEMF.

**Comment by pixelzoom** [comment]
As of 11:00AM this morning... Issues with the new flux model have been resolved, so work on calibration can resume.

**Comment by pixelzoom** [comment]
Calibration went relatively quickly.  Transformer screen needed some tweaks in the above commits, but otherwise things look pretty good.

@arouinfar please review.  ... and definitely take your time on this review. It's something we can tweak after a dev test, and does not block dev testing.

**Comment by pixelzoom** [comment]
... and definitely take your time on this review.  It's something we can tweak after a dev test, and does not block dev testing.

**Comment by pixelzoom** [comment]
@arouinfar To facilitate fiddling with calibration, I've made 2 improvements to the developer features that are available when running with `?dev`.

First, in the 'Developer' accordion box, the arrow buttons for the 'Max EMF' control (shown below) now increment/decrement by 100 -- instead of 1, which was not very useful for the range [100000, 6000000].

<img width="236" alt="screenshot_3384" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/531e5853-9540-4011-ae76-8db9fa418733">


Second, I've added a 'Max EMF' display to the 'Pickup Coil Debugger' panel, shown below.  This is a nicer alternative to the `calibrateMaxEMF` query parameter.  As you play with the sim, this value will update, and you can use it to inform how you set the 'Max EMF' control in the 'Developer' accordion box.

<img width="214" alt="screenshot_3382" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/6865f442-00fe-4005-8a65-4687b20890b7">

**Comment by pixelzoom** [comment]
With the improvements noted in https://github.com/phetsims/faradays-electromagnetic-lab/issues/66#issuecomment-2181203760, the `calibrateMaxEMF` query parameter is no longer needed, so I've deleted it.  

Here is the latest documentation that describes how to calibrate `maxEMFProperty` and `transitionSmoothingScaleProperty`.

```ts
  // DEBUG: Writeable via developer controls only, when running with &dev query parameter. Dividing the coil's EMF by
  // this number will give us the coil's normalized current (see Coil.normalizedCurrentProperty), which determines the
  // responsiveness of view components.
  //
  // To set this value, follow these steps:
  // * Run with &dev query parameter to see the 'Developer' accordion boxes. For screens that have a pickup coil:
  // * Check the 'Debugger Panel' checkbox to see the 'Pickup Coil Debugger' panel, which displays 'Max EMF'.
  // * Set the sim to settings that will generate the most EMF. Note the value of 'Max EMF' in the 'Pickup Coil Debugger' panel.
  // * Set the 'Max EMF' control in the 'Developer' accordion box based on the value that you observe in the 'Pick Coil Debugger' panel.
  //   Depending on the screen, you may decide to use a smaller value for 'typical' use versus 'extreme' use.
  public readonly maxEMFProperty: NumberProperty;

  // DEBUG: Writeable via developer controls only, when running with &dev query parameter.
  // This is a scaling factor used to smooth out abrupt changes that occur when the magnet transitions between being
  // inside & outside the coil. This is used to scale the B-field for sample points inside the magnet, eliminating
  // abrupt transitions at the left and right edges of the magnet. For any sample point inside the magnet, the B-field
  // sample is multiplied by this value.
  //
  // To set this value, follow these steps:
  // * Run with &dev query parameter to see the 'Developer' accordion boxes. For screens that have a pickup coil:
  // * Check the 'Debugger Panel' checkbox to see the 'Pickup Coil Debugger' panel.
  // * Move the magnet horizontally through the coil until, by moving it one pixel, you see an abrupt change in the
  //   displayed flux value.
  // * Note the 2 flux values when the abrupt change occurs.
  // * Move the magnet so that the largest of the 2 flux values is displayed.
  // * Adjust the 'Transition Smoothing Scale' control until the larger value is reduced to approximately
  //   the same value as the smaller value.
  public readonly transitionSmoothingScaleProperty: NumberProperty;
```

**Comment by arouinfar** [comment]
@pixelzoom thanks for setting up the dev controls, it made calibration much smoother. The one sticking point was that the Max EMF readout in the debugger panel doesn't reset with ResetAll, I had to refresh the browser window.
 
 Let's use these values:
- [x] Pickup Coil Screen: Max EMF = 1,300,000
- [x] Transformer Screen: Max EMF = 3,500,000
- [x] Generator Screen: Max EMF = 120,000

The only significant change is the Transformer screen, which was at Max EMF = 5,000,000. A stationary AC source inside of the coils has a max EMF of ~1,600,000 (max amplitude, max frequency, max loops, min loop area) and I found the voltmeter particularly hard to read. Under the same conditions, the DC source has a Max EMF of ~3,100,000 with alt input, but can get much higher when dragged rapidly. Decreasing the Max EMF to 3,500,000 seemed like a good compromise to improve the static AC source case without sacrificing too much from the DC case.

**Comment by pixelzoom** [comment]
Back to @arouinfar for review and some questions.

I've made the max EMF changes requested in https://github.com/phetsims/faradays-electromagnetic-lab/issues/66#issuecomment-2207402239.

Any changes for transitionSmoothingScaleProperty?

Regarding:
> The one sticking point was that the Max EMF readout in the debugger panel doesn't reset with ResetAll, I had to refresh the browser window.

Developer controls are currently NOT reset on ResetAll, and I'd like to keep that consistent.  So rather than resetting the max EMF display on ResetAll, I'm now resetting it whenever the "Max EMF" control is changed in the Developer accordion box. Does this address the inconvenience?

**Comment by pixelzoom** [comment]
Re https://github.com/phetsims/faradays-electromagnetic-lab/issues/66#issuecomment-2211129851, @arouinfar and I reviewed 2 of my questions during today's standup meeting:

> Any changes for transitionSmoothingScaleProperty?

No. Current values looked good.

> ... So rather than resetting the max EMF display on ResetAll, I'm now resetting it whenever the "Max EMF" control is changed in the Developer accordion box. Does this address the inconvenience?

Yes.

So all that remains is to review the changes requested for max EMF values.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! Looks good on main, closing.
