### ISSUE TITLE
Compass spins wildly near bar magnet poles.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#67]
Surprising that this was not reported in Unfuddle for the Java version, because it's a problem with the Java version.

If the center of the compass is moved very close to the 'N' or 'S' pole of the bar magnet (as shown in the screenshot below), the compass starts to spin wildly. 

<img width="344" alt="screenshot_3006" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/3279213c-ce0e-47c2-b8b8-95601219eca7">

**Comment by pixelzoom** [comment]
Fixed in the above commits.  The problem was that the Verlet algorithm for compass kinematics was working nicely for field strengths in the range (0,10] G.  But above 10G, the algorithm was blowing up, causing the compass needle to spin wildly.  So I introduced a threshold, MAX_FIELD_MAGNITUDE = 10G, above which the compass immediately aligns with the magnetic field.  In reality, a compass would align with a strong magnetic field more quickly, with less wobble, so this seemed like an acceptable compromise.

@arouinfar please test-drive, let me know what you think.  If it's OK, please close.

**Comment by pixelzoom** [comment]
I should also note that I fixed another bug in https://github.com/phetsims/faradays-electromagnetic-lab/commit/700ce8291d389b85aaa3320f44653b1806a92899, which was present in the Java version.  In many cases, the compass was never coming to rest, and wobbling around a very tiny delta that was impossible to see. This was because the delta angle was not normalized to [0,2*PI].  Here's the fix:

```ts
-  const deltaAngle = ( angle - this._angleProperty.value );
+  const deltaAngle = ( angle - this._angleProperty.value ) % ( 2 * Math.PI ); 
```

**Comment by arouinfar** [comment]
> So I introduced a threshold, MAX_FIELD_MAGNITUDE = 10G, above which the compass immediately aligns with the magnetic field.  In reality, a compass would align with a strong magnetic field more quickly, with less wobble, so this seemed like an acceptable compromise.

I agree, this is completely reasonable behavior, and fairly realistic. I reviewed on main and the behavior looks great! Closing.
