### ISSUE TITLE
Does stepEmitter need to be instrumented?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#69]
In FELModel:

```
    this.stepEmitter = new ConstantStepEmitter( options.tandem.createTandem( 'stepEmitter' ) );
```

ConstantStepEmitter is a subclass of Emitter that fires at 25fps with dt = 1.  It's a basically an implementation of a "constant dt clock", something we had in Java (see SwingClock.java) and which FEL model requires.  See the doc at the top of [ConstantStepEmitter.ts](https://github.com/phetsims/faradays-electromagnetic-lab/blob/main/js/common/model/ConstantStepEmitter.ts) for more details.

ConstantStepEmitter has `accumulatedTimeProperty: Property<number>`, which does need to be instrumented.  

Questions:

(1) Does `stepEmitter` itself need to be instrumented?  Is it important for PhET-iO clients to know when the model is stepped?

(2) If it does need to be instrumented, should it be `phetioHighFrequency:true`?

**Comment by pixelzoom** [comment]
@arouinfar @zepumph @samreid I'd love your input on the 2 questions in https://github.com/phetsims/faradays-electromagnetic-lab/issues/69#issue-2106671451.

**Comment by samreid** [comment]
Clients do not need to listen for that emitter, it is an internal implementation detail. I recommend not instrumenting.

**Comment by zepumph** [comment]
I agree with @samreid. 

I also thought the phetioHighFrequency was deprecated generally, and shouldn't be added to more elements even if they are spammy (punting until we design the data stream).

**Comment by pixelzoom** [comment]
Thanks @samreid and @zepumph.  Unless @arouinfar disagrees, I'll uninstrument `stepEmitter`.  I will need to instrument `stepEmitter.accumulatedTimeProperty`, which accumulates dt values.  If I don't, the Upstream and Downstream sims will be very out of sync.

Re:
> I also thought the phetioHighFrequency was deprecated generally, and shouldn't be added to more elements even if they are spammy (punting until we design the data stream).

I'm been adding `phetioHighFrequency: true` only in cases where a Property (like `stepEmitter.accumulatedTimeProperty`) makes it impossible to even look at the data stream -- which I do very occassionally, as a development tool.

**Comment by pixelzoom** [comment]
I'm confident enough that stepEmitter should be uninstrumented that I went ahead and did so.  If that's OK with you @arouinfar, then please close this issue.  If not, it's easy to restore uninstrumentation.

**Comment by pixelzoom** [comment]
FYI, in the above commit, I renamed ConstantStepEmitter to ConstantDtClock, and renamed `model.stepEmitter.accumulatedTimeProperty` to `model.clock.accumulatedTimeProperty`.

**Comment by arouinfar** [comment]
Thanks, everyone! Uninstrumenting `stepEmitter` sounds reasonable to me, closing.
