### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#70]
https://github.com/phetsims/faradays-electromagnetic-lab/blob/main/doc/model.md

**Comment by pixelzoom** [comment]
@arouinfar model.md is ready for review.  Feel free to make changes/corrections directly.

**Comment by pixelzoom** [comment]
You can also have a look at model.md for the derived sims. They all point to https://github.com/phetsims/faradays-electromagnetic-lab/blob/main/doc/model.md.

* https://github.com/phetsims/magnet-and-compass/blob/main/doc/model.md
* https://github.com/phetsims/magnets-and-electromagnets/blob/main/doc/model.md
* https://github.com/phetsims/generator/blob/main/doc/model.md

**Comment by arouinfar** [comment]
Looks good @pixelzoom! I made a few small edits in the commit above.

**Comment by pixelzoom** [comment]
Assigned to @samreid and @matthew-blackman as part of code review #103.

**Comment by pixelzoom** [comment]
Issues #117, #118, and #119 all deal with how this sim does (and does not) deal with resistance and current.  To address those issue, @matthew-blackman will take a stab at improving related documentation in model.md.  @arouinfar and I will review.

**Comment by matthew-blackman** [comment]
I added a note about the wire length in the 'Electromagnet' section. Over to you for review @arouinfar and @pixelzoom.

**Comment by pixelzoom** [comment]
Thanks @matthew-blackman, looks good to me.

**Comment by arouinfar** [comment]
Looks good to me too, closing.
