### ISSUE TITLE
implementation-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#71]
https://github.com/phetsims/faradays-electromagnetic-lab/blob/main/doc/implementation-notes.md

**Comment by pixelzoom** [comment]
This is ready for code review, so assigning to @samreid and @matthew-blackman.  Let me know what else would be helpful here.

**Comment by matthew-blackman** [comment]
The examples provided in examples.md contain a nice overview of the customization options available via PhET-IO, as well as all sim preferences. Nice work! I went through the sim/doc and didn't find any notable omissions. Closing.
