### ISSUE TITLE
Improve the kinematics for the voltmeter.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#73]
Noticed while working on https://github.com/phetsims/faradays-electromagnetic-lab/issues/9 ...

Looking at Voltmeter.ts, and comparing the behavior to faradays-law, I suspect that there's a problem with `step`.  With this bit of code, I don't see how the damping could possibly be working:

```ts
    if ( needleAngle !== ZERO_NEEDLE_ANGLE ) {
      this._needleAngleProperty.value = needleAngle;
    }
```

The algorithm used for `step` in Voltmeter.ts was ported directly from Voltmeter.java.  And the Java version behaves the same as the current HTML5, so this was not a problem introduced during porting. 

The damping for the voltmeter in faradays-law looks like it's in the `step` method of Voltmeter.js.

**Comment by pixelzoom** [comment]
We should probably turn damping off when using the AC power supply.

**Comment by pixelzoom** [comment]
Design meeting 2/29/24 with @arouinfar @kathy-phet @ariel-phet @Nancy-Salpepi @pixelzoom 

Consensus was that the voltmeter behavior in "Faraday's Law" is much nicer, and that I should give this a go.  @ariel-phet is available for consultation.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/faradays-electromagnetic-lab/commit/f69af233e8aca653b6600e1fde2cec6dcbb541b6, I disabled kinematics when the AC power supply is being used.  In that case, the needle always moves immediately to the correct angle.

Discussed kinematics with @arouinfar.  If I can get this to behave like faradays-law, we can ditch the "jiggle" around the zero point.

I made some progress on this, but the needle gets stuck, and does not return to zero.  Here's the revised `step` method:

```ts
public step( dt: number ): void {
  assert && assert( dt === ConstantDtClock.DT, `invalid dt=${dt}` );

  // Determine the desired needle deflection angle.
  const desiredNeedleAngle = this.getDesiredNeedleAngle();

  const deltaAngle = ( desiredNeedleAngle - this._needleAngleProperty.value ) % ( 2 * Math.PI );
  if ( deltaAngle === 0 ) {
    // Do nothing, the needle is resting at zero volts.
  }
  else if ( Math.abs( deltaAngle ) < NEEDLE_JIGGLE_THRESHOLD ) {

    // The needle is close enough to zero, so move immediately to zero.
    this._needleAngleProperty.value = ZERO_NEEDLE_ANGLE;
  }
  else {
    // Use the Verlet algorithm to simulation rotational kinematics.

    const SENSITIVITY = 0.01; // Increase this to make the needle more sensitive to smaller values.
    const DAMPING = 0.08; // Increase this to make the needle wobble less.
    const amplitude = this.currentAmplitudeProperty.value;

    // Step 1: rotation
    const angularAccelerationTemp = ( SENSITIVITY * Math.sin( deltaAngle ) * amplitude ) - ( DAMPING * this.angularVelocityProperty.value );
    this._needleAngleProperty.value = this._needleAngleProperty.value + ( this.angularVelocityProperty.value * dt ) + ( 0.5 * angularAccelerationTemp * dt * dt );

    // Step 2: angular acceleration
    const angularVelocityTemp = this.angularVelocityProperty.value + ( angularAccelerationTemp * dt );
    this.angularAccelerationProperty.value = ( SENSITIVITY * Math.sin( deltaAngle ) * amplitude ) - ( DAMPING * angularVelocityTemp );

    // Step 3: angular velocity
    this.angularVelocityProperty.value = this.angularVelocityProperty.value + ( 0.5 * ( this.angularAccelerationProperty.value + angularAccelerationTemp ) * dt );
  }
}
```

**Comment by pixelzoom** [comment]
I gave up on the Verlet algorithm because it's problematic here --  we'll miss peak voltages, which may only exist for 1 time step.  The solution in the above commit simulates kinematics, with deceleration, when the needle is returning to zero. It has a damping constant that can be used to adjust how quickly the needle returns to zero.   

This is a noticeable improvement, but I'm going to ponder on how to refine it before asking for a review. @arouinfar feel free to have a look if you're curious.

**Comment by pixelzoom** [comment]
FYI... In https://github.com/phetsims/faradays-electromagnetic-lab/commit/f69af233e8aca653b6600e1fde2cec6dcbb541b6 and https://github.com/phetsims/faradays-electromagnetic-lab/commit/1aa77c51c12f66ecf339c167b5eba44133b41ab9, I disabled voltmeter kinematics in the Transformer screen (when AC power supply is selected) and Generator screen (always disabled) respectively.   When the flux change is periodic, we want the voltmeter to respond immediately, or it will always lag behind.  This is the same reason that we do not use the kinematic compass in these screens.

**Comment by pixelzoom** [comment]
I'm pretty happy with this improved behavior.  It's not the same as the Faraday's Law sim, but I don't think it should be.

@arouinfar please review, let's discuss if you have ideas/concerns/whatever.

To summarize
* Voltmeter kinematics is turned off for the AC power supply and Generator.  In these cases, the voltage is varying cyclically, and we need the voltmeter to respond immediately (similar to the compass for these cases).
* When kinematics is enabled, the needle moves immediately to non-zero values. When returning to zero, it does so incrementally and decelerates.

**Comment by arouinfar** [comment]
@pixelzoom the updated voltmeter behavior is so nice! It feels so much smoother now, really nicely done. Not sure if any further cleanup/documentation is needed, so back to you.

**Comment by pixelzoom** [comment]
Glad you like it.  Nothing else to be done here, so closing.
