### ISSUE TITLE
Integrate keyboard help for FaucetNode.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#74]
... when https://github.com/phetsims/scenery-phet/issues/839 is completed.

**Comment by pixelzoom** [comment]
@arouinfar ready for you to review.  Let me know what you'd like to change, or feel free to close.

Screenshots below show keyboard help for the Generator screen, followed by the first 4 screens (which all have the same help).  I tried to follow the guideline of ordering from most to least sim-specific, from left to right. 


<img width="715" alt="screenshot_3023" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/564a7fc5-ba5c-4510-b5cc-417ea60f19fd">

<img width="806" alt="screenshot_3022" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/37873a9b-6041-4000-a37b-0efa39cb404e">

**Comment by arouinfar** [comment]
Looks great! Thanks @pixelzoom, closing.
