### ISSUE TITLE
Determine `dragSpeed` and `shiftDragSpeed` for draggable objects

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-electromagnetic-lab#79]
@pixelzoom wrote in https://github.com/phetsims/faradays-electromagnetic-lab/issues/54#issuecomment-1912733540
>For tuning drag speeds, I added query parameter dragVelocity (default 500) and shiftVelocity (default 250). Since they affect all draggable objects, they should be used to tune one object at a time.

The query parameters have since been updated to `dragSpeed` and `shiftDragSpeed`. KeyboardDragListener currently supports two drag speeds, but a third speed has been proposed in https://github.com/phetsims/scenery/issues/1601. 

For now, I will focus on just the two supported speeds, and we can reassess if/when the third speed is added to KeyboardDragListener. I will also consider using different speeds for the measurement tools (compass and field meter) and the experimental equipment (magnets, coils).

**Comment by pixelzoom** [comment]
@arouinfar here's a table that you can fill in:

| Component | dragSpeed | shiftDragSpeed |
| -----------  | ----------- | --------------- |
| Bar Magnet | 600 | 150 |
| Electromagnet | 600 | 150 |
| Pickup Coil | 600 | 150 |
| Compass | 150 | 50 |
| Field Meter | 150 | 50 |

**Comment by arouinfar** [comment]
Thanks for the table @pixelzoom, I've filled it out.

I chose slower speeds overall for the Compass and  Field Meter. The rationale is that I want the `dragSpeed` to be slow enough to still be readable but not inconveniently slow. Additionally, the smaller the `shiftDragSpeed`, the more precisely the tools can be placed, which seems important.

We may need to refine these values as sound is integrated, but I tested these speeds with #77 and it sounded reasonable to me.

**Comment by pixelzoom** [comment]
Thanks @arouinfar. These values feel good to me, implemented in https://github.com/phetsims/faradays-electromagnetic-lab/commit/e855aa508189fc987bc05c0634def6c84e6a790c.  It was also necessary to delete `?dragSpeed` and `?shiftDragSpeed`.   Back to you for a look, feel free to close.

**Comment by arouinfar** [comment]
Looks good on main, thanks @pixelzoom!
