### ISSUE TITLE
Adjust pdomOrder for "play area" and "control area"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#81]
Related to #14 ...

In Slack#dev-public on 2/9/24, @jessegreenberg said:
> We decided to make a small change to our process for adding alternative input to a simulation. In addition to creating a traversal order, focusable components will be categorized into "Play Area" and "Control Area" sections for the Parallel DOM.

@jessegreenberg and I discussed the approach to doing this. For this sim, it involves going to this line in each ScreenView subclass:

```ts
screenViewRootNode.pdomOrder = [ ... ];
```

... and replacing it with:

```ts
this.pdomPlayAreaNode.pdomOrder = [ ... ];
this.pdomControlAreaNode.pdomOrder = [ ... ];
```

The designer (@arouinfar for this sim) will specify specify what needs to go in play area vs control area.

**Comment by pixelzoom** [comment]
Discussed with @arouinfar at today's standup meeting.  Here are the requirements, using tandem names to identify elements:

* control area:  toolsPanel, timeControlNode, resetAllButton
* play area: everything else

**Comment by pixelzoom** [comment]
Splitting `panels` up across play area and control area was a tiny bit of additonal work.  But having used the `screenViewRootNode` approach (Approach 1 in the quickstart guide) throughout this sim, it took me < 15 minutes to specify the pdomOrder for play area and control area, then test.  

@arouinfar please review. Close if OK.

**Comment by arouinfar** [comment]
Looks good on main, thanks @pixelzoom! Closing.
