### ISSUE TITLE
Dynamic layout of the AC Power Supply

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#82]
Related to #62 ...

How should dynamic layout of the AC Power Supply behave? 

For exampe, if we hide `frequencyControl` and `maxVoltageControl`, we currently get this:

<img width="238" alt="screenshot_3040" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/09d3258a-2520-4714-b941-66d5c238321b">

**Comment by pixelzoom** [comment]
@arouinfar ready for review, close if OK

Screenshots below show the various layouts, based on the values of `frequencyControl.visibleProperty` and `maxVoltageControl.visibleProperty`.   

I also fixed a general layout problem.  The power supplies were not quite horiztonally centered on the coil, because I wasn't including the background layer of the coil in the bounds.

<img width="242" alt="screenshot_3042" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/1107995c-1fe0-4206-92be-3b79ef0b4b43">

<img width="222" alt="screenshot_3045" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/80929089-b054-449a-a72a-af0fc5cd2863">

<img width="185" alt="screenshot_3043" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/16798ccc-b64a-4dfa-bce9-da24aa443e23">

<img width="211" alt="screenshot_3044" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/0c58a9f9-b10b-4957-8771-94fcd5ebab9e">

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom! Closing.
