### ISSUE TITLE
Field meter should display small gauss values as "< 0.01" instead of "0.00"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#84]
In https://github.com/phetsims/faradays-electromagnetic-lab/issues/77#issuecomment-1953274272, @emily-phet said:

> The sound needs to not play when B = 0.00 G on the meter. Currently still can be heard....presumably it's not actually at 0.

Correct, the magnitude (B) is not actually zero. It's just smaller than can be displayed with 2 decimals places. The field meter continues to display an angle, meaning there is a non-zero magnitude. And if you switch to Tesla units (Preferences > Simulation > Magnetic Units), you'll see these very small non-zero values in scientific notation. 

So while the sound should continue to play, I think we need to do something about the presentation of gauss (G) values that are < 0.01.   I'm going to modify the field meter to display "< 0.01" instead of "0.00".

**Comment by pixelzoom** [comment]
Done in https://github.com/phetsims/faradays-electromagnetic-lab/commit/2a1ee30e84ebdc135592c7ba90d828173e9709d9, example screenshot below.  @arouinfar please review, close if OK.

<img width="1028" alt="screenshot_3046" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/9b21ffb6-67a7-4ef4-a4e9-128aefb5a5a9">

**Comment by arouinfar** [comment]
Great idea @pixelzoom! The field meter looks good, closing.
