### ISSUE TITLE
Color matching of Bar Magnet to Compass Needles

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/faradays-electromagnetic-lab#85]
When reviewing the HTML version and revisiting the Java version, I noticed that the magnet changed to Blue/Red and I just wanted to open this issue to note that their was a pedagogical choice to the prior design. 

The original magnet design had a "white end" a "grey middle" and a "red end", with the white in as South and red end as North poles. I believe we did this intentionally to have clear S and N ends, and so that the S/N colors matched the white and red ends of the mini compass needles. 

With the current HTML color scheme, we don't have that matching we have the field needs as white/red south/north, but the magnet as blue/red south/north. Right now there is no mapping you can use to decide that "white"== "south" end on the compass needles, which feels important pedagogically. 

@arouinfar, please have a review and tag for design meeting as you see fit.

**Comment by kathy-phet** [comment]
One additional observation, with the full half of the bar magnet being red, the red end of the compass needles is more hidden for a larger part of the magnet when you hit "see inside". The grey center of the magnet had an advantage in this way.

**Comment by arouinfar** [comment]
Thanks @kathy-phet. There is still an open issue to finalize the sim colors, see #32.

The current colors match up with what would be most typical in a classroom setting -- magnets are usually red/blue and compasses are usually red/white. It does not appear that red/white magnets are typical, but I can understand why we made that choice in Java.

Here's what it would like with a pure white south pole:
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/abae259f-f561-4214-b549-d227c8d62521" width=400> <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/40e7a6aa-2c84-458a-8ac9-f25e232180d4" width=400>

I don't think white will work in projector mode, though. We could use a light grey instead, either for just projector mode or for both color profiles:
<img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/95f204fe-bde8-4273-a966-b8e45749b87d" width=400> <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/575b6b8c-606b-478e-a76e-4d74db7f137e" width=400>

> One additional observation, with the full half of the bar magnet being red, the red end of the compass needles is more hidden for a larger part of the magnet when you hit "see inside". The grey center of the magnet had an advantage in this way.

I think we can address this by a combination of increasing the opacity and stroke weight of the compass needles.

**Comment by pixelzoom** [comment]
I'll defer to @arouinfar for finalizing the colors. But a few comments:

* I changed to red/blue for the bar magnet based on a prior request for standardization with the Faraday's Law sim.
* If you do a Google search for bar magnets, you'll see that red/blue is overwhelmingly the standard.
* If you do a Google search for compass, you'll see that red/white is overwhelmingly the standard, with red/black a distant second. And there is no correspondence to bar magnet colors -- perhaps students should learn that?
* As @arouinfar pointed out, red/white for the bar magnet is problematic in projector mode.  Red/blue as no problems.

**Comment by kathy-phet** [comment]
One additional thought that could be a different way to scaffold would be to put icons next to compass and field meter, and use something labeled like this to help know that "white"== south for the compass needles? 
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/5096804/cd85401d-119b-4aa2-a3d3-2c07bbd30f8a)

**Comment by pixelzoom** [comment]
I like the icon idea.  How about something like this? (screenshot below)  I put the "S" and "N" labels outside the ends of the needle, so that they will be legible (and more easily localized).  And the icon to use for the field meter is a separate issue.

<img width="288" alt="screenshot_3055" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/a1cc847c-782f-4080-b69d-88037b29dbdb">


In case we go in this direction, here's a note for myself:

<details>
<summary>ugly quick-&-dirty patch</summary>

```diff
Subject: [PATCH] fix alphabetical order of team, #2
---
Index: js/common/view/ToolsPanel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/ToolsPanel.ts b/js/common/view/ToolsPanel.ts
--- a/js/common/view/ToolsPanel.ts	(revision b25b8cc60ec977c64359cdb8bf28a9cea11da8d9)
+++ b/js/common/view/ToolsPanel.ts	(date 1709002168832)
@@ -9,7 +9,7 @@
 import faradaysElectromagneticLab from '../../faradaysElectromagneticLab.js';
 import Panel, { PanelOptions } from '../../../../sun/js/Panel.js';
 import Checkbox, { CheckboxOptions } from '../../../../sun/js/Checkbox.js';
-import { Text, VBox, VBoxOptions } from '../../../../scenery/js/imports.js';
+import { Circle, HBox, Node, Text, VBox, VBoxOptions } from '../../../../scenery/js/imports.js';
 import { combineOptions, optionize4 } from '../../../../phet-core/js/optionize.js';
 import FELConstants from '../../common/FELConstants.js';
 import FaradaysElectromagneticLabStrings from '../../FaradaysElectromagneticLabStrings.js';
@@ -18,6 +18,11 @@
 import Property from '../../../../axon/js/Property.js';
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
 import LockToAxisCheckbox from './LockToAxisCheckbox.js';
+import CompassNeedleNode from './CompassNeedleNode.js';
+import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
+import FELColors from '../FELColors.js';
+import PlusNode from '../../../../scenery-phet/js/PlusNode.js';
+import { Dimension2 } from '../../../../dot/js/imports.js';
 
 type SelfOptions = {
 
@@ -37,17 +42,60 @@
       isLockedToAxisProperty: null
     }, providedOptions );
 
+    const compassIcon = new HBox( {
+      children: [
+        new Text( 'S', { font: new PhetFont( 13 ) } ),
+        new CompassNeedleNode( { length: 30 } ),
+        new Text( 'N', { font: new PhetFont( 13 ) } )
+      ],
+      spacing: 3,
+      layoutOptions: {
+        stretch: false // prevent space from being introduced between text and icon
+      }
+    } );
+
     // 'Compass' checkbox
     const compassText = new Text( FaradaysElectromagneticLabStrings.compassStringProperty, FELConstants.CHECKBOX_TEXT_OPTIONS );
-    const compassCheckbox = new Checkbox( compass.visibleProperty, compassText,
+
+    const compassLabel = new HBox( {
+      children: [ compassText, compassIcon ],
+      spacing: 10,
+      layoutOptions: {
+        stretch: false // prevent space from being introduced between text and icon
+      }
+    } );
+    const compassCheckbox = new Checkbox( compass.visibleProperty, compassLabel,
       combineOptions<CheckboxOptions>( {}, FELConstants.CHECKBOX_OPTIONS, {
+        layoutOptions: {
+          stretch: false // prevent space from being introduced between text and icon
+        },
         tandem: options.tandem.createTandem( 'compassCheckbox' )
       } ) );
 
+    const circle = new Circle( 10, {
+      stroke: FELColors.fieldMeterProbeColorProperty,
+      lineWidth: 3
+    } );
+    const plus = new PlusNode( {
+      size: new Dimension2( 13, 1 ),
+      fill: 'black', //FELColors.fieldMeterProbeColorProperty,
+      center: circle.center
+    } );
+    const fieldMeterIcon = new Node( {
+      children: [ circle, plus ]
+    } );
+
     // 'Field Meter' checkbox
     const fieldMeterText = new Text( FaradaysElectromagneticLabStrings.fieldMeterStringProperty, FELConstants.CHECKBOX_TEXT_OPTIONS );
-    const fieldMeterCheckbox = new Checkbox( fieldMeter.visibleProperty, fieldMeterText,
+    const fieldMeterLabel = new HBox( {
+      children: [ fieldMeterText, fieldMeterIcon ],
+      spacing: 8
+    } );
+    const fieldMeterCheckbox = new Checkbox( fieldMeter.visibleProperty, fieldMeterLabel,
       combineOptions<CheckboxOptions>( {}, FELConstants.CHECKBOX_OPTIONS, {
+        layoutOptions: {
+          stretch: false // prevent space from being introduced between text and icon
+        },
         tandem: options.tandem.createTandem( 'fieldMeterCheckbox' )
       } ) );
```

</details>

**Comment by arouinfar** [comment]
I also like the icon idea! @pixelzoom thanks for the mockup. I like those icon choices, but I think it would be a bit easier to read if we right-aligned the icons in the panel, similar to what we do in Geometric Optics.

![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/2845dad4-1f97-4218-9a28-4a7f3a652dee)

I confirmed with `stringTest=dynamic` because the string lengths are fairly similar in English and I wasn't sure if the alignment was an optical illusion or not.

**Comment by pixelzoom** [comment]
Agreed, I had planned to right align icons. I just didn't spend the time in my "ugly quick-&-dirty patch".

So to clarify... Should I proceed with adding the icons?

**Comment by pixelzoom** [comment]
Btw... Even if the icons don't resolve @kathy-phet's original concern, I think they are a nice touch, and I recommend adding icons.

**Comment by arouinfar** [comment]
Yes, please proceed @pixelzoom.

**Comment by pixelzoom** [comment]
@arouinfar @kathy-phet icons are ready for review, see screenshot below.  Note that I also added an icon for the "Electrons" checkbox, but did not right-justify it. 

We should also check in with @kathy-phet to see if this addresses her concern about using red/blue for the bar magnet, or whether we still need to consider color-coordinating the bar magnet and compass needles. 

<img width="1150" alt="screenshot_3057" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/d208a196-a1f2-4875-90de-588ccc988c8b">

**Comment by kathy-phet** [comment]
This helps address my concerns. I like the way the icons came out. Thanks! 

I do see that the bulk of school magnets are blue / red (at least when googled from the US).

**Comment by pixelzoom** [comment]
2/29/24 design meeting with @arouinfar @kathy-phet @ariel-phet @Nancy-Salpepi @pixelzoom 

* Checkbox icons were approved.
* Concern about red/blue bar magnet is resolved.
* This issue can be closed.
