### ISSUE TITLE
When "Earth" is checked, the bar magnet points in the wrong direction.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#88]
@arouinfar noticed this in today's design meeting. Doh!

When "Earth" is checked, the bar magnet points in the wrong direction:

<img width="502" alt="screenshot_3069" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/eddaceae-7741-41c8-a31f-002eab0ae6a6">

It should look like this (Java version):

<img width="447" alt="screenshot_3070" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/704f6719-1e4c-4290-a32a-b9a4a4c2ebbf">

**Comment by pixelzoom** [comment]
Fixed, @arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Looks good, closing!
