### ISSUE TITLE
`clipArea` bug for screen icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#89]
Breaking this issue out of #28 ...

The screen icons for the _Pickup Coil_ and _Transformer_ screens are not respecting `clipArea`.   

On macOS 14.3.1, this problem occurs in both Chrome 122 and Firefox 123, but does NOT occur in Safari.

The first screenshot below shows the screen icons when the sim is started.  The second screenshot below shows what happens when you leave the home screen, then come back to the home screen. 

@jonathanolson is on the case. The backup plan is to convert those icons to images using `rasterize()`.

<img width="840" alt="screenshot_3066" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/58ca7dc6-b755-44cf-91a3-cc421decd7e5">

<img width="840" alt="screenshot_3067" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/8ef61fee-3df4-4689-8385-2a095c5923b8">

**Comment by jonathanolson** [comment]
Commit above I believe should fix this. @pixelzoom can you verify?

Looks related to https://github.com/phetsims/scenery/issues/1548.

**Comment by pixelzoom** [comment]
Yep, confirmed - that fixed it. Thanks! Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
