### ISSUE TITLE
Repo name does not match legacy sim name.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#91]
The legacy (Java) sim was "faraday", and the production version is at https://phet.colorado.edu/en/simulations/faraday.

The HTML5 version is in repo "faradays-electromagnetic-lab".    So I'm guessing it would publish to https://phet.colorado.edu/en/simulations/faradays-electromagnetic-lab.

Is this going to cause a problem when we publish?  Who would know? 

The derivative sims do not have this problem. The legacy and HTML5 names are the same: magnet-and-compass, magnets-and-electromagnets, generator.

Also note that there's already a faraday repo, which is an early prototype. I plan to delete it (see #5) but it currently exists.

**Comment by pixelzoom** [comment]
We could consider renaming the repo to "faraday", to match the legacy version.  But problems there include:

* There's already a "faraday" repo, see #5.

* It would introduce an inconsistency for PhET-iO, where (by convention) tandem names match the sim title.   E.g. `faradaysElectromagneticLab.barMagnetScreen.model.compass` vs `faraday.barMagnetScreen.model.compass`.

* Since we also have the "faradays-law" repo (which also supports PhET-iO), there's a slight concern that we'd continue to have confusion about "faraday" vs "faradays-law".

**Comment by pixelzoom** [comment]
In Slack#faradays-electromagnetic-lab, @arouinfar reminded me that we've encountered this problem before:

> We’ve had other instances where the legacy sim and repo name don’t match up. I think Gas Properties was `ideal-gas` (or similar). I think there are a few extra steps for the first production deploy that Matt Pennington can advise on, but I don’t remember the details.

**Comment by pixelzoom** [comment]
@mattpen Can you fill me in on what I'll need to do when I publish the 1.0 version of this sim?   The legacy version lives at https://phet.colorado.edu/en/simulations/faraday, and the HTL5 version needs to move to https://phet.colorado.edu/en/simulations/faradays-electromagnetic-lab.

**Comment by mattpen** [comment]
@pixelzoom - I'm not aware of any action that you need to take. I don't think there is anything in sim or common code that handles this case.  There are some data files in the website that will need new entries for the legacy -> html5 name mapping but I will take care of that.

**Comment by mattpen** [comment]
I added a goal for myself in Monday.com to work on this in this iteration, but it is likely it will get deferred to the next.  I'm hoping to have the change deployed on the website by April 3.  @pixelzoom - does that timing work for you, or will FEL be deployed to production sooner than that?

**Comment by pixelzoom** [comment]
Thanks @mattpen.  FEL is still in development, and I would estimate that the production deploy will occur sometime in April/May 2024.

**Comment by pixelzoom** [comment]
Self-assigning, so that I remember to contact @mattpen before deploying production 1.0.

**Comment by mattpen** [comment]
The two commits above should allow this to function as a normal html5 port. This is staged for the next website deploy.

**Comment by pixelzoom** [comment]
Unassigning until we get closer to publication.

**Comment by mattpen** [comment]
This change was published to production. @pixelzoom - there shouldn't be anything else to do, other than check that the behavior is correct after FEL has it's first production deployment.

**Comment by pixelzoom** [comment]
Excellent, thanks @mattpen.  I'll leave this issue open until FEL has had it's first (1.0) production deployment.

**Comment by pixelzoom** [comment]
@arouinfar The full suite of sims has been deployed.  After doing whatever you typically do to make new sims visible, please verify that there were no problems with renaming `faraday` to `faradays-electromagnetic-lab`.   If there are problems, please contact @mattpen.   If there are no problems, feel free to close this issue.

**Comment by arouinfar** [comment]
The FEL sim page is up and running at https://phet.colorado.edu/en/simulations/faradays-electromagnetic-lab and the old URL https://phet.colorado.edu/en/simulations/faraday is properly redirecting. Closing.
