### ISSUE TITLE
Set `constrainValue` to 5% in Bar Magnet Strength and Loop Area sliders

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-electromagnetic-lab#96]
We often use `constrainValue` in sliders to help students reach more reproducible values or to facilitate actions like doubling the value. I noticed that we aren't currently using it in the Bar Magnet Strength and Loop Area sliders, but I think it would be useful. @pixelzoom  can you please set `constrainValue` to 5% for both sliders? This matches the keyboard step size.

**Comment by pixelzoom** [comment]
@arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom!
