### ISSUE TITLE
Review pointer areas.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#97]
From the CRC:

>  - [ ] Are pointer areas optimized, especially for touch? (run with query parameter showPointerAreas)
> - [ ] Do pointer areas overlap? (run with query parameter `showPointerAreas`) Overlap may be OK in some cases, depending on the z-ordering (if the front-most object is supposed to occlude pointer areas) and whether objects can be moved.

**Comment by pixelzoom** [comment]
Looks good to me. Over to @arouinfar for review, close if OK.

**Comment by arouinfar** [comment]
I reviewed with `showPointerAreas` and tested on my phone (without zooming) and everything worked well. Closing.
